### ISSUE TITLE
[Bug][[Manager] Data type 'doris' not support

### ISSUE THREAD

**Issue by zhouhoo** [apache/inlong#10076]
### What happened

when I add node for doris, I did what offfical step by adding doris connector to flink lib, but I still get node type not support error.
![微信截图_20240425194405](https://github.com/apache/inlong/assets/5432592/051617de-bade-49b3-b23f-22e42530585f)

### What you expected to happen

add doris node success!

### How to reproduce

1. download latest inlong-1.12 and connectors.
1. add sort-connector-doris-1.11.0.jar to flink lib.
2. start flink
3. start inlong with standalone mode.

### Environment

linux centos 7

### InLong version

1.12.0

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@zhouhoo the manager module could not support Doris data node, do you have a plan to fix it?

**Comment by haifxu** [comment]
Test connections are temporarily not supported here, but it does not affect saving and using the `Doris` data nodes.
