### ISSUE TITLE
[Improve][CVE] net/http, x/net/http2: close connections when receiving too many headers

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#10162]
### Description

Upgrade golang.org/x/net to fix [1 Dependabot alert](https://github.com/apache/inlong/security/dependabot?q=is%3Aopen+package%3Agolang.org%2Fx%2Fnet+manifest%3Ainlong-sdk%2Fdataproxy-sdk-twins%2Fdataproxy-sdk-golang%2Fgo.mod+has%3Apatch) in [inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/go.mod](https://github.com/apache/inlong/blob/-/inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/go.mod)
Upgrade golang.org/x/net to version 0.23.0 or later. For example:

```
require golang.org/x/net v0.23.0
```

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoYou201** [comment]
I submit a pr #10163, PTAL, thx~
