### ISSUE TITLE
[Feature][Manager] Support installing agents by SSH key-based authentication

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#10261]
### Description

- SSH Authentication by username and password implemented in https://github.com/apache/inlong/pull/10098
- The Dashboard also supported the password SSH Authentication in https://github.com/apache/inlong/pull/10244

But in the product environments, most users like using key-based authentication to log in to nodes by SSH, we hope this issue can complete it.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shuiqingliu** [comment]
I would like to work on this issue.
