### ISSUE TITLE
[Improve][Manager] Change the default flink version from 1.13 to 1.15

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#10284]
### Description

Change the default flink version from 1.13 to 1.15

- the version in docker-compose
- the version in the manager plugin
- the version for the connector building

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wallezhang** [comment]
I'll try it. Please assign to me.
