### ISSUE TITLE
[Improve][Agent] Update the Oracle Source

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#10288]
### Description

the latest Agent plugin factored, Oracle Source needs to be updated, you can refer to [the development guide](https://inlong.apache.org/zh-CN/docs/next/design_and_concept/how_to_write_plugin_agent) and [MongoDB Source](https://github.com/apache/inlong/pull/10007).

<img width="480" alt="image" src="https://github.com/apache/inlong/assets/45282474/b3092635-3a35-4b38-a58a-8764f126178a">

Requirements:
1. Optimize the logic and performance
2. A set of UTs

**This issue is a dedicated issue for the 2024 Tencent Rhino-bird Open Source Talent Training event and is only available for college students to claim**
【Claim the issue】Sign up for the corresponding issue in columns M~R of the [Research and Study Base](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D) "issue Camp" to be considered as **successfully claimed**.
【Complete the issue】For students who have claimed the issue, please also reply "Successfully claimed this issue" in the comment section of this issue; if there is no progress submitted within 7 days, including but not limited to comments, commits, or Pull Requests, it will be considered as voluntarily giving up the issue and the committee will release the issue to the next person in line.

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by iendi** [comment]
Successfully claimed this issue
