### ISSUE TITLE
[Improve][CVE] Decompressors can crash the JVM and leak memory content in Aircompressor

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#10331]
### Description

![image](https://github.com/apache/inlong/assets/18047329/8d9926e4-f758-4927-8aec-80e8b0c390a2)

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoYou201** [comment]
I'd like to do this ～
