### ISSUE TITLE
[Feature][Sort] Add Elasticsearch connector on Flink 1.18

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#10467]
### Description

Add Iceberg connector on Flink 1.18 to sort-flink-v1.18, you can refer to the latest release of elasticsearch at https://github.com/apache/flink-connector-elasticsearch and the previous realization on Flink 1.15.

Location:
inlong-sort/sort-flink/sort-flink-v1.18

Requirements:
1. Support report audits to Inlong Audit with exactly once
2. End-to-end testing

Nice to have:
1. Pressure testing report

**This issue is a dedicated issue for the 2024 Tencent Rhino-bird Open Source Talent Training event and is only available for college students to claim**
【Claim the issue】Sign up for the corresponding issue in columns M~R of the [Research and Study Base](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D) "issue Camp" to be considered as **successfully claimed**.
【Complete the issue】For students who have claimed the issue, please also reply "Successfully claimed this issue" in the comment section of this issue; if there is no progress submitted within 7 days, including but not limited to comments, commits, or Pull Requests, it will be considered as voluntarily giving up the issue and the committee will release the issue to the next person in line.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoYou201** [comment]
I'd like to finish this issue~

**Comment by XiaoYou201** [comment]
This issue finish by es6 pr #10722 and es7 pr #10741 ~

**Comment by vernedeng** [comment]
> This issue finish by es6 pr #10722 and es7 pr #10741 ~

Thx @XiaoYou201
