### ISSUE TITLE
[Feature][SDK] InlongSDK support retry sending when failed

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#10464]
### Description

When InlongSDK fails to send data to DataProxy, it returns the failure to the user directly. Add the capability to retry sending.

<img width="453" alt="image" src="https://github.com/apache/inlong/assets/45282474/0efc6c79-26a9-4884-84a2-71916fa54c53">

Location:
inlong-sdk/dataproxy-sdk/

Requirements:
1. Choose another dataproxy node to resend data when the send fails.
2. Able to configure max retry times.
3. Check failures and only retry those retriable, discard those not.

**This issue is a dedicated issue for the 2024 Tencent Rhino-bird Open Source Talent Training event and is only available for college students to claim**
【Claim the issue】Sign up for the corresponding issue in columns M~R of the [Research and Study Base](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D) "issue Camp" to be considered as **successfully claimed**.
【Complete the issue】For students who have claimed the issue, please also reply "Successfully claimed this issue" in the comment section of this issue; if there is no progress submitted within 7 days, including but not limited to comments, commits, or Pull Requests, it will be considered as voluntarily giving up the issue and the committee will release the issue to the next person in line.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hackerismydream** [comment]
Successfully claimed this issue
