### ISSUE TITLE
[Improve][SDK] Optimization of ultra-long field processing in InlongSDK

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#10463]
### Description

SDK does not limit the maximum report data size, while dataproxy only supports processing a maximum of 500k bytes for each message.

<img width="510" alt="image" src="https://github.com/apache/inlong/assets/45282474/a731f070-652b-4401-bd69-3ff5ce813557">

Location:
inlong-sdk/dataproxy-sdk/

Requirements:
1. Support automatic ultra-long data truncation in SDK
2. User-configurable automatic truncation
3. Provide the default value of the allowed data length

**This issue is a dedicated issue for the 2024 Tencent Rhino-bird Open Source Talent Training event and is only available for college students to claim**
【Claim the issue】Sign up for the corresponding issue in columns M~R of the [Research and Study Base](https://docs.qq.com/sheet/DTk9YV3pXSklZZ29D) "issue Camp" to be considered as **successfully claimed**.
【Complete the issue】For students who have claimed the issue, please also reply "Successfully claimed this issue" in the comment section of this issue; if there is no progress submitted within 7 days, including but not limited to comments, commits, or Pull Requests, it will be considered as voluntarily giving up the issue and the committee will release the issue to the next person in line.

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hackerismydream** [comment]
Successfully claimed this issue

**Comment by ratSquealer** [comment]
已领取该问题

**Comment by ratSquealer** [comment]
初步写好处理代码，但是在测试TcpClientExample.java文件（根据调用修改后），报链接错误：
Connect Manager error, message: Unsupported or unrecognized SSL message
![QQ图片20240714224212](https://github.com/user-attachments/assets/ddb0c7ff-7966-4616-9061-2f75c3f9aa74)
![QQ图片20240714224423](https://github.com/user-attachments/assets/05390e93-c542-4279-a842-b78d387483a7)
在调查问题后，手动修改为http后，可以连接，但从代码角度来看，要修改TcpClientExample.java和ProxyClientConfig.java文件（重点），不知道是否进行，希望能得到导师指导。
我是在win11下面部署的inlong
![QQ图片20240714224325](https://github.com/user-attachments/assets/ae01e36f-051d-4b0d-848d-3c51a6d75344)
