### ISSUE TITLE
deleted failed

### ISSUE THREAD

**Issue by czxin788** [apache/inlong#10557]
### What happened

![image](https://github.com/apache/inlong/assets/13861904/09baf270-b18a-4f83-82ab-357f07ec5f52)

### What you expected to happen

can delete task

### How to reproduce

see above

### InLong version

1.12.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
From the screenshot, it can be seen that there is a stream in test_group_1646 that has not been deleted. You need to delete the stream in the group first in order to successfully delete the group.
