### ISSUE TITLE
[Bug] Data node type 'DORIS' not supported

### ISSUE THREAD

**Issue by lordk911** [apache/inlong#10588]
### What happened

when create a Doris data node on the web ui , got error:

Data node type 'DORIS' not supported

<img width="747" alt="image" src="https://github.com/apache/inlong/assets/19989300/81b630b6-b12f-42ab-9e3f-4ed16ff43e0f">

### What you expected to happen

.

### How to reproduce

.

### InLong version

1.12.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoYou201** [comment]
Version 1.12.0 may has some problem in web ui. You can try using master branch to deploy it~

**Comment by dockerzhang** [comment]
@lordk911 1.13.0 was released, you could try it.
