### ISSUE TITLE
[Bug]When the tenant associated with the user is not public, login is not possible.

### ISSUE THREAD

**Issue by lordk911** [apache/inlong#10586]
### What happened

I deployed inlong-1.12.0 using docker-compose
then I create a new tenant named shujugl ，and a new user named shuju-admin. 
No matter whether the user shuju-admin is an administrator, a common user, or a tenant administrator, the user cannot log in.
The login page is displayed immediately after the user logs in

### What you expected to happen

.

### How to reproduce

.

### InLong version

1.12.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@lordk911 please try the latest 1.13.0 version, and give steps to reproduce the issue, thanks.

**Comment by aloyszhang** [comment]
Close this issue since there has been no feedback for a long time, and feel free to re-open it if needed.
