### ISSUE TITLE
[Umbrella] Release InLong 1.13.0

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#10667]
### Describe the proposal

To release 1.13.0, refer to #10031

### Task list

- [x] #10656 
- [x] #10658 
- [x] #10659 
- [x] #10660 
- [x] #10661 
- [x] #10662 
- [x] #10663 
- [x] https://github.com/apache/inlong-website/issues/960
- [x] https://github.com/apache/inlong-website/issues/961
- [x] https://github.com/apache/inlong-website/issues/962

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aloyszhang** [comment]
https://inlong.apache.org/blog/2024/07/18/release-1.13.0   1.13 has been released.
