### ISSUE TITLE
【咨询】iceberg sink新增列

### ISSUE THREAD

**Issue by tivontang** [apache/inlong#10699]
flink iceberg sink, 如果sink table运营中新增列，是否需要重启任务，如果不重启，项目如何实现处理该场景

**Comment by vernedeng** [comment]
> flink iceberg sink, 如果sink table运营中新增列，是否需要重启任务，如果不重启，项目如何实现处理该场景

目前必须重启任务。这个问题其实可以通过新增一个算子来实现， 每次 checkpoint 时该算子获取最新的 table schema，并更新其他算子
