### ISSUE TITLE
[Feature][SDK] Transform SQL support Round function 

### ISSUE THREAD

**Issue by Zkplo** [apache/inlong#10803]
### Description
- parent issue #10796

ROUND(x [,y])：

- x: Numbers that need to be rounded. It can be an integer or a floating point number.
- y: Optional parameter, indicating the number of decimal places to be rounded.
  - If y is omitted, it means rounding x to an integer.
  - If y is a positive number, it means rounding x to y decimal places.
  - If y is negative, it means rounding x to the nearest y decimal place.

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aloyszhang** [comment]
<img width="897" alt="image" src="https://github.com/user-attachments/assets/394d1f0e-c1ca-479b-b871-39304d4d2d7b">
FYI, the pull request can be modified many times. You don't need to create a new pull request if you want to make some modifications.

**Comment by Zkplo** [comment]
> <img alt="image" width="897" src="https://private-user-images.githubusercontent.com/48062889/358960411-394d1f0e-c1ca-479b-b871-39304d4d2d7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjE0NTQsIm5iZiI6MTcyNDEyMTE1NCwicGF0aCI6Ii80ODA2Mjg4OS8zNTg5NjA0MTEtMzk0ZDFmMGUtYzFjYS00NzliLWI4NzEtMzkzMDRkNGQyZDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAyMzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNzhhOWEzOTI3NzNjNjU3NzgwMDU2NTRlNmU0YTBiZTAzMTFlMjAwODc4ZGUyYTA1ODFiNjdjMmQ4ZGQ1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wTvpWhjT7Cdd0AR_LG_P_lXEGUCkdPlIOhLTH4bDmOM"> FYI, the pull request can be modified many times. You don't need to close and create a new pull request if you want to make some modifications.
> 仅供参考，拉取请求可以修改多次。如果您想进行一些修改，则无需关闭并创建新的拉取请求。

Thank you for your suggestion. I will pay attention to it in the future.
