### ISSUE TITLE
[Feature][SDK] Transform SQL support sign function

### ISSUE THREAD

**Issue by Zkplo** [apache/inlong#10866]
### Description

- parent issue #10796

sign(x): Return the sign of x, where x is a negative number, 0, and positive numbers return -1, 0, and 1, respectively

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aloyszhang** [comment]
Hi, @Zkplo
FYI, if there is something wrong with your branch, you can rebase the master again and force push to your branch. It does not need to open a brand-new pull request. 

You can try this way next time if you meet the same problem again.
