### ISSUE TITLE
[Feature][SDK] Transform support factorial function

### ISSUE THREAD

**Issue by youzhi886** [apache/inlong#10873]
### Description

-parent issue #10796
Factorial(numeric)--returns the factorial of a non-negative
Example:
5! = 120

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by emptyOVO** [comment]
I will continue to complete this issue
