### ISSUE TITLE
[Feature][SDK] Transform SQL support Fibonacci function

### ISSUE THREAD

**Issue by youzhi886** [apache/inlong#11002]
### Description

parent issue [Umbrella] Tencent Rhino-bird: Expand InLong Transform functions #10796 
definition of Fibonacci sequence:
F(0) = 0
F(1) = 1
对于 n >= 2，F(n) = F(n-1) + F(n-2)
F(2) = 1 （1 = 1 + 0）
F(3) = 2 （2 = 1 + 1）
F(4) = 3 （3 = 2 + 1）
fibonacci(numeric)--returns the nth Fibonacci number
examples:
fibonacci(0) = 0
fibonacci(4) = 3

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by emptyOVO** [comment]
I will continue to complete this issue
