### ISSUE TITLE
[Feature] Add adaptation to Signoz

### ISSUE THREAD

**Issue by sususama** [apache/inlong#11267]
### Description

New document describing inlong adaptation to Signoz

### Use case

Add new document

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aloyszhang** [comment]
Issue for web-site repository should be created here https://github.com/apache/inlong-website/issues
