### ISSUE TITLE
[Feature][Manager] Support Airflow schedule engine

### ISSUE THREAD

**Issue by aloyszhang** [apache/inlong#11400]
### Description

Currently, InLong supports both real-time and offline data synchronization.
The offline data sync is scheduled repeatedly by the schedule engine.
#10412 introduced a built-in schedule engine and #10515 supports the built-in engine to trigger the Flink batch job.
So, InLong has the basic capability for offline data synchronization. 

There are some mature and stable scheduling engines like [Apache Airflow](https://airflow.apache.org) and [Apache Dolphinscheduler](https://dolphinscheduler.apache.org/). It will be helpful for Inlong to support these scheduling engines in offline data synchronization.

This issue is part of this which aims to support Apache Airflow.

Ref:
[InLong offline synchronization ](https://github.com/apache/inlong/issues/9779)
[Offline data synchronization Example](https://inlong.apache.org/docs/next/quick_start/offline_data_sync/pulsar_mysql_example/)
[Offline Sync Connector Extension](https://inlong.apache.org/docs/next/development/extension_sort/offline_data_sync)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zkplo** [comment]
I am interested in this issue, can you assign it to me?

**Comment by PeterZh6** [comment]
I am interested in this issue and willing to contribute.
