### ISSUE TITLE
[Bug]数据同步时jobmanager报错

### ISSUE THREAD

**Issue by qwe123520** [apache/inlong#11456]
### What happened

jobmanager  | 2024-11-05 03:00:53,854 ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Failed to create Source Enumerator for source Source: table_vi-dev[5]
jobmanager  | java.lang.NoSuchMethodError: 'void io.debezium.jdbc.JdbcConnection.<init>(io.debezium.config.Configuration, io.debezium.jdbc.JdbcConnection$ConnectionFactory)'
jobmanager  |   at com.ververica.cdc.connectors.mysql.debezium.DebeziumUtils.openJdbcConnection(DebeziumUtils.java:58) ~[sort-connector-mysql-cdc-v1.15-2.0.0.jar:2.3.0]
jobmanager  |   at com.ververica.cdc.connectors.mysql.MySqlValidator.validate(MySqlValidator.java:72) ~[sort-connector-mysql-cdc-v1.15-2.0.0.jar:2.3.0]
jobmanager  |   at org.apache.inlong.sort.mysql.source.MySqlSource.createEnumerator(MySqlSource.java:180) ~[sort-connector-mysql-cdc-v1.15-2.0.0.jar:2.3.0]
jobmanager  |   at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:197) ~[flink-dist-1.15.4.jar:1.15.4]
jobmanager  |   at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$DeferrableCoordinator.resetAndStart(RecreateOnResetOperatorCoordinator.java:394) ~[flink-dist-1.15.4.jar:1.15.4]
jobmanager  |   at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator.lambda$resetToCheckpoint$6(RecreateOnResetOperatorCoordinator.java:144) ~[flink-dist-1.15.4.jar:1.15.4]
jobmanager  |   at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
jobmanager  |   at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
jobmanager  |   at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
jobmanager  |   at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
jobmanager  |   at org.apache.flink.runtime.operators.coordination.ComponentClosingUtils.lambda$closeAsyncWithTimeout$0(ComponentClosingUtils.java:77) ~[flink-dist-1.15.4.jar:1.15.4]
jobmanager  |   at java.lang.Thread.run(Unknown Source) [?:?]

### What you expected to happen

可以成功启动，并不报错

### How to reproduce

mysql同步到mysql即可实现，使用docker部署模式

### InLong version

2.0.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
May I ask if this real-time synchronization task was initiated through the `InLong Manager` or directly submitted to the Flink?

**Comment by qwe123520** [comment]
通过inlong的taskmanager提交的，不是直接调用的fink
