### ISSUE TITLE
[Bug][Dashboard] The "next" button of the data synchronization module is invalid

### ISSUE THREAD

**Issue by qy-liuhuo** [apache/inlong#11478]
### What happened

After creating a data synchronization task in the inlong dashboard, do not submit it directly, return and enter again, then the next button will be invalid. 

### What you expected to happen

I got the err msg in browser console:

```js
4577.97fb8884.chunk.js:1 
 Uncaught (in promise) TypeError: n.join is not a function
    at 4577.97fb8884.chunk.js:1:7112
    at d (main.3841acf9.js:2:1653059)
    at Generator._invoke (main.3841acf9.js:2:1652812)
    at Generator.next (main.3841acf9.js:2:1653422)
    at r (main.3841acf9.js:2:1646506)
    at c (main.3841acf9.js:2:1646709)
```

### How to reproduce

1. Create a data synchronization task
![image](https://github.com/user-attachments/assets/587d84e4-62f0-4cfb-917d-687530ae83bc)
![image](https://github.com/user-attachments/assets/76458348-8709-4748-86c5-8b17ac69fbfe)
2. Don't submit, just return
![image](https://github.com/user-attachments/assets/38d7b1d6-7f3d-4f48-a1e0-b6c76ae03f85)
3. Re-enter the task you just created
![image](https://github.com/user-attachments/assets/3157f8b0-54c1-4efa-b161-d220f02ab5fc)
4. Click the `Next` button, you will find the button is invalid
![image](https://github.com/user-attachments/assets/23941ef8-76c1-4e0d-a651-11849667809e)

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wohainilaodou** [comment]
It has been solved in this PR https://github.com/apache/inlong/pull/11486
