### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by KingkINGK** [apache/inlong#11555]
### What happened

我使用：https://inlong.apache.org/zh-CN/docs/deployment/standalone 文档进行单机部署，按照https://inlong.apache.org/zh-CN/docs/quick_start/data_ingestion/file_pulsar_clickhouse_example 示例进行数据同步。显示配置成功数据流中的数据源一直是待下发添加状态。

### What you expected to happen

查看manager日志。
manager的error.log有如下相关：[ ] 2024-11-29 09:31:40.458 -ERROR [inlong-plugin-0] .p.f.FlinkParallelismOptimizer:86 - Error retrieving data volume: Illegal character in scheme name at index 0: 127.0.0.1:10080/audit/query/minutes?startTime=2024-11-29T08:31:40.452&endTime=2024-11-29T09:31:40.452&inlongGroupId=p112909&inlongStreamId=p112909sjl&auditId=6&auditCycle=1
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:10080/audit/query/minutes?startTime=2024-11-29T08:31:40.452&endTime=2024-11-29T09:31:40.452&inlongGroupId=p112909&inlongStreamId=p112909sjl&auditId=6&auditCycle=1
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 127.0.0.1:10080/audit/query/minutes?startTime=2024-11-29T08:31:40.452&endTime=2024-11-29T09:31:40.452&inlongGroupId=p112909&inlongStreamId=p112909sjl&auditId=6&auditCycle=1
[ ] 2024-11-29 09:32:16.753 -ERROR [inlong-plugin-1] .p.f.FlinkParallelismOptimizer:86 - Error retrieving data volume: Illegal character in scheme name at index 0: 127.0.0.1:10080/audit/query/minutes?startTime=2024-11-29T08:32:16.752&endTime=2024-11-29T09:32:16.752&inlongGroupId=p112909&inlongStreamId=p112909sjl&auditId=6&auditCycle=1
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:10080/audit/query/minutes?startTime=2024-11-29T08:32:16.752&endTime=2024-11-29T09:32:16.752&inlongGroupId=p112909&inlongStreamId=p112909sjl&auditId=6&auditCycle=1
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 127.0.0.1:10080/audit/query/minutes?startTime=2024-11-29T08:32:16.752&endTime=2024-11-29T09:32:16.752&inlongGroupId=p112909&inlongStreamId=p112909sjl&auditId=6&auditCycle=1

### How to reproduce

https://inlong.apache.org/zh-CN/docs/deployment/standalone 文档进行单机部署，按照https://inlong.apache.org/zh-CN/docs/quick_start/data_ingestion/file_pulsar_clickhouse_example 示例进行数据同步。

### Environment

linux centos7

### InLong version

2.0.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KingkINGK** [comment]
![inlong待下发](https://github.com/user-attachments/assets/cce5cb52-66f6-4db4-9f40-8311fa9d0ec0)

**Comment by wohainilaodou** [comment]
> 图片如下：![inlong待下发](https://private-user-images.githubusercontent.com/16586821/390937914-cce5cb52-66f6-4db4-9f40-8311fa9d0ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTA4NjIsIm5iZiI6MTczMzIxMDU2MiwicGF0aCI6Ii8xNjU4NjgyMS8zOTA5Mzc5MTQtY2NlNWNiNTItNjZmNi00ZGI0LTlmNDAtODMxMWZhOWQwZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA3MjI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOGY4Nzk2N2RkM2Y0NmQ0ODA2NjExYTYzOTAzNzQ3ZGMzMThhZDg4MTk1MTg2Njk3NzU4ZDk1ODc5NTYzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WTwpWQHeetgAMvF90afHVH7w3VknZ0eybj0L1Pc2uj4)

This state is normal

**Comment by KingkINGK** [comment]
> > 图片如下：![inlong待下发](https://private-user-images.githubusercontent.com/16586821/390937914-cce5cb52-66f6-4db4-9f40-8311fa9d0ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTA4NjIsIm5iZiI6MTczMzIxMDU2MiwicGF0aCI6Ii8xNjU4NjgyMS8zOTA5Mzc5MTQtY2NlNWNiNTItNjZmNi00ZGI0LTlmNDAtODMxMWZhOWQwZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA3MjI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOGY4Nzk2N2RkM2Y0NmQ0ODA2NjExYTYzOTAzNzQ3ZGMzMThhZDg4MTk1MTg2Njk3NzU4ZDk1ODc5NTYzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WTwpWQHeetgAMvF90afHVH7w3VknZ0eybj0L1Pc2uj4)
> 
> This state is normal

这个 state  是在等待哪个组件运行吗？ 我在文档中没有找到相关的说明。
