### ISSUE TITLE
[Bug][TubeMQ] Go SDK load balance logic not perfect, causing consumption to stop suddenly

### ISSUE THREAD

**Issue by yuexihan** [apache/inlong#11583]
### What happened

consumption suddenly stop
![image](https://github.com/user-attachments/assets/b0ad2b2d-7384-45de-859a-75fbb0fdcce1)

### What you expected to happen

1. If the old code fails to register to Master again, there will be no further actions. It needs to be changed to continue retrying indefinitely upon failure.
<img width="716" alt="企业微信截图_17334052584263" src="https://github.com/user-attachments/assets/2227aa5c-4449-4d0a-88e2-1926e9508490">

2. OfferEventAndNotify is responsible for receiving rebalance events, while OfferEventResult handles the results of those events. Therefore, the former should definitely not operate on rebalanceResults, nor should it reprocess the header of rebalanceResults as if it were a newly received event. Otherwise, if the result of the previous event has not been reported yet when the second event arrives, the subsequent processRebalanceEvent will end up processing the first event again, causing the second received event to be discarded.
<img width="684" alt="企业微信截图_1733405369322" src="https://github.com/user-attachments/assets/981fceea-28cc-4371-a360-edcd00fc7d58">

3. ip_selector directly returns the domain name, while the connection pool maintains one connection per address, and it will not reconnect as long as the packet sending and receiving are normal. If there is a cluster switch, as long as the old master is sending and receiving packets normally, even if the registration fails, the TCP connection will not reconnect. Therefore, it is necessary to resolve the domain name into an IP address before returning it. During a cluster switch, a new IP can be returned by re-selecting. 
<img width="537" alt="企业微信截图_17334056241261" src="https://github.com/user-attachments/assets/05bfeeb0-847c-42e0-b417-7928b4e9e83d">

4. Here, there is no check to see if rsp's success is true. If a cluster change causes the master to no longer recognize the client, it will continue to send heartbeats without re-registering.
<img width="697" alt="企业微信截图_17334061728723" src="https://github.com/user-attachments/assets/097f42f7-0147-49bb-8525-e1c6f3dff393">

### How to reproduce

when master changes

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Thanks @yuexihan
