### ISSUE TITLE
[INLONG-720] Dataproxy Support Kafka

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#1309]
InLong only supports TubeMQ and Pulsar now, we can support using Kafka to extend its usage scenario.

<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-720">[INLONG-720]</a> created by dockerzhang</i>

**Comment by walkhan** [comment]
@dockerzhang 你好！针对Dataproxy 对Kafka的支持，我觉着是有必要的。kafka因为是绝大公司在生产使用的。另外manager端界面上也是需要支持，毕竟界面配置更符合现在的技术融合了。
       另外，我们这边场景涉及到binlong,埋点日志及上游提供的http数据。
    通过一段时间大概调研了下inlong，这种消息队列的同步也进一步减少了各种组件的维护。不愿意使用Pulsar的原因，是因为公司层面还觉着Pulsar当前不是特别稳定，不愿意冒哪个风险，毕竟kafka已经相当成熟了。
  所以建议社区，能将kafka尽快支持Dataproxy 和manager。这样对社区产品的使用上也会有更多的用户参与进来。

**Comment by luchunliang** [comment]
This issue have implemented in the PR: https://github.com/apache/inlong/pull/2442.
