### ISSUE TITLE
[INLONG-737] Supports Chinese and English for Swagger API

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#1326]
<i>JIRA link - <a href="https://issues.apache.org/jira/browse/INLONG-737">[INLONG-737]</a> created by healchow</i>

**Comment by aloyszhang** [comment]
@healchow This isssue was created month ago, so how's going on here?

**Comment by healchow** [comment]
It's not necessary to support i18n in the Swagger APIs.
First of all, Swagger's tags do not support internationalization, and the APIs of other open-source projects do not specifically support internationalization.
Our document already supports internationalization, and that's enough.
