### ISSUE TITLE
[Feature]  [InLong audit] Naming Service  for audit

### ISSUE THREAD

**Issue by doleyzi** [apache/inlong#1737]
### Description

This is a sub issue for releasing InLong audit.
![image](https://user-images.githubusercontent.com/43397300/140050974-59a24477-63e7-4bc0-8499-889bc19c3dd9.png)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
impleted in https://github.com/apache/inlong/issues/1737, close it.
