### ISSUE TITLE
[Feature] support collect data from debezium 

### ISSUE THREAD

**Issue by huzk8** [apache/inlong#2520]
### Description

support collect mysql cdc data 

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
InLong support collects MySQL data using debezium, so this issue will close now.
https://inlong.apache.org/docs/next/data_node/extract_node/mysql-cdc
