### ISSUE TITLE
[Feature][Manager] Make the default admin account configurable

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#3680]
### Description

the default admin account is defined in the file `conf/application.properties` of the `manager` module like this:
```
default.admin.user=admin
default.admin.password=inlong
```
We can make it configurable for different users, especially for the password.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mroccyen** [comment]
Please assign to me. I'll try to work on this.

**Comment by wilburjiang0** [comment]
Please assign this issue to me, thx. @dockerzhang

**Comment by dockerzhang** [comment]
Hi, @mroccyen thanks. due to @wilburjiang0 is doing this issue, I will assign it to him.

**Comment by dockerzhang** [comment]
it's better to fix it when https://github.com/apache/inlong/issues/5049 all issues have done.

**Comment by healchow** [comment]
Fixed by #6206.
