### ISSUE TITLE
[Improve] Initialize database by SQL file automatic

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#3690]
### Description

Initialize database by SQL file automatic, including [Manager](https://inlong.apache.org/docs/next/modules/manager/quick_start/) and [Audit](https://inlong.apache.org/docs/next/modules/audit/quick_start/).
you can refer to https://docs.spring.io/spring-boot/docs/2.0.0.M2/reference/html/howto-database-initialization.html#howto-initialize-a-database-using-spring-jdbc

### InLong Component

InLong Manager, InLong Audit

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mroccyen** [comment]
Please assign to me. I'll try to work on this.

**Comment by Trydamere** [comment]
hi, @dockerzhang, I learned the project on the Tencent opensource program. I am willing to contribute to the project. Can I try to work on this issue?

**Comment by dockerzhang** [comment]
@mroccyen assigned to you.

**Comment by dockerzhang** [comment]
@mroccyen can you still work on this?

**Comment by tunsuy** [comment]
有具体的sql文件吗

**Comment by mroccyen** [comment]
> @mroccyen can you still work on this?

yep
