### ISSUE TITLE
[Bug][Manager]Execution exception status also changes to success

### ISSUE THREAD

**Issue by Greedyu** [apache/inlong#3889]
### What happened

Click Execute when it fails, and the status will jump to success. But it still failed.
![image](https://user-images.githubusercontent.com/20356765/164709859-847f822b-65bb-4e57-883e-1bff06259fb6.png)

### What you expected to happen

-

### How to reproduce

When one of the initialization steps fails, manually click the execution trigger

### Environment

centos

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by herywang** [comment]
I ran into the same bug
