### ISSUE TITLE
[Feature][Manager] MQ module support Kafka middleware

### ISSUE THREAD

**Issue by herywang** [apache/inlong#3950]
### Description

Inlong MQ support Kafka middleware, including:
1. kafka mq management.
2. Initializing kafka topic in creating workflow

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haifxu** [comment]
Kafka MQ is already supported.
#5389 [INLONG-4976][Manager] The Manager module supports the use of Kafka
#6455 [INLONG-6451][Manager] Optimize the resource process of Kafka MQ
