### ISSUE TITLE
[Feature][Agent] Support CloudEvents

### ISSUE THREAD

**Issue by xuesongxs** [apache/inlong#4080]
### Description

Support CloudEvents in Agent.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@xuesongxs please add more description about this issue, why do we need to support CloudEvents in the agent? do we have a specific use case?

**Comment by dockerzhang** [comment]
duplicate with https://github.com/apache/inlong/issues/4987, so close it.
