### ISSUE TITLE
[BUG][TubeMQ] All images can not work when using go example

### ISSUE THREAD

**Issue by bigdaronlee163** [apache/inlong#4123]
### What happened

I want to run the example code  in tubemq-client-go， when i run tubemq using `docker run -p 8080:8080 -p 8715:8715 -p 8123:8123 -p 2181:2181 --name tubemq -d inlong/tubemq-all:latest`  ,and then I run the code in example in tubemq-client-go, with error reporting . 

![image](https://user-images.githubusercontent.com/49524138/167276756-49ab5ed5-bf33-4e55-9700-10bfbee63d8f.png)

![image](https://user-images.githubusercontent.com/49524138/167276852-8878caa6-49ca-468e-9708-55352ff27e0b.png)

### What you expected to happen

run example code with right behavior

### How to reproduce

1. docker run -p 8099:8099 -p 8080:8080 -p 8715:8715 -p 8123:8123 -p 2181:2181 --name tubemq -d inlong/tubemq-all:latest
2. run example  code  in tubemq-client-go

### Environment

版本	Windows 10 家庭中文版
版本号	21H2
安装日期	‎2021/‎11/‎6
操作系统内部版本	19044.1645
体验	Windows Feature Experience Pack 120.2212.4170.0

### InLong version

1.1.0

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@TszKitLo40 PTAL, thanks.

**Comment by TszKitLo40** [comment]
@bigdaronlee163 Do you run the code in  https://github.com/apache/incubator-inlong/blob/master/inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/consumer.go? It is just an example for the users. which means you may need to replace by the correct address by yourself. The address is `127.0.0.1:8099?topic=test_1&group=test_group`. So you need to change the port to the correct TubeMQ port, and you also need to make sure that there is a topic  called `test_1` and a group called `test_group` in the corresponding TubeMQ server.

**Comment by bigdaronlee163** [comment]
yes, I run the code https://github.com/apache/incubator-inlong/blob/master/inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/consumer.go. But I run the tubemq images with docker and export port according to  https://inlong.apache.org/zh-CN/docs/modules/tubemq/quick_start . After tubemq-all container running, I create test_topic and test_group in 127.0.0.1:8080， there is still error when running the code https://github.com/apache/incubator-inlong/blob/master/inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/consumer.go. 

![image](https://user-images.githubusercontent.com/49524138/167279498-1043e2e4-0b47-4d97-8c0c-988e5a1bd4f3.png)


![image](https://user-images.githubusercontent.com/49524138/167279462-5b3f5ffe-aa70-4b94-af85-48c090c427b1.png)

**Comment by TszKitLo40** [comment]
The topic name should be `test_1` instead of `test_topic`.

**Comment by TszKitLo40** [comment]
> yes, I run the code https://github.com/apache/incubator-inlong/blob/master/inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/consumer.go. But I run the tubemq images with docker and export port according to https://inlong.apache.org/zh-CN/docs/modules/tubemq/quick_start . After tubemq-all container running, I create test_topic and test_group in 127.0.0.1:8080， there is still error when running the code https://github.com/apache/incubator-inlong/blob/master/inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/consumer.go.
> 
> ![image](https://user-images.githubusercontent.com/49524138/167279498-1043e2e4-0b47-4d97-8c0c-988e5a1bd4f3.png)
> 
> ![image](https://user-images.githubusercontent.com/49524138/167279462-5b3f5ffe-aa70-4b94-af85-48c090c427b1.png)
> 
> @TszKitLo40


The topic name should be test_1 instead of test_topic.

**Comment by bigdaronlee163** [comment]
![image](https://user-images.githubusercontent.com/49524138/167280035-edd55bed-2e65-46b1-bb2d-f82dbe38e869.png)

**Comment by TszKitLo40** [comment]
Maybe you also need to provide the log the TubeMQ server. @gosonzhang PTAL

**Comment by TszKitLo40** [comment]
Is your master address `127.0.0.1:8099`? @bigdaronlee163

**Comment by bigdaronlee163** [comment]
> Is your master address `127.0.0.1:8099`? @bigdaronlee163

yes , I will submit log soon

**Comment by bigdaronlee163** [comment]
[gc.log.2022-05-08-06-53-23.0.current.log](https://github.com/apache/incubator-inlong/files/8646522/gc.log.2022-05-08-06-53-23.0.current.log)
[master.log](https://github.com/apache/incubator-inlong/files/8646523/master.log)
[broker.log](https://github.com/apache/incubator-inlong/files/8646524/broker.log)
[gc.log.2022-05-08-06-53-19.0.current.log](https://github.com/apache/incubator-inlong/files/8646525/gc.log.2022-05-08-06-53-19.0.current.log)

there are logs， but I donot find any exception.

**Comment by bigdaronlee163** [comment]
I will try java client to test the running tubemq-all

**Comment by bigdaronlee163** [comment]
It may be the lack of data producers.....
