### ISSUE TITLE
[Improve][Manager] Not pass the type field when querying sources and sinks

### ISSUE THREAD

**Issue by healchow** [apache/inlong#4133]
### Description

Not pass the type field when querying sources and sinks.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
I will deal with this problem.
