### ISSUE TITLE
[Feature][Sort] Sort lightwieght support load data to DLC

### ISSUE THREAD

**Issue by thexiay** [apache/inlong#4431]
### Description

Sort lightwieght support load data to DLC.
DLC describe: https://cloud.tencent.com/product/dlc

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by thesumery** [comment]
please assgin to me.
