### ISSUE TITLE
[Improve][Manager] Change the operating classes name from Operation to Operator

### ISSUE THREAD

**Issue by healchow** [apache/inlong#4701]
### Description

Change the operating classes name from Operation to Operator.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wilburjiang0** [comment]
hi @healchow ,please assign this issue to me, thx.
