### ISSUE TITLE
[Bug][Manager] Should not start the Init-Sort process when there is no sink info

### ISSUE THREAD

**Issue by GanfengTan** [apache/inlong#4715]
### What happened

1. No configuration sink
<img width="1729" alt="企业微信截图_2852a6f6-ae2f-4a85-a1cb-d6f0d9e9ada8" src="https://user-images.githubusercontent.com/17596132/174709238-9d7a2d89-2399-4773-aa42-c1cfee667aad.png">
2. Start Sort
<img width="1018" alt="企业微信截图_ac7bff4a-e1d8-4100-82e5-3bfc60de1bcb" src="https://user-images.githubusercontent.com/17596132/174709260-1475cce4-5e8e-44ff-b4c9-5fc03e24f8bc.png">

### What you expected to happen

Only the collection process is required.

### How to reproduce

agent-->dataproxy-->tube

### InLong version

1.2.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woofyzhao** [comment]
1. Remove skip resolver to simply workflow processing.
2. Annihilate unnecessary work when no sink is configured.

**Comment by healchow** [comment]
> 1. Remove skip resolver to simply workflow processing.
> 2. Annihilate unnecessary work when no sink is configured.

Thanks for your contribution 🎉
