### ISSUE TITLE
[Bug][Manager] The task retry error information is not detailed and NPE

### ISSUE THREAD

**Issue by GanfengTan** [apache/inlong#4766]
### What happened

Invalid task retry and NPE.
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/17596132/175460391-340de6a7-5b25-46ce-ab11-1b31f10b7c52.png">

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/17596132/175460551-5246236c-627b-4bd8-8ecf-420967145d4a.png">

### What you expected to happen

Tasks can be retried with detailed error messages.

### How to reproduce

For example: the configuration task cannot submit the task.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woofyzhao** [comment]
Looking into this.
