### ISSUE TITLE
[Improve][Doc] Maven jar url is malformed

### ISSUE THREAD

**Issue by boatrainlsz** [apache/inlong#4773]
### Description

The Maven jar url in [quickstart page](https://inlong.apache.org/docs/modules/manager/quick_start) is malformed:
![image](https://user-images.githubusercontent.com/18243785/175752669-ac6c8eda-b1a1-4490-8760-892a7e94f43d.png)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Hi, thanks for your contribution.
By the way, just need to create one `Issue` for one specific problem, so I'll close this one.

**Comment by boatrainlsz** [comment]
> Hi, thanks for your contribution. By the way, just need to create one `Issue` for one specific problem, so I'll close this one.

Thanks for your advice.
