### ISSUE TITLE
[Feature][Manager] Support auth and encryption key of user config

### ISSUE THREAD

**Issue by woofyzhao** [apache/inlong#4774]
### Background

In scenarios where the source of data (e.g. dataproxy sdk or agent) is located outside of idc and the data has to be transferred through insecure / public networks, it is better to enable the clients the ability to authenticate with server and encrypt their data. 

### Use case

Insecure network data transmission.

### Interaction
We use AES encryption to secure data transfer. The AES key is generated each time by the client and is encrypted and decrypted by each client's own RSA key pairs. The RSA key pairs are retrieved from manager when the clients are properly authenticated.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/941634/176112250-e60c0131-c799-42a6-97d9-27c8b8a66d97.png">

### Progress
The function may be implemented with several PRs. 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gong** [comment]
@woofyzhao Maybe you can add some detail of design. For example data flow picture.
