### ISSUE TITLE
[Bug][Docker] HTTP 502 error appears on the login dashboard when deploying InLong dashboard

### ISSUE THREAD

**Issue by boatrainlsz** [apache/inlong#4779]
### What happened

login fail
![Screenshot_select-area_20220626135911](https://user-images.githubusercontent.com/18243785/175801586-7ae00b1b-fc27-4da8-bcd8-b723ae5480ba.png)

### What you expected to happen

login success

### How to reproduce

1. sudo bin/inlong-daemon start manager
2. sudo bin/inlong-daemon start dashboard
3. open brower and visit 127.0.0.1, input  default username and password(admin, inlong), click login
4. login fail with 502 error code

### Environment

os-release:
```
PRETTY_NAME="Deepin 20.6"
NAME="Deepin"
VERSION_ID="20.6"
VERSION="20.6"
VERSION_CODENAME="apricot"
ID=Deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="https://bbs.deepin.org/"
```
docker:
```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:11 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```
I did some research, according to [this answer](https://stackoverflow.com/questions/38346847/nginx-docker-container-502-bad-gateway-response), I add the `--net host` paramter to docker command in `bin/inlong-daemon` at line 112, then problem solved. I'm wondering is there any other way to solve this?

### InLong version

1.2.0

### InLong Component

InLong Manager, InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by theseusyang** [comment]
how to add --net host paramter to docker file? @boatrainlsz

**Comment by boatrainlsz** [comment]
> how to add --net host paramter to docker file? @boatrainlsz

it's used in docker run command,  see [this]()

**Comment by dockerzhang** [comment]
<img width="844" alt="企业微信截图_94aa2c9e-9220-4985-9aa2-fd6c021fd38c" src="https://user-images.githubusercontent.com/18047329/175907489-9ea15f20-4f6a-46b3-bf61-1e4fdd6f3119.png">

**Comment by dockerzhang** [comment]
@boatrainlsz this issue will close for not reproducing, please make sure the manager address configure correctly first.
