### ISSUE TITLE
error happens when dashboard accessing to manager backend 

### ISSUE THREAD

**Issue by theseusyang** [apache/inlong#4786]
### What happened

15.bfdbbdcd.chunk.js:2 Error: http error
    at main.78043ec4.chunk.js:1:11794
（匿名） @ 15.bfdbbdcd.chunk.js:2
/#/:1 Uncaught (in promise) useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.
15.bfdbbdcd.chunk.js:2 Error: http error
    at main.78043ec4.chunk.js:1:11794
（匿名） @ 15.bfdbbdcd.chunk.js:2
/#/:1 Uncaught (in promise) useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.
15.bfdbbdcd.chunk.js:2 Error: http error
    at main.78043ec4.chunk.js:1:11794
（匿名） @ 15.bfdbbdcd.chunk.js:2
/#/:1 Uncaught (in promise) useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.
15.bfdbbdcd.chunk.js:2 Error: http error
    at main.78043ec4.chunk.js:1:11794
（匿名） @ 15.bfdbbdcd.chunk.js:2
/#/:1 Uncaught (in promise) useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.

### What you expected to happen

unknown

### How to reproduce

docker compose up -d

### InLong version

1.2.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by theseusyang** [comment]
looks like the same problem ----- https://github.com/apache/inlong/issues/4779

**Comment by dockerzhang** [comment]
@theseusyang do you use docker-compose?

**Comment by dockerzhang** [comment]
<img width="844" alt="企业微信截图_94aa2c9e-9220-4985-9aa2-fd6c021fd38c" src="https://user-images.githubusercontent.com/18047329/175907797-f95caf97-c2c9-4402-8e63-f472b1976b78.png">

```
docker-compose version 1.29.2, build 5becea4c
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by dockerzhang** [comment]
it can not reproduce, close it first.
