### ISSUE TITLE
[Bug][Manager] Caught the exception with Column 'creator' cannot be null

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4797]
### What happened

![企业微信截图_16563996978130](https://user-images.githubusercontent.com/18047329/176115087-3abcf641-2db0-474a-a9b7-db57f930d02b.png)

### What you expected to happen

manager run without exception

### How to reproduce

deploy using standalone mode
https://inlong.apache.org/zh-CN/docs/next/deployment/standalone/

### InLong version

1.2.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 948843289** [comment]
![image](https://user-images.githubusercontent.com/49986986/178642300-4b6827c3-f60b-4602-9bd2-e66a679c147a.png)
