### ISSUE TITLE
[Bug][TubeMQ] Tube-Manager startup failed

### ISSUE THREAD

**Issue by genshengyang** [apache/inlong#4805]
### What happened

inlong-tubemq-manager startup failed

2022-06-28 17:06:10.933 -ERROR  [           main] LoggingFailureAnalysisReporter : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field clusterRepository in org.apache.inlong.tubemq.manager.service.ClusterServiceImpl required a bean named 'entityManagerFactory' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean named 'entityManagerFactory' in your configuration.

### What you expected to happen

inlong-tubemq-manager  startup without errors

### How to reproduce

Download InLong Source Code from InLong Download Page and compile it or download InLong Binary file directly,then follow the manual of TubeMQ Quick start.

### Environment

Ubuntu 16.04.7 LTS (Xenial Xerus)

### InLong version

1.2.0

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EMsnap** [comment]
Will be fixed in next version
