### ISSUE TITLE
[Improve][Manager] Choose the specified connector instead of all

### ISSUE THREAD

**Issue by LvJiancheng** [apache/inlong#4812]
### Description

Choose the specified connector instead of all to avoid conficts

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by showingdata** [comment]
Where is the code
