### ISSUE TITLE
[Bug][Sort][Manager] Declare the primary key for sink table when the query contains update/delete

### ISSUE THREAD

**Issue by Greedyu** [apache/inlong#4814]
### What happened

When creating a binlog type data source, an exception occurs when initializing sort: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: please declare primary key for sink table when query contains update/delete record.
<img width="1127" alt="wecom-temp-20a4631da2c50b05cc5e6953c34d0f8c" src="https://user-images.githubusercontent.com/20356765/176403877-1ef10c3b-19f8-48bb-a469-8974fd4618ee.png">

### What you expected to happen

no error

### How to reproduce

When creating a binlog type data source, an exception occurs when initializing sort.

### Environment

centos7

### InLong version

1.2.0

### InLong Component

InLong Manager, InLong Sort

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Hi @Greedyu, could you please resolve this issue?

**Comment by Greedyu** [comment]
> 

@healchow  ok, i'll try it later
