### ISSUE TITLE
[Bug][DataProxy] Caught IllegalStateException: No tube service url specified

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4816]
### What happened

![image](https://user-images.githubusercontent.com/18047329/176581342-cb14c440-5172-4f5f-9424-759460390339.png)

### What you expected to happen

start with winning, to reminder register new cluster

### How to reproduce

start dataproxy with tube MQ

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 948843289** [comment]
I meet, how to solve it?
