### ISSUE TITLE
[Improve][Manager] Add APIs for bind and unbind cluster tag for inlong cluster

### ISSUE THREAD

**Issue by healchow** [apache/inlong#4818]
### Description

Add APIs for bind and unbind cluster tag for inlong cluster.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dadalongvs** [comment]
When the dashboard displays "cluster tags 不能为空", the following error will appear in the error.log of "inlong-manager":
![image](https://user-images.githubusercontent.com/108457248/176642795-01022527-0188-4048-be01-4b96a8029264.png)

**Comment by healchow** [comment]
@dadalongvs Thanks, we found this issue, and we will resolve it soon.
