### ISSUE TITLE
[Bug][Dashboard][Manager] Error of cluster Tags:不能为空

### ISSUE THREAD

**Issue by dadalongvs** [apache/inlong#4819]
### What happened

![QQ截图20220630163505](https://user-images.githubusercontent.com/108457248/176632015-dea124f1-fb2c-480f-bba1-37076c3e88f5.png)

### What you expected to happen

前端展示错误？

### How to reproduce

![3500ef2bf4c22f3b4bd048b89cc24e7](https://user-images.githubusercontent.com/108457248/176632175-adf4ad48-6a8c-4b56-92ff-957eef8e7299.png)

### Environment

20.04.1-Ubuntu

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Will fix in https://github.com/apache/inlong/issues/4818.
