### ISSUE TITLE
[Bug][K8s] Helm upgrade inlong failed

### ISSUE THREAD

**Issue by genshengyang** [apache/inlong#4826]
### What happened

helm upgrade inlong failed when volumes.persistence in values.yaml is set to true and volumes.persistence.storageClassName is set to "tke-cfs-storage".

kubectl create namespace inlong
helm upgrade inlong --install -n inlong ./

Error: UPGRADE FAILED: failed to create resource: PersistentVolumeClaim in version "v1" cannot be handled as a PersistentVolumeClaim: v1.PersistentVolumeClaim.Spec: v1.PersistentVolumeClaimSpec.Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|s-storage"}}}}
|..., bigger context ...|orage":"10Gi","storageClassName":"tke-cfs-storage"}}}}
|...

btw, when I changed the value of volumes.persistence.storageClassName to "tke\\\-cfs\\\-storage", the Error above disappeared,
but the new error below had occurred .

Error: UPGRADE FAILED: YAML parse error on inlong/templates/tubemq-broker-statefulset.yaml: error converting YAML to JSON: yaml: line 134: found unknown escape character

### What you expected to happen

no errors

### How to reproduce

volumes.persistence in values.yaml is set to true and volumes.persistence.storageClassName is set to "tke-cfs-storage"

kubectl create namespace inlong
helm upgrade inlong --install -n inlong ./

### Environment

kubectl version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GoVersion:"go1.18.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.4

Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### InLong version

1.2.0

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lucaspeng12138** [comment]
hello @genshengyang , could you please change docker/kubernetes/templates/mysql-pvc.yaml, to make storageClassName located before accessModes, then  try again?
<img width="583" alt="image" src="https://user-images.githubusercontent.com/100204617/176859555-8d436066-58c4-4ca2-ba15-a91c85b3e2be.png">

**Comment by genshengyang** [comment]
@lucaspeng12138 the Error above disappear, but the new error has occurred.
![image](https://user-images.githubusercontent.com/108330042/176866415-3351435f-bed9-4de2-95dc-ebc6b1097ebf.png)
the mysql pod is always Pending

**Comment by genshengyang** [comment]
@lucaspeng12138 the Error above disappear, but the new error has occurred.
![image](https://user-images.githubusercontent.com/108330042/176866415-3351435f-bed9-4de2-95dc-ebc6b1097ebf.png)
the mysql pod is always Pending

**Comment by lucaspeng12138** [comment]
@genshengyang and describe PersistentVolumeClaim inlong-mysql-data too, thx

**Comment by genshengyang** [comment]
@lucaspeng12138 
kubectl describe pod inlong-mysql-0

Error from server (Forbidden): pods "inlong-mysql-0" is forbidden: User "u-cgshvjautw" cannot get resource "pods" in API group "" in the namespace "default"

kubectl describe PersistentVolumeClaim inlong-mysql-data

Error from server (Forbidden): persistentvolumeclaims "inlong-mysql-data" is forbidden: User "u-cgshvjautw" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "default"

**Comment by lucaspeng12138** [comment]
@genshengyang I think this means user "u-cgshvjautw" have no right to access namespace "default". Could you check the rights?

**Comment by genshengyang** [comment]
@lucaspeng12138 thx, it mentions lack of resources, I will try later

**Comment by lucaspeng12138** [comment]
@genshengyang OK. I will submit a pr to fix mysql-pvc.yaml. Please notice me if there is any progress. Thanks a lot.

**Comment by lucaspeng12138** [comment]
@genshengyang I think mysql-pvc is running normally. Is there a PersistentVolume for PersistentVolumeClaim? If exist, may be there are some thing wrong with config. Please use kubectl get pv show access right.

**Comment by genshengyang** [comment]
@lucaspeng12138 
When I deploy inlong with PVC for the first time, the inlong-mysql pod works well. 
But when I uninstall the inlong, all PVC are reserved except PVC: inlong-mysql-data . 
When I deploy inlong with PVC again, mysql pod is pending and it mentions that  " running "VolumeBinding" filter plugin for pod "inlong-mysql-0": pod has unbound immediate PersistentVolumeClaims ".
I have to execute "kubectl delete pvc -n inlong --all" to avoid the error above，but data in  PVC: inlong-mysql-data will lose.
