### ISSUE TITLE
[Bug][Manager] After deleting the data_proxy cluster config, the data_proxy node under it was not deleted

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#4834]
### What happened

After deleting the data_proxy cluster config ，the data_proxy node  config under it was not deleted in the same time. When I append a data_proxy cluster with the same name, the previous data_proxy node config is still there.

### What you expected to happen

delete the data proxy node in the same time

### How to reproduce

delete the data proxy cluster and reconfigure with the same name

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
Please assign this issue to me, thx.
