### ISSUE TITLE
[Improve][Manager] Add RPC URL for TubeMQ cluster

### ISSUE THREAD

**Issue by healchow** [apache/inlong#4843]
### Description

Add RPC URL for TubeMQ cluster.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GanfengTan** [comment]
3qs
