### ISSUE TITLE
[Bug][Manager] Fail to list full inlong stream

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#4864]
### What happened

An error occurred when getting data streams of the inlongGroup, and no data streams were shown

![get_data_streams_err](https://user-images.githubusercontent.com/67505181/177148566-459bb68e-b836-44e4-a748-f35947e4bc14.png)

### What you expected to happen

list datastreams correctly

### How to reproduce

get data streams detail of a inlong group

### InLong version

master

### InLong Component

InLong Manager, InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by https://github.com/apache/inlong/issues/4857.
