### ISSUE TITLE
[TubeMQ] No error report for incorrect topic subscription

### ISSUE THREAD

**Issue by GanfengTan** [apache/inlong#4883]
### What happened

TubeMQ Client configuration is error.

topic list
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/17596132/177463204-e77367ae-385a-4576-8908-25092476ef7d.png">

config information
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/17596132/177463479-92e3c673-f92f-4d89-a10f-bd94c36c273f.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/17596132/177463539-45105eb3-535a-4070-b15c-9d7db732e6ca.png">

### What you expected to happen

Feedback error messages and exit the process.

### How to reproduce

reference--> What happened

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@GanfengTan, I got it, thanks!

**Comment by gosonzhang** [comment]
@GanfengTan, I have fixed this bug, if there is any problem, please @ me
