### ISSUE TITLE
[Bug]ead timed out

### ISSUE THREAD

**Issue by dadalongvs** [apache/inlong#4907]
### What happened

(1)inlong-manager/logs/error.log
(2)inlong-agent/logs/error.log
(3)inlong-dataproxy/logs/error.log:
![image](https://user-images.githubusercontent.com/108457248/177719093-2eac9cc4-fe9d-466e-ad98-49801926a070.png)
![image](https://user-images.githubusercontent.com/108457248/177719194-fb69a4c1-a554-45f5-aecb-41c20edeea1f.png)
![image](https://user-images.githubusercontent.com/108457248/177719282-06e3d5b9-140d-43f0-82ac-8bd234d15c2f.png)

### What you expected to happen

No error is reported, data can be imported into hive locally

### How to reproduce

When my approval is over, I view the data grouping, I can't refresh or refresh, I can't see the grouping anymore
![image](https://user-images.githubusercontent.com/108457248/177719494-08d349dc-18b8-4296-b112-cc80c5ccb719.png)

### Environment

20.04.1-Ubuntu

### InLong version

master

### InLong Component

InLong Manager, InLong Agent, InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@dadalongvs there is an OOM  exception, please fix it first. as for the time out, please the network is working.
