### ISSUE TITLE
[Feature][Manager] Supplement or modify the inlong group api in the manager client

### ISSUE THREAD

**Issue by haifxu** [apache/inlong#4926]
### Description

Supplement or modify the inlong group api in the manager client.

### Use case

Supplement or modify the inlong group api in the manager client.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haibo-duan** [comment]
I want to take over it.
