### ISSUE TITLE
[Bug][Manager] Failed to create Hive Metastore client

### ISSUE THREAD

**Issue by dadalongvs** [apache/inlong#4948]
### What happened

inlong-manager/logs/error.log：
![image](https://user-images.githubusercontent.com/108457248/178131279-38d09238-c847-40c3-86b9-70184f900b62.png)

![image](https://user-images.githubusercontent.com/108457248/178131286-206f060b-458f-462b-aebf-e615a49cc775.png)

### What you expected to happen

After the approval is over, the data flow column on the dashboard shows that the configuration failed, and an error is reported in inlong-manager/logs/error.log.
But when I use the deployed flink to test hive alone, the import query data is normal

### How to reproduce

Start, end of approval

### Environment

centos7

### InLong version

master

### InLong Component

InLong Manager, InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GanfengTan** [comment]
@dadalongvs  Thank you for using. Please add the configuration information of the task.

**Comment by dadalongvs** [comment]
@@dadalongvs This is the relevant configuration information
![image](https://user-images.githubusercontent.com/108457248/178219249-053e853f-36c1-4e1a-9045-4ad7abef00f2.png)
![image](https://user-images.githubusercontent.com/108457248/178219302-4f9acb0b-975b-490d-95ff-9474ebe72cca.png)
![image](https://user-images.githubusercontent.com/108457248/178219369-9f23db77-5e8c-4e98-90b1-e1b1ccccfaf7.png)
![image](https://user-images.githubusercontent.com/108457248/178219415-22bb67a8-fc00-4609-9245-863b16b5c50f.png)

**Comment by dadalongvs** [comment]
@[GanfengTan](https://github.com/GanfengTan)This is the relevant configuration information
![5](https://user-images.githubusercontent.com/108457248/178391565-937c1e1c-f593-43c9-9c5e-cdee4634dcfc.png)
![image](https://user-images.githubusercontent.com/108457248/178391836-378f2da3-a420-4622-a64b-d541f125b9f1.png)
![image](https://user-images.githubusercontent.com/108457248/178391890-20b10331-6c33-42fc-bd0c-04347aa20222.png)
![image](https://user-images.githubusercontent.com/108457248/178391924-aac9ed69-f53a-4e44-9b24-1c8b55c78b6a.png)
![image](https://user-images.githubusercontent.com/108457248/178391970-01b27520-8a73-420f-932f-caeb62fde5ae.png)

**Comment by dadalongvs** [comment]
> 



> @dadalongvs Thank you for using. Please add the configuration information of the task.

**Comment by GanfengTan** [comment]
@dadalongvs 1. Please put hive-site.xml to Manager config directory, then restart Manager service.
2. Update config information.
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/17596132/178403216-21f290d5-74ba-40cb-88cc-36b085d699ad.png">

**Comment by dadalongvs** [comment]
@[GanfengTan](https://github.com/GanfengTan)I have modified the configuration, but still have this error:
![image](https://user-images.githubusercontent.com/108457248/178423527-831e4306-13ce-422f-9c92-eac1ac374418.png)
![image](https://user-images.githubusercontent.com/108457248/178423636-8c81ec84-8c5d-45fc-9778-e9a40c01f0fd.png)
![image](https://user-images.githubusercontent.com/108457248/178423679-81b3c448-aed1-43fb-8887-76e2d440ef2d.png)
![image](https://user-images.githubusercontent.com/108457248/178423977-c37c594e-ab43-44ac-9a52-20d866445a5a.png)

**Comment by dadalongvs** [comment]
@[GanfengTan](https://github.com/GanfengTan) The next error was generated by changing the latest source code, but it didn't. Is there a requirement for the hive version now? This is the error reported in "inlong-manager/logs/error.log" when I approve it.
![image](https://user-images.githubusercontent.com/108457248/178425437-373aa9a9-5e4d-48a5-98cd-6ed8a23c1d66.png)

**Comment by dadalongvs** [comment]
@GanfengTan The version of hadoop is 2.7.6；he version of  hive is 2.3.3；the version of  flink is 1.13.5; he version of  mysql is 8.0.29；he version of  inlong is master.


| |
15996229218
|
|
***@***.***
|
On 7/11/2022 ***@***.***> wrote：

@dadalongvs Thank you for using. Please add the configuration information of the task.

**Comment by dadalongvs** [comment]
@GanfengTan The version of hadoop is 2.7.6；he version of  hive is 2.3.3；the version of  flink is 1.13.5; he version of  mysql is 8.0.29；he version of  inlong is master. 
|
***@***.***
|

**Comment by dadalongvs** [comment]
This is the source data file I want to export
