### ISSUE TITLE
[Bug][Manger] Unable to save the change when updating the chargers of cluster tag

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#4951]
### What happened

Unable to save the change when updating the chargers of cluster tag
![update tag](https://user-images.githubusercontent.com/67505181/178185448-a4a763c9-a14f-4979-be3c-76721d3d0efa.png)

### What you expected to happen

save rightly

### How to reproduce

update chargers of cluster tag

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woofyzhao** [comment]
The problem is manager only deals with the situation where tag name is changed. Tag property changes like chargers should also be properly dealt with.
