### ISSUE TITLE
[Improve][Manager] Add physical delete api for groupId

### ISSUE THREAD

**Issue by kipshi** [apache/inlong#4952]
### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woofyzhao** [comment]
The deletion operation has been implemented as a timer task in the other pr.

**Comment by healchow** [comment]
See #6151.
