### ISSUE TITLE
[Bug][Manager] Fail to update user info

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#4956]
### What happened

when updating the user info, such as role or valid duration，the error occurs: "password cannot be blank".
![update_user_info](https://user-images.githubusercontent.com/67505181/178219963-59356aeb-e448-482e-b1c9-6ae71ea65888.png)
![update_user_info_log](https://user-images.githubusercontent.com/67505181/178220164-cb55c116-84db-4bb9-911f-861e2dfc1375.png)

### What you expected to happen

update rightly

### How to reproduce

update the user info

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@woofyzhao PTAL, thanks.

**Comment by woofyzhao** [comment]
This depends on the refinement of user interaction desgin. Holding.

**Comment by woofyzhao** [comment]
This issue is already fixed by refactoring the user admin UI
