### ISSUE TITLE
[Umbrella] Add Grafana Metrics Dashboard

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4957]
### Describe the proposal

Agent/DataProxy/TubeMQ exposed all metrics using Prometheus framework, we need add Grafana Metrics Dashboard for them.

### Task list

Add Grafana Metrics Dasboard

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DD152** [comment]
I would like to do this.

**Comment by DD152** [comment]
# Motivation
Exposed metrics need to be showed in dashboard.

# Changes
Add Grafana Agent/DataProxy/TubeMQ Metrics Dasboard

# Design
Use Prometheus&Grafana to expose all metrics which are described in [Agent](https://inlong.apache.org/docs/modules/agent/metrics/)/[TubeMQ ](https://inlong.apache.org/docs/modules/tubemq/tubemq_metrics)/[DataProxy](https://inlong.apache.org/docs/modules/dataproxy/overview)

**Comment by dockerzhang** [comment]
@DD152 we do not need the exposed metrics shown in the dashboard module, just show in grafana page.
I think we only need the grafana template files for InLong.

**Comment by Keylchen** [comment]
I would like to continue to finish this issue.
