### ISSUE TITLE
[Feature][Sort] Sort Standalone support parse InLongMsg

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4964]
### Description

Sort Standalone can not parse the InLongMsg directly, it's better to add it for consumption from TubeMQ or Pulsar.

[Parse InLongMsg](https://inlong.apache.org/docs/next/development/inlong_msg)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vernedeng** [comment]
I will get it done, assign it to me plz

**Comment by vernedeng** [comment]
This issue has been fixed in #5808
