### ISSUE TITLE
[Umbrella][Sort] Support Batch Processing based on Flink

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4966]
### Describe the proposal

Support Batch Processing based on Flink

### Task list

Support Batch Processing based on Flink

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wilbur-jiang** [comment]
Hi @dockerzhang.  I'm interested in this issue, can you assign it to me ?

**Comment by ifndef-SleePy** [comment]
Hi @dockerzhang, I'm following Flink batch processing recently. If nobody is working on this, I'd like to take it.

**Comment by dockerzhang** [comment]
duplicated with https://github.com/apache/inlong/issues/9779, close it.
