### ISSUE TITLE
[Umbrella][Manager] Supplement the Managerctl Commands Tools

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4973]
### Description

the Managerctl Commands Tools Code:
https://github.com/apache/inlong/tree/master/inlong-manager/manager-client-tools

### Sub Tasks

- [x] #5036 
- [x] #5037
- [ ] #5038
- [x] #5039

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lujunhao957** [comment]
I want to do this task

**Comment by lujunhao957** [comment]
<h2>Motivation</h2>

The Managerctl Commands Tools does not support cluster and label management.
The Managerctl Commands Tools does not support SQL.

<h2>Changes</h2>

Support cluster and label management.
Support SQL.

<h2>Design</h2>

Support cluster and label management by interface InlongGroup.
Support SQL by Flink

**Comment by dockerzhang** [comment]
@lujunhao957 LGTM
