### ISSUE TITLE
[Feature][Manager] Support Kafka

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4976]
### Description

Manage Kafka like Pulsar/TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jun0315** [comment]
@dockerzhang Hi, I want to do this task.

**Comment by jun0315** [comment]
# Motivation

Manage module supports Apache Kafka. Apache Kafka is an open-source distributed event streaming platform . We should support Apache Kafka in manage module.

# Design

The design will follow following the document  Manager Plugin

The main modules of Kafka include topic and partition.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/44310040/182873098-c16b61a9-e532-4d3c-b6f3-66fe3bec9ed1.png">

The mapping relationship between inlong and Kafka is: Kafka's topic is group+stream, and the specific rule is: `topic=group_ with_ stream`, where `with` is the separator. The rules can be configured and perceived by users.

# Modification

Creating new file called kafka `inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group`, Adding new classes into the file:

```InlongKafkaInfo.java```

```InlongKafkaDTO.java```

```InlongKafkaRequest.java```

Creating new file called kafka `inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue`, Adding new classes into the file:

```KafkaOperator.java```

```KafkaResourceOperator.java```

```KafkaUtils.java```

# Manager plugin

Follow the document Manager Plugin.
