### ISSUE TITLE
[Feature][Dashboard] Extract / Load Node Management

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4982]
### Description

the information for Extract / Load Node is reusable for all data streams, we can add a page to manage all Extract / Load Node, like register Node, modify Node and remove Node.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leezng** [comment]
This has been published
