### ISSUE TITLE
[Feature][Agent] Support CloudEvents Source

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#4987]
### Description

CloudEvents is a specification for describing event data in common formats to provide interoperability across services, platforms and systems.

https://github.com/cloudevents/spec

### Use case

Kafka Example:
https://github.com/cloudevents/sdk-java/tree/master/examples/kafka

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by iamsee123** [comment]
Motivation
---
Add the collecting CloudEvents data function to agent module and provide the necessary management ability for manager module.

Changes
---
+ An agent module plugin with Reader and Source added
Design
---
__This PR following the document [Agent Plugin](https://inlong.apache.org/zh-CN/docs/design_and_concept/how_to_write_plugin_agent)__
1. read CloudEvents data in reader
2. create CloudEvents reader and add it to source
3. add Enum type in manager class

Implementation
---
+ Add the ability of collecting data from CloudEvents
  + CloudEventsReader: read data from CloudEvents by Debezium 
  + CloudEventsSource: implement split method
+ Add the management ability for manager module
  + add type in TaskTypeEnum
+ Add Unit test for CloudEventsReader
  + CloudEventsReaderTest: test CloudEventsReader's functional integrity
