### ISSUE TITLE
[Bug][Manager] class org.datanucles.api.jdo.JDOPersistenceManagerFactory was not found

### ISSUE THREAD

**Issue by dadalongvs** [apache/inlong#5005]
### What happened

![image](https://user-images.githubusercontent.com/108457248/178430774-c8361265-e90b-4636-8127-c45b4b9bdc5b.png)

### What you expected to happen

no error

### How to reproduce

@[GanfengTan](https://github.com/GanfengTan) The next error was generated by changing the latest source code, but it didn't. Is there a requirement for the hive version now? This is the error reported in "inlong-manager/logs/error.log" when I approve it.

### Environment

centos7

### InLong version

master

### InLong Component

InLong Manager, InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
This bug seems already fixed by another pr, close it.
