### ISSUE TITLE
[Improve] Fix the code scanning alerts exposed by CodeQL

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#5014]
### Description

Fix the code scanning alerts exposed by CodeQL.

you can find all alerts in the next link:
https://github.com/apache/inlong/security/code-scanning

### InLong Component

Other for the not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huyuanfeng2018** [comment]
https://github.com/apache/inlong/security/code-scanning This link cannot be opened ，plz check

**Comment by dockerzhang** [comment]
maybe the limits of authority, I post all winnings to you.

1
```
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/admin/AdminHttpSource.java:269
```
![image](https://user-images.githubusercontent.com/18047329/178670515-c13be8ee-2c44-467c-8b2c-6e6770c68f21.png)


2
```
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/admin/AdminHttpSource.java:262
```
![image](https://user-images.githubusercontent.com/18047329/178670648-bba8dc9f-ca0b-4e09-a0ff-45b4a33b3794.png)

3
```
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/admin/AdminHttpSource.java:246
```
![image](https://user-images.githubusercontent.com/18047329/178670742-5ecaee56-a07f-45f6-91a1-19d365bfb8be.png)

4
```
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/admin/AdminHttpSource.java:239
```
![image](https://user-images.githubusercontent.com/18047329/178670827-79eec847-31e2-4027-b6f6-4927d3ae2d12.png)

5
```
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/admin/AbstractAdminEventHandler.java:47
```
![image](https://user-images.githubusercontent.com/18047329/178670954-2f8c7208-9c04-40fa-b989-4a29490756d4.png)

6
```
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/MasterStatusCheckFilter.java:68
```
![image](https://user-images.githubusercontent.com/18047329/178671029-61bc4f9f-1e3b-4caa-90a5-6a8b3dab4092.png)

7
```
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/AbstractWebHandler.java:77
```
![image](https://user-images.githubusercontent.com/18047329/178671100-83c2ba32-d756-4bd4-a220-84e2dab03ede.png)

8
```
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/AbstractWebHandler.java:77
```
![image](https://user-images.githubusercontent.com/18047329/178671319-dc4e61ff-5ce0-4484-8a40-76faa7823e49.png)

9
```
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/MessageFilter.java:111
```
![image](https://user-images.githubusercontent.com/18047329/178671371-ca46b256-5eb9-40d7-af0f-f0842f0ddde7.png)

**Comment by huyuanfeng2018** [comment]
hi, @dockerzhang, Please assign to me.

**Comment by dockerzhang** [comment]
@huyuanfeng2018 This issue has been assigned to you, please fix it when you have time for it.

**Comment by dockerzhang** [comment]
@huyuanfeng2018 do you still work on this issue?

**Comment by jun0315** [comment]
Hi, I want to do it :D

**Comment by dockerzhang** [comment]
@huyuanfeng2018  this issue concerns a lot, so reassigned to @jun0315 , thanks

**Comment by huyuanfeng2018** [comment]
> @huyuanfeng2018 this issue concerns a lot, so reassigned to @jun0315 , thanks

ok, I happened to refer to the pr of the big guy to learn
