### ISSUE TITLE
[Bug] org.apache.inlong.tubemq.corebase.protobuf this package is not found

### ISSUE THREAD

**Issue by flgaofei** [apache/inlong#5027]
### What happened

org.apache.inlong.tubemq.corebase.protobuf this package is not found

### What you expected to happen

org.apache.inlong.tubemq.corebase.protobuf this package is not found

### How to reproduce

org.apache.inlong.tubemq.corebase.protobuf this package is not found

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@flgaofei, you need to install pb first, our protocol is in pb format, and a pb environment is required when compiling the source code
