### ISSUE TITLE
[Feature][Manager] Support query resource execution log for managerctl

### ISSUE THREAD

**Issue by haifxu** [apache/inlong#5039]
### Description

Support query resource execution log.

### Use case

Support query resource execution log.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yizhou-Yang** [comment]
I will work on this issue, including any follow-ups and revisions in the future.
