### ISSUE TITLE
[Feature][Sort] Add Apache Doris extract node for Sort

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#5040]
### Description

you can refer to:
https://inlong.apache.org/docs/next/design_and_concept/how_to_extend_data_node_for_sort#extend-a-new-extract-node

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by duoduo5566** [comment]
Hi, @dockerzhang ,can you assigin https://github.com/apache/inlong/issues/5040 to me? thanks

**Comment by dockerzhang** [comment]
@duoduo5566 thanks.

**Comment by duoduo5566** [comment]
@dockerzhang  Sorry, I clicked the unassign me button by mistake, please assign me again

**Comment by dockerzhang** [comment]
@duoduo5566 done

**Comment by duoduo5566** [comment]
Hi，@dockerzhang ! I plan to introduce the flink doris connector implementation of the doris community, which has been compiled locally and integrated into inlong. However, the doris community currently does not support version 2.11 for flink 1.13. Do we have relevant public maven repositories to upload flink-doris-connector-1.13.5_2.11 for everyone to use?

**Comment by dockerzhang** [comment]
@duoduo5566 all connectors in InLong will publish to central maven repositories, and I think everyone can access it directly.
