### ISSUE TITLE
[Feature][Sort] Add Apache Doris load node for Sort

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#5041]
### Description

you can refer to:
https://inlong.apache.org/docs/next/design_and_concept/how_to_extend_data_node_for_sort#extend-a-new-load-node

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by duoduo5566** [comment]
Hi, @dockerzhang ,can you assigin https://github.com/apache/inlong/issues/5041 to me? thanks

**Comment by dockerzhang** [comment]
@duoduo5566 done, thanks.

**Comment by dockerzhang** [comment]
@duoduo5566 do you still work on this issue?

**Comment by duoduo5566** [comment]
> @duoduo5566 do you still work on this issue?

@dockerzhang Yes, I have developed it. There is still a problem of lack of source code dependencies generated by thrift during packaging (because the flink connctor source code of the doris community is used), and I am still solving this problem
