### ISSUE TITLE
[Feature][Agent] Support collect data from MongoDB

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#5045]
### Description

you can refer to:
https://inlong.apache.org/docs/next/design_and_concept/how_to_write_plugin_agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
I want to take over this issue  @dockerzhang

**Comment by dockerzhang** [comment]
@seedscoder done, thanks.

**Comment by dockerzhang** [comment]
@seedscoder do you still work on this issue?

**Comment by seedscoder** [comment]
in progress @dockerzhang

**Comment by seedscoder** [comment]
It has been basically completed, and PR will be submitted by the end of this week at the latest

**Comment by dockerzhang** [comment]
@seedscoder do you still work on this issue?

**Comment by iamsee123** [comment]
If you haven't started yet, I want to try this
