### ISSUE TITLE
[Feature][Agent] Support collect data from PostgreSQL

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#5046]
### Description

you can refer to:
https://inlong.apache.org/docs/next/design_and_concept/how_to_write_plugin_agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by iamsee123** [comment]
Motivation
---
Add the collecting postgreSQL data function to agent module and provide the necessary management ability for manager module.

Changes
---
+ An agent module plugin with Reader and Source added
+ A manager plugin with extention of ExtractNode and LoadNode added

Design
---
__This PR following the document [Agent Plugin](https://inlong.apache.org/zh-CN/docs/design_and_concept/how_to_write_plugin_agent) and [Manager Plugin](https://inlong.apache.org/zh-CN/docs/design_and_concept/how_to_extend_data_node_for_manager)__
1. read wal log in reader by Debezium
2. create postgreSQL wal log reader and add it to source
3. add Enum type in manager class

Implementation
---
+ PostgreSQLLogReader: read data from wal log by Debezium 
+ PostgreSQLLogSource:implement split method
+ WalLogSnapShot: store some info during reading
+ add type in TaskTypeEnum,SourceType

**Comment by EMsnap** [comment]
Thanks for contribution, the implementation looks fine.
But for manager, it use tasktype for different  tasks, not loadNode. LoadNode is used for sort module actually.

**Comment by EMsnap** [comment]
For manager -> agent, pls see AgentServiceImpl getTaskResult

**Comment by iamsee123** [comment]
OK, Thank you. I will see that.
