### ISSUE TITLE
[Feature][Agent] Support collect data from SQLServer

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#5047]
### Description

you can refer to:
https://inlong.apache.org/docs/next/design_and_concept/how_to_write_plugin_agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haibo-duan** [comment]
I want to try it.

**Comment by dockerzhang** [comment]
@haibo-duan assigined to you, thanks.
