### ISSUE TITLE
[Feature][Manager] Improve user management

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#5049]
### Describe the proposal

complete user management for InLong

### Task list

- support adding users using API / SDK / Dashboard
- support modifying users' password API / SDK / Dashboard

- [x] #3680

### InLong Component

InLong Manager, InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
I'm interested in this issue

**Comment by haifxu** [comment]
@dockerzhang can you assign this to me ? I will try to do it.
