### ISSUE TITLE
[Bug][Agent] The whitelist function is abnormal

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#5050]
### What happened

After configuring the db.table whitelist, agent still filtered out the related data

### What you expected to happen

Agent should not drop whitelist data

### How to reproduce

Config whitelist

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EMsnap** [comment]
The whitelist should be a comma-separated list of regular expressions that match the fully-qualified names of tables to be monitored. Fully-qualified names for tables are of the form <databaseName>.<tableName> or <databaseName>.<schemaName>.<tableName>.
