### ISSUE TITLE
[Bug][Agent] Agent can not import old job after reboot

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#5054]
### What happened

Agent can not import old job after reboot

### What you expected to happen

Old job should run properly

### How to reproduce

reboot agent

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pocozh** [comment]
done
