### ISSUE TITLE
[Improve][Sort] KafkaExtractNode support more StartupMode

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/inlong#5074]
### Description

Written variously: I think KafkaExtractNode should support more KafkaScanStartupMode. Currently, only two types of KafkaExtractNode are supported, including EARLIEST_OFFSET and LATEST_OFFSET, But in many cases topicPartitionOffset is specified, and this parameter is already reserved in KafkaSource,I'd like to contribute this code if I can

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EMsnap** [comment]
Yeah sure, thanks for participating, note that now SPECIFIC_OFFSETS is currently support by KafkaDynamicTableFactory. Please be aware of that the specificStartupOffsets should also be passed to the factory when doing so

**Comment by huyuanfeng2018** [comment]
I want to do this  @dockerzhang

> Yeah sure, thanks for participation, note that now SPECIFIC_OFFSETS is currently support by KafkaDynamicTableFactory. Please be aware of that the specificStartupOffsets should also be passed to the factory when doing so

Ok, I'll take care of that
