### ISSUE TITLE
[Feature][Manager] Support create Greenplum databases and tables

### ISSUE THREAD

**Issue by healchow** [apache/inlong#5084]
### Description

To support the creation of Greenplum databases and tables, you can refer to the class `HiveResourceOperator`.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
Can you assign this issue to me?

**Comment by healchow** [comment]
> Can you assign this issue to me?

OK, done.
