### ISSUE TITLE
[Feature][Manager] Support create Oracle databases and tables 

### ISSUE THREAD

**Issue by healchow** [apache/inlong#5086]
### Description

To support the creation of Oracle databases and tables, you can refer to the class `HiveResourceOperator`.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haibo-duan** [comment]
pls assign it to me.
