### ISSUE TITLE
[Improve][CI] Use maven parallel build feature to improve project workflow build speed

### ISSUE THREAD

**Issue by leosanqing** [apache/inlong#5098]
### Description

We can use the parallel build feature of maven to reduce workflow runtime
I tested locally using 6 threads and the compilation went from over twenty minutes for serial to less than 8 minutes,
300% faster

This article is for reference：https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@leosanqing do you prepare to add PR for this issue?

**Comment by leosanqing** [comment]
> @leosanqing do you prepare to add PR for this issue?
I'll try to do it
