### ISSUE TITLE
http error

### ISSUE THREAD

**Issue by 948843289** [apache/inlong#5108]
### What happened

use docker-compose up -d，success，but http error in using inlong.don't work
![cc1bf7bd450938a48dc9aefe37d143b](https://user-images.githubusercontent.com/49986986/179650951-f85797ca-a533-457c-be8e-e78d18ab1a11.jpg)

### What you expected to happen

Normal use

### How to reproduce

cd docker/docker-compose
docker-compose up -d
using http://localhost

### Environment

CentOS 7
Docker version 20.10.17, build 100c701

### InLong version

1.2.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@948843289 please try again using the latest image, which corresponds to the master branch code. if there still is an error, please check the manager log for the detail.
