### ISSUE TITLE
[Feature][Dashboard] Add buttons to modify password and display sercetkey

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#5109]
### Description

At present, the user management interface does not have an interface for modifying passwords and viewing sercetkey. I hope to add these two functions
### Use case

We can modify the password and view the user sercetkey through the user management interface
Add password modification in the editing interface
<img width="525" alt="WeChatWorkScreenshot_e3a13b01-d5c7-4966-ae51-66acae725ab3" src="https://user-images.githubusercontent.com/76141879/182066478-b000a333-b696-4f4b-8c5d-96d1efc0eeb9.png">

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Already supported in #5235.
