### ISSUE TITLE
[Feature][Dashboard] Add approver management

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#5111]
### Description

Add approver management, which can support the operation of viewing and modifying the approval responsible person

### Use case

<img width="1048" alt="企业微信截图_3d66ef3a-50be-4c17-a609-82c585f7dabc" src="https://user-images.githubusercontent.com/76141879/179657368-a73e9df5-3efc-48c0-9b0e-7e8e73f73380.png">
<img width="855" alt="企业微信截图_fbabf31a-4ac3-44cb-881a-62a5f5fdcaf1" src="https://user-images.githubusercontent.com/76141879/179658448-be764008-2ff9-47f3-a747-8d9212202257.png">

Add approver management

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Already supported in #5351.
