### ISSUE TITLE
[Bug]Error executing SQL query "select "DB_ID" from "DBS"".    Table/View 'DBS' does not exist. 

### ISSUE THREAD

**Issue by z1076398926** [apache/inlong#5113]
### What happened

在使用Docker方式部署InLong，首先发现Docker中没有inlong-sort-connectors，创建数据接入时候manager容器报错：找不到/opt/inlong-sort路径，下载inlong二进制包，仅将inlong-sort复制到manager容器的/opt/目录下，然后又报错，找不到/opt/inlong-sort/connectors目录，又单独下载connectors复制到了manager容器，完整目录/opt/inlong-sort/connectors；

然后重新创建数据接入，之前的报错没有了，出现了新的报错，报错如下：
![image](https://user-images.githubusercontent.com/35166159/179687041-c226d753-fcce-422b-8e7b-93570421f5b3.png)
![image](https://user-images.githubusercontent.com/35166159/179687084-88b2bfd9-c8ce-4a90-b601-cad5c792d62d.png)
![image](https://user-images.githubusercontent.com/35166159/179687137-fbce790d-f951-4624-a7c9-63219d2c9c52.png)
![image](https://user-images.githubusercontent.com/35166159/179687172-c299e7d0-e7c8-4f56-9227-160e4a054828.png)
![image](https://user-images.githubusercontent.com/35166159/179687220-97e49f4f-0c9a-4512-a90c-a794bcdbf805.png)
![image](https://user-images.githubusercontent.com/35166159/179687246-c04551db-93a8-4193-a768-42f37c583f82.png)
![image](https://user-images.githubusercontent.com/35166159/179687289-305830ca-9e8d-4880-98db-d24ad089914c.png)
![image](https://user-images.githubusercontent.com/35166159/179687326-ef5ddc49-1c3c-4282-a10e-10929ff1ffa2.png)
![image](https://user-images.githubusercontent.com/35166159/179687358-e97f924c-a6da-4500-a21e-59f1ba9ec9b6.png)
![image](https://user-images.githubusercontent.com/35166159/179687409-a8840948-a757-4932-b971-be0496ab2562.png)

首先我看到的是：Error executing SQL query "select "DB_ID" from "DBS"".    Table/View 'DBS' does not exist.  
我从MySQL、Hive中都没有看到这张DBS在哪里。

我的配置：
![image](https://user-images.githubusercontent.com/35166159/179684677-3c14977a-b4b6-4d72-8789-ae38716d463a.png)

![image](https://user-images.githubusercontent.com/35166159/179684757-8a07d114-63db-48e0-8895-9ae24d6a4a58.png)
![image](https://user-images.githubusercontent.com/35166159/179684785-c11278d7-baee-4434-979d-d2db44ec5c83.png)

![image](https://user-images.githubusercontent.com/35166159/179684849-0b27bf73-9ba7-46dc-baa0-c9f52c0fc099.png)
![image](https://user-images.githubusercontent.com/35166159/179684917-1b3004fc-85b6-4d5a-b3a7-69ea4043342e.png)

我的Hive是用docker启动的，连接都没问题，也可以看到库和表都被创建了出来，hdfs的路径如下：

![image](https://user-images.githubusercontent.com/35166159/179685105-91888244-d804-46b2-a6db-c6f017b2174a.png)
![image](https://user-images.githubusercontent.com/35166159/179685179-de8e0824-3323-4079-ae72-8628c0dffd52.png)

### What you expected to happen

首先按照官网文档上的Docker安装方式做完之后，并没有提到需要单独下载inlong-sort-connectors（或者说单独下载并复制到容器的方式是错误的，那怎么做才是正确的？）或者说docker部署时候怎么装inlong-sort-connectors；
然后，上面提到的报错如果是表或者视图，应该自动被创建？（或者我使用的方式有问题）

期望获得帮助并解决此问题，流程是按照官方文档上的操作的（尽管官方文档上的图片是比较旧的版本，和现在1.2.0版本根本对不上）

### How to reproduce

使用一个干净的环境，并安装Docker，使用Docker部署Hive（用InLong官网提到的docker部署Hive的链接去启动），然后使用Docker部署InLong（根据官方文档上操作），根据文档上的流程创建数据接入提交审核，审核通过后，可在manager容器的日志里发现报错

### Environment

docker方式启动

### InLong version

1.2.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by z1076398926** [comment]
还有个问题，我在数据分组那里，选择执行日志，然后对失败的步骤点击执行，就会报错
![image](https://user-images.githubusercontent.com/35166159/179691486-c4d3401d-a095-4d52-92bc-637f95432120.png)
![image](https://user-images.githubusercontent.com/35166159/179691568-0f97ea2f-920c-4e51-9deb-297c2fb4c182.png)


查看manager容器日志，得到以下信息：
![image](https://user-images.githubusercontent.com/35166159/179691686-14887c36-5eda-4988-b493-0953e21ebe2a.png)
![image](https://user-images.githubusercontent.com/35166159/179691741-f10ee134-5c9e-4fe9-ad76-048d03082f14.png)

**Comment by dockerzhang** [comment]
> 还有个问题，我在数据分组那里，选择执行日志，然后对失败的步骤点击执行，就会报错 ![image](https://user-images.githubusercontent.com/35166159/179691486-c4d3401d-a095-4d52-92bc-637f95432120.png) ![image](https://user-images.githubusercontent.com/35166159/179691568-0f97ea2f-920c-4e51-9deb-297c2fb4c182.png)
> 
> 查看manager容器日志，得到以下信息： ![image](https://user-images.githubusercontent.com/35166159/179691686-14887c36-5eda-4988-b493-0953e21ebe2a.png) ![image](https://user-images.githubusercontent.com/35166159/179691741-f10ee134-5c9e-4fe9-ad76-048d03082f14.png)

hi, @z1076398926  this bug has been fixed, please use the latest image, which builds from the master branch.

**Comment by z1076398926** [comment]
> > 一个，我在数据分组然后对那里的问题，选择执行日志，点击执行日志，报错![图片](https://user-images.githubusercontent.com/35166159/179691486-c4d3401d-a095-4d52-92bc-637f95432120.png) ![图片](https://user-images.githubusercontent.com/35166159/179691568-0f97ea2f-920c-4e51-9deb-297c2fb4c182.png)
> > 查看经理记录，得到以下信息：![图片](https://user-images.githubusercontent.com/35166159/179691686-14887c36-5eda-4988-b493-0953e21ebe2a.png) ![图片](https://user-images.githubusercontent.com/35166159/179691741-f10ee134-5c9e-4fe9-ad76-048d03082f14.png)
> 
> 你好，@z1076398926 此错误已修复，请使用从 master 分支构建的最新图像。

好的，谢谢~我一开始提交的那个问题，是我哪个步骤出了错？已经排查很久了，目前还没找到问题

**Comment by dockerzhang** [comment]
@z1076398926 
after https://github.com/apache/inlong/pull/5125 merged, you do not need to copy sort dist and connectors to containers.

**Comment by dockerzhang** [comment]
As for the hive exception, we find the same issue, and another contributor will fix it later.
![image](https://user-images.githubusercontent.com/18047329/179716238-4c77382f-29d3-4f92-a562-24ae34bc8522.png)

**Comment by z1076398926** [comment]
好的~谢谢

**Comment by z1076398926** [comment]
> As for the hive exception, we find the same issue, and another contributor will fix it later. ![image](https://user-images.githubusercontent.com/18047329/179716238-4c77382f-29d3-4f92-a562-24ae34bc8522.png)

好的，谢谢

**Comment by dockerzhang** [comment]
@z1076398926  after https://github.com/apache/inlong/pull/5128 merged, you can try if there still is the hive exception

**Comment by z1076398926** [comment]
> @z1076398926 after #5128 merged, you can try if there still is the hive exception

谢谢，但我现在暂时没法测试，因为用了Master之后，出现了新的问题，我已经开了一个新的Issue，并且您已经在那个Issue中回复。

**Comment by z1076398926** [comment]
> @z1076398926 after #5128 merged, you can try if there still is the hive exception

谢谢，但我现在暂时没法测试，因为用了Master之后，出现了新的问题，我已经开了一个新的Issue，并且您已经在那个Issue中回复。

![image](https://user-images.githubusercontent.com/35166159/179735113-9d9e9d7c-aa8a-4b16-9974-ff9f6bc101dc.png)
