### ISSUE TITLE
[Bug][Dashboard] Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'remark')

### ISSUE THREAD

**Issue by z1076398926** [apache/inlong#5121]
### What happened

从master分支拉取代码，使用master分支的docker-compose.yml启动，然后根据官方文档操作，创建了dataproxy集群和pulsar集群，然后创建数据接入，创建完成后，提交。
在审核界面，点通过审核没有反应，manager容器也没有看到打印日志（没收到请求），浏览器使用F12查看到前端的console有报错。
![image](https://user-images.githubusercontent.com/35166159/179705002-c093bd40-d998-46a1-b41f-42c8bd598ff0.png)

### What you expected to happen

整个操作是根据官方文档来的（尽管新版的界面和官方文档上的图片已经不一样了），我是先在集群管理处的标签管理创建了标签，再创建了集群，然后创建数据接入，再提交审核。出现这个错误的原因未知......

### How to reproduce

使用Master分支，用Master中的docker-compose.yml启动，Hive同样使用docker（官方文档提供的Hive链接）

### Environment

Ubuntu16.04
Docker version 20.10.6

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by z1076398926** [comment]
点驳回也没反应

**Comment by xunfeng1980** [comment]
+1

**Comment by xunfeng1980** [comment]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/8380489/179893060-ab9c899c-9e9f-4fae-9e49-08fb4c3bf9c3.png">

**Comment by dockerzhang** [comment]
@xunfeng1980 @z1076398926 after https://github.com/apache/inlong/pull/5143 merged, please pull the latest image and try again.

**Comment by z1076398926** [comment]
> @xunfeng1980 @z1076398926 after #5143 merged, please pull the latest image and try again.

谢谢
