### ISSUE TITLE
[Bug]Create Data Group fail

### ISSUE THREAD

**Issue by xingzhoutan** [apache/inlong#5129]
### What happened

![image](https://user-images.githubusercontent.com/21697654/179726432-a4b78806-72d6-415d-9198-f64239e80edf.png)
![image](https://user-images.githubusercontent.com/21697654/179726609-51cd4479-4ee6-4cc8-9248-fe46f16414f7.png)

### What you expected to happen

![image](https://user-images.githubusercontent.com/21697654/179726686-51a647e3-650f-451f-88cf-707ed2d6aa40.png)

### How to reproduce

Follow the above operation

### Environment

Kubernetes 1.10+
Helm 3.0+

### InLong version

1.2.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@xingzhoutan please use the master branch code and try again, thanks.

**Comment by dockerzhang** [comment]
the image with the latest tag is the related to the master branch.
