### ISSUE TITLE
[Bug] 入库 Hive 示例中自主推送按钮在 1.2.0 版本中不见了

### ISSUE THREAD

**Issue by xunfeng1980** [apache/inlong#5135]
### What happened

[Bug] 入库 Hive 示例中自主推送按钮在 1.2.0 版本中不见了，现在只有文件和 BinLog 接入
![image](https://user-images.githubusercontent.com/8380489/179879295-6c0c7528-40b8-467d-b4ea-ffba2d7ae5e0.png)

### What you expected to happen

可以支持使用 Http API 接入数据

### How to reproduce

按照 https://inlong.apache.org/zh-CN/docs/deployment/docker 安装后，即可复现

### InLong version

1.2.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Hello, Auto push data can be used in any situation.
If no data source is added here, it can be regarded as an autonomous push method.

BTW, in order to facilitate the understanding of community developers at home and abroad, please submit PR in English, thank you.
