### ISSUE TITLE
[Bug][Manager] Fail to execute Group-InitSort

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#5144]
### What happened

Fail to Group-InitSort
![fail_init_sort](https://user-images.githubusercontent.com/67505181/179948691-b2d794db-f962-4351-bc14-dc5762118dcf.png)

### What you expected to happen

Execute init-sort config successfully

### How to reproduce

Create a group and approve it.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GanfengTan** [comment]
I am willing to submit a PR
