### ISSUE TITLE
[Bug][DataProxy] Dataproxy can not send data to pulsar as topic NotFoundException

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#5163]
### What happened

Dataproxy can not send data to pulsar:
error info:
![send_pulsar_error](https://user-images.githubusercontent.com/67505181/180201176-c6eca51d-4941-4727-a525-da8178a25818.png)

### What you expected to happen

Send data to pulsar gracefully, and can decide if using batch type or not by configuration.

### How to reproduce

Using binlog source to collect data

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by woofyzhao** [comment]
Looking into this.
