### ISSUE TITLE
[Bug][Manager] Cluster tags are not separated by commas when querying clusters

### ISSUE THREAD

**Issue by healchow** [apache/inlong#5166]
### Description

In `InlongClusterServiceImpl`, clusters tags are not separated by commas when querying clusters.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I want to fix this issue.
