### ISSUE TITLE
[Improve][Manager] There is so much Warning info when compiling the Manager module

### ISSUE THREAD

**Issue by healchow** [apache/inlong#5178]
### Description

There is so much Warning info when compiling the Manager module.

![image](https://user-images.githubusercontent.com/31994335/180353591-f41fffb2-840e-46f5-aab8-6d798c4812df.png)

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
search `Builder.Default`  in https://github.com/apache/inlong/runs/7461166731?check_suite_focus=true can see the complete log.

**Comment by liangyepianzhou** [comment]
@dockerzhang This is a good idea! I would like to do this.

**Comment by dockerzhang** [comment]
@liangyepianzhou thanks, it was assigned to you.
