### ISSUE TITLE
[Bug][Manager] Create group workflow fail

### ISSUE THREAD

**Issue by woofyzhao** [apache/inlong#5188]
### What happened

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/941634/180637138-45b14c4d-f7f5-4441-9e67-a979a3eb4f5c.png">

### What you expected to happen

Not fail

### How to reproduce

Create any group

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
I will deal with this problem.
