### ISSUE TITLE
[Bug][Manager] Create cluster tag failed, cancel apply failed

### ISSUE THREAD

**Issue by 948843289** [apache/inlong#5244]
### What happened

Using Bare Metal deployment(inlong-dashboard use docker), in the open web interface, cannot create a new label, pass and reject do not work, and the system management interface has been waiting

<img width="893" alt="微信截图_20220728103008" src="https://user-images.githubusercontent.com/49986986/181407396-8641a21b-d35f-4f44-a7c7-cb9244ad008f.png">
<img width="992" alt="微信截图_20220727093841" src="https://user-images.githubusercontent.com/49986986/181407447-52f15bd8-ad22-4f7c-baa8-7e45fc96bb22.png">
<img width="836" alt="微信截图_20220728102125" src="https://user-images.githubusercontent.com/49986986/181407511-e1e30047-4e5b-42ce-a977-8a2cdcaef301.png">
<img width="966" alt="微信截图_20220728101103" src="https://user-images.githubusercontent.com/49986986/181407565-bad846b2-0788-4c16-bbe9-ea5de918d88d.png">

### What you expected to happen

Normal use

### How to reproduce

Follow the Bare Metal deployment documentation step by step

### Environment

CentOS 7
Docker version 19.03.13

### InLong version

1.2.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Is this the code from the latest master branch?

Have you re-executed the apache_inlong_manager.sql file?

**Comment by 948843289** [comment]
I pulled the latest image and re-executed the sql file, but the error still occurred, and then I checked the logs of the components. Is it caused by these reasons? But my configuration is the same as the documentation
audit:
<img width="789" alt="audit" src="https://user-images.githubusercontent.com/49986986/181435445-c634526a-bef1-43bf-88b8-17d499214be0.png">
dataproxy:
<img width="824" alt="dataproxy" src="https://user-images.githubusercontent.com/49986986/181435527-253a6811-66c9-49d6-bc68-906d40edf31d.png">
agent:
<img width="818" alt="agent" src="https://user-images.githubusercontent.com/49986986/181435607-faa018a9-87f1-4760-b7f8-b4d3f68d755a.png">

**Comment by healchow** [comment]
Those errors have not occurred in the master branch, please pull the latest codes to test again, thanks.

**Comment by 948843289** [comment]
ok



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 1, 2022 17:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/inlong] [Bug][Manager] Create cluster tag failed, cancelapply failed (Issue #5244)




 
Those errors have not occurred in the master branch, please pull the latest codes to test again, thanks.
