### ISSUE TITLE
[TubeMQ] An error when deploying tubemq-manager according to the documentation on the official website

### ISSUE THREAD

**Issue by 948843289** [apache/inlong#5282]
### What happened

Deploying tubemq-manager according to the documentation on the official website will encounter the following problems. After adding jboss-logging-3.4.2.Final.jar and antlr-complete-3.5.2.jar to the lib, the log will not report an error
![image](https://user-images.githubusercontent.com/49986986/181738098-de65f035-4cb4-4eef-922f-782dca611df5.png)
![image](https://user-images.githubusercontent.com/49986986/181739431-f0d096bd-6767-4d5f-a79e-b45d92cba915.png)

### What you expected to happen

none

### How to reproduce

Deploy tubemq-manager according to the documentation on the official website

### Environment

CetOS 7
hibernate-core-5.6.9.Final
hibernate-commons-annotations-5.1.2.Final

### InLong version

1.2.0

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@bluewang, can you take a look at this issue?
