### ISSUE TITLE
[Bug][TubeMQ] When a non-master node is configured in the first position of the address, the service cannot be started

### ISSUE THREAD

**Issue by mrcat2018** [apache/inlong#5314]
### What happened

When a non-master node is configured in the first position of the address, the service cannot be started.

### What you expected to happen

The master-slave order of the client relationship is not required when configuring addresses.

### How to reproduce

When a non-master node is configured in the first position of the address, the service cannot be started. 

The client program panics when the server performs a master-slave switch

### Environment

centos 7

github.com/apache/inlong/inlong-tubemq/tubemq-client-twins/tubemq-client-go v0.0.0-20220731125344-27b1a02fc0db

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@mrcat2018, thanks!

**Comment by TszKitLo40** [comment]
Can you provide the trace of panic?
