### ISSUE TITLE
[Bug][Dashboard] An error occurred while creating the  dataproxy cluster

### ISSUE THREAD

**Issue by GanfengTan** [apache/inlong#5319]
### What happened

![image](https://user-images.githubusercontent.com/17596132/182143589-20b81e84-5719-48d3-afe6-4c0101b0f435.png)

### What you expected to happen

Create the dataproxy cluster success.

### How to reproduce

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/17596132/182143890-7d0c9c8c-1474-49e0-a6cd-09983755bf0d.png">

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by #5310
