### ISSUE TITLE
[Bug][Manager] MySQL binlog datasource job can not be add successfully in tke env

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#5366]
### What happened

the binlog datasource job has been in the 'ToBeAdd' state

### What you expected to happen

binlog datasource run successfully

### How to reproduce

config a binlog datasource job

### Environment

tke

### InLong version

master

### InLong Component

InLong Manager, InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
it does not happen again, close it.
