### ISSUE TITLE
[Bug][Dashboard] No restrictions are added to the input of port numbers, such as dataproxy node

### ISSUE THREAD

**Issue by bruceneenhl** [apache/inlong#5406]
### What happened

with configuring the ip:port of dataproxy or other module, there are no format restrictions on ip or port.
please check this kind of problem, not only dataproxy node.

### What you expected to happen

add input restrictions.

### How to reproduce

input ip port

### InLong version

master

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leezng** [comment]
@bluewang PTAL.
