### ISSUE TITLE
[inlong-sdk] NullPointerException while call getManagerIpList

### ISSUE THREAD

**Issue by gosonzhang** [apache/inlong#5408]
### What happened

When running InLong-SDK, the SDK obtains the Manager's IP list, it returns a null pointer error, error message:
![image](https://user-images.githubusercontent.com/14038849/183402651-831690fc-de41-4e6c-95ab-7fc79989b40e.png)

code:
![image](https://user-images.githubusercontent.com/14038849/183403008-06392b56-1e32-4b82-8655-55c37ce6acf2.png)

Is this a problem with the implementation of the SDK, or is the interface of DataProxy not consistent?

### What you expected to happen

no exception

### How to reproduce

start DataProxy SDK

### Environment

linux

### InLong version

master

### InLong Component

InLong DataProxy, InLong SDK

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
YES,return is `data`, not `resultData`

**Comment by gosonzhang** [comment]
@fuweng11, thanks, I'll fix it.
