### ISSUE TITLE
[Feature][Sort] Add metric for Hive with Flink metrics group and audit SDK

### ISSUE THREAD

**Issue by thesumery** [apache/inlong#5469]
### Description

Add metric for hive with flink metrics group and audit sdk

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
this issue has finished, close it.
