### ISSUE TITLE
对项目很感兴趣，项目1.2版本一经发布立刻就安装体验了

### ISSUE THREAD

**Issue by zhujunjieit** [apache/inlong#5473]
### What happened

项目使用docker-compose虽然正常启动起来了。但是在接入得时候一直报错，不知道怎么排查，有没有交流qq群或者微信群
![图片](https://user-images.githubusercontent.com/42972147/184051143-b5aeb76a-cf20-44f4-9f7b-232ad94b9991.png)

### What you expected to happen

项目使用docker-compose虽然正常启动起来了。但是在接入得时候一直报错，不知道怎么排查，有没有交流qq群或者微信群

### How to reproduce

项目使用docker-compose虽然正常启动起来了。但是在接入得时候一直报错，不知道怎么排查，有没有交流qq群或者微信群

### InLong version

1.2.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
Follow us on WeChat, and you can scan the QR [1].

[1] https://github.com/apache/inlong-website/blob/master/static/img/apache-inlong-wechat.jpg
