### ISSUE TITLE
[Bug][Manager] Unsupported MQ type TUBE

### ISSUE THREAD

**Issue by 948843289** [apache/inlong#5482]
### What happened

![48f59568ceb811d382928ab6c18c457](https://user-images.githubusercontent.com/49986986/184080287-7016692a-9222-43fc-b25a-6922b6cc5811.jpg)
sort don't support tubemq?

### What you expected to happen

use tubemq

### How to reproduce

Hive Example

### Environment

InLong 1.2.0

### InLong version

1.2.0

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GanfengTan** [comment]
Could you  use the master code?  It is not to support  in this release. @948843289
