### ISSUE TITLE
[Feature][Manager] Add file and auto_push extract node

### ISSUE THREAD

**Issue by emhui** [apache/inlong#5506]
### Description

[Feature][Manager]Add filesource and sdk extract node

### Use case

[Feature][Manager]Add filesource and sdk extract node

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
File source and auto push source are already supported in `StreamSourceOperator#getSourcesMap`, so close this issue.
