### ISSUE TITLE
[Feature][Manager] Mask sensitive data in logs

### ISSUE THREAD

**Issue by emhui** [apache/inlong#5507]
### Description

Mask sensitive data in logs

### Use case

Mask sensitive data in logs

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e-mhui** [comment]
I'll do this.

**Comment by healchow** [comment]
Duplicate with #5598.
