### ISSUE TITLE
[Bug][Agent] MySQL binlog reader has NPE error

### ISSUE THREAD

**Issue by iamsee123** [apache/inlong#5540]
### What happened

When MySQL binlog reader read from binlog it will report java.lang.NullPointerException.

### What you expected to happen

BinLogReader use `readerMetric` to collect infomation but without initialize the variable which cause the problem.

### How to reproduce

when collect MySQL data with binLog

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
@iamsee123 Hello, thanks for your issue.
Could you please paste all detail of the exception?
