### ISSUE TITLE
[Improve][Manager] Add manager client packages into the lib directory

### ISSUE THREAD

**Issue by healchow** [apache/inlong#5570]
### Description

Add manager client packages into the lib directory.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
Please assign this issue to me, thx.
