### ISSUE TITLE
[Feature][Sort] Add redis extract node and support temporal join

### ISSUE THREAD

**Issue by yunqingmoswu** [apache/inlong#5576]
### Description

Add redis extract node and support temporal join.

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gong** [comment]
I suggest that adding use case. For example, how to use flink sql?
