### ISSUE TITLE
[Improve][DataProxy] The in charges person and other info are not reported

### ISSUE THREAD

**Issue by healchow** [apache/inlong#5603]
### Description

The in charges person and other info are not reported when the node is automatically registered.

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Ok, let me fix it!
