### ISSUE TITLE
[Feature][Sort] Support Raw Format 

### ISSUE THREAD

**Issue by Oneal65** [apache/inlong#5713]
### Description

Support Raw Format

### Use case

according to https://nightlies.apache.org/flink/flink-docs-release-1.13/zh/docs/connectors/table/formats/raw/

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Resolved by #5702.
