### ISSUE TITLE
[Bug][Manager] Fix Binary type mapping error

### ISSUE THREAD

**Issue by e-mhui** [apache/inlong#5797]
### What happened

`Binary` mapping to `array`, `fieldinfoUtils` parse failed.

```
org.apache.flink.shaded.jackson2…com.fasterxml.jackson.databind.exc.InvalidTypeIdException:Couldnotresolvetypeid'FieldInfoUtils$$Lambda$1517/
642480380' as a subtype of org.apache.inlong.sort.formats.common.FormatInfo':known type ids = [array, binary, boolean, byte,
```

### What you expected to happen

`Binary` mapping to `Binary`, instead of `Array`.

### How to reproduce

1

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gong** [comment]
close it, pr [https://github.com/apache/inlong/pull/6079](https://github.com/apache/inlong/pull/6079) had fixed it.
