### ISSUE TITLE
[Bug][TubeMQ] Get duplicated call when calling TubeMQConsumer::Start()

### ISSUE THREAD

**Issue by chen9t** [apache/inlong#5848]
### What happened

First time we call `TubeMQConsumer::Start()`, got "timeout".
When we want to call `TubeMQConsumer::Start()` again, got "duplicated call".

### What you expected to happen

No duplicated call if first call is failed.

### How to reproduce

1. Call `TubeMQConsumer::Start()`, got "timeout";
2. Retry `TubeMQConsumer::Start()` again, got "duplicated call".

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@chen9t, thanks!

**Comment by gosonzhang** [comment]
It should be a bug in the code. When Start() exits abnormally, the status flag is not set, so the above problem occurs. The main points are as follows:
1. tubemq_client.cc:
https://github.com/apache/inlong/blob/master/inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/tubemq_client.cc#L69
![image](https://user-images.githubusercontent.com/14038849/189518107-93e3d34f-d353-4dc9-9a1e-5ac574237193.png)

2. baseconsumer.cc:
https://github.com/apache/inlong/blob/master/inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/baseconsumer.cc#L62
![image](https://user-images.githubusercontent.com/14038849/189518193-7b214b93-14f1-4dc8-bab8-530a9c9d0a24.png)

I'll fix them, thanks @chen9t
