### ISSUE TITLE
[Bug]1.2.0启动StandAlone模式时候报错

### ISSUE THREAD

**Issue by yg9538** [apache/inlong#5856]
### What happened

启动data proxy的时候会爆出一个找不到Creator的错误

### What you expected to happen

期待启动成功，实际启动出错

### How to reproduce

需要修改数据库表中的sql 中的creator为not null才能不报错启动，在源码接口中传Creator的地方为null

### InLong version

1.2.0

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Hello, @yg9538, thanks for your test and issue.
Suggested using the master branch, or the latest release (1.3.0) to test again, this error had been fixed.
