### ISSUE TITLE
[Bug][Manager] Error in /api/inlong/manager/consumption/save

### ISSUE THREAD

**Issue by yg9538** [apache/inlong#5869]
### What happened

调用/api/inlong/manager/consumption/save报错

### What you expected to happen

{"consumerGroupName":"yg9538_test","inCharges":"admin","inlongGroupId":"yg9538_test","mqType":"TUBE","topic":"yg9538_test","filterEnabled":0,"consumerGroupId":"yg9538_test","mqExtInfo":{"mqType":"TUBE"}}  中consumerGroupId字段不存在导致接口异常

### How to reproduce

需要重构接口

### InLong version

1.2.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Hello, thanks for your concern and test.
Those APIs were changed. Please use the master branch or the latest release (1.3.0) to test again.
