### ISSUE TITLE
[Improve]建议增加standalone模式启动建议

### ISSUE THREAD

**Issue by yg9538** [apache/inlong#5872]
### Description

建议在standalone启动教程里增加修改docker dashboard pod中默认api路由地址的提示

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
thanks, @yg9538 .
please add more details for your improvement suggestion.

**Comment by yg9538** [comment]
我启动standalone模式时候dashboard会爆出502错误，经过排查是因为dashboard中的nginx配置文件中default.conf指向了127.0.0.1:8083，这个地址没法走通

**Comment by dockerzhang** [comment]
@yg9538 127.0.0.1:8083 is the URL for manager, please check the manager services status, and make sure it started successfully.

**Comment by yg9538** [comment]
如果是linux启动127.0.0.1:8083为manager启动 外网访问不通，只能把localhost_ip改成外网地址，一修改后dashboard就访问不通，如果不修改127.0.0.1:8083不是访问容器内的地址么?

**Comment by dockerzhang** [comment]
please change the `local_ip=` to actual IP in `conf/inlong.conf`.
