### ISSUE TITLE
[Improve][Dashboard] Change the consume related config to adapt the Manager module

### ISSUE THREAD

**Issue by healchow** [apache/inlong#5926]
### Description

Change the consume related config to adapt the Manager module.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I want to process this issue, could someone assign it to me?

**Comment by healchow** [comment]
> I want to process this issue, could someone assign it to me?

Done.
