### ISSUE TITLE
[Improve][Manager] Optimize the usage of ObjectMapper

### ISSUE THREAD

**Issue by healchow** [apache/inlong#6068]
### Description

Optimize the usage of ObjectMapper.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ciscozhou** [comment]
I will fix this issue, please assign it to me, thanks.
