### ISSUE TITLE
[Umbrella] [Manager]  Manager support delete/update by unique key

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#6105]
### Task list

- [x] #6042
- [x] #6086
- [x] #6101
- [x] #6103

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
All sub-tasks are finished, so close it.
