### ISSUE TITLE
[Bug][Manager] Cannot find manager-web.log in docker mode

### ISSUE THREAD

**Issue by healchow** [apache/inlong#6136]
### What happened

Cannot find manager-web.log in docker mode.

![166546957960](https://user-images.githubusercontent.com/31994335/195013576-9004a0f6-c8d9-4022-ab44-5923ab64b2fe.png)

### What you expected to happen

Should see log success.

### How to reproduce

Execute the `docker logs {container_id}`.

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yurzhou** [comment]
I want to solve this problem, please assign the issue to me

**Comment by healchow** [comment]
> I want to solve this problem, please assign the issue to me

Done. Thanks for your contribution.
