### ISSUE TITLE
[Improve][Manager] Add a consumer group of TubeMQ for each sink

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#6226]
### Description

Add a consumption group for each sink

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Not needed anymore.
