### ISSUE TITLE
[Improve][Dashboard] Source data delimiter changed from ASCII to symbol

### ISSUE THREAD

**Issue by bluewang** [apache/inlong#6258]
### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Keep the usage of ASCII for data separators, the backend does the transfer operation when needed.
