### ISSUE TITLE
[Bug][TubeMQ] host is blank

### ISSUE THREAD

**Issue by FvvSuu** [apache/inlong#6421]
### What happened

Some time after the deployment runs successfully, a consumer process exception occurs: 
java.lang.IllegalArgumentException: Argument host is Blank!

### What you expected to happen

Log contents:
<img width="1420" alt="Snipaste_2022-11-07_17-08-13" src="https://user-images.githubusercontent.com/53012896/200271099-3e7b9291-da9e-41e6-9345-08410b388a2b.png">

### How to reproduce

Some time after the deployment runs successfully

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Thanks @FvvSuu, I got it

**Comment by gosonzhang** [comment]
The problem should be the following [1]. When adding or modifying the broker configuration, the complete configuration information of the broker to be modified is not obtained, resulting in the host part being empty.

I will fix it, thanks @FvvSuu 

1. https://github.com/apache/inlong/blob/master/inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DefaultMetaDataService.java#L367
![image](https://user-images.githubusercontent.com/14038849/200249281-8f52ca10-0886-4fbe-96b6-4697e59b3c49.png)
