### ISSUE TITLE
[Umbrella] Support export CLS

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#6466]
### Describe the proposal

Support export CLS https://cloud.tencent.com/product/cls
Include CLS cluster, CLS data node, CLS sink

### Task list

- [ ] #6462
- [ ] #6467
- [ ] #6468

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
there is no CLS user for InLong, all ClS PR and issues will close.
