### ISSUE TITLE
[Improve][Sort] Accurately parse the schema type and completely match the missing precision information

### ISSUE THREAD

**Issue by thesumery** [apache/inlong#6545]
### Description

Currenttly auto create table feature support extract schema from 'sqlType' field, 
```
{
  "data": [
    {
      "id": "111",
      "name": "scooter",
      "description": "Big 2-wheel scooter",
      "weight": "5.18"
    }
  ],
  "database": "inventory",
  "es": 1589373560000,
  "id": 9,
  "isDdl": false,
  "mysqlType": {
    "id": "INTEGER",
    "name": "VARCHAR(255)",
    "description": "VARCHAR(512)",
    "weight": "FLOAT"
  },
  "old": [
    {
      "weight": "5.15"
    }
  ],
  "pkNames": [
    "id"
  ],
  "sql": "",
  "sqlType": {
    "id": 4,
    "name": 12,
    "description": 12,
    "weight": 7
  },
  "table": "products",
  "ts": 1589373560798,
  "type": "UPDATE"
}
```

althouth it unified jdbc type, but it has some limit：
1. It is not directly convert, it may loss convert error
2. Jdbc type does not have accuracy information, for some data type it may loss some information.For example: decimal(15,2), varchar(3)

So i suggest to extract it from mysqlType, it can slove those problem, but it's more complex.

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by e-mhui** [comment]
It has been fixed in https://github.com/apache/inlong/pull/8342.
