### ISSUE TITLE
[Feature] Add arm64 image for inlong/tubemq-all

### ISSUE THREAD

**Issue by caozongpeng** [apache/inlong#6560]
### Describe the proposal

inlong/tubemq-all 能否提供arm64的镜像

### Task list

![image](https://user-images.githubusercontent.com/30362467/202150054-a863f575-0f81-402d-a68e-89e7410ad00c.png)

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@lucaspeng12138 PTAL, thanks.

**Comment by lucaspeng12138** [comment]
Able to do that. But we need to change base images from zookeeper 3.4  to another one, because of 3.4 doesn't support arm. @dockerzhang could we change that?

**Comment by dockerzhang** [comment]
@lucaspeng12138 i think that's ok.

**Comment by lucaspeng12138** [comment]
[自动回复]：您的邮件我已收到，我将尽快给您回复，谢谢

**Comment by dockerzhang** [comment]
@caozongpeng After https://github.com/apache/inlong/pull/7296 merged, you can try again, thank you.
