### ISSUE TITLE
[Feature]Device log collection function support，such as syslog/sftp/http source?

### ISSUE THREAD

**Issue by bitian** [apache/inlong#6576]
### Description

Today, I deployed the docker version and test，I want to collect syslog logs, device http interface data or ftp/sftp data.I don't know if it is possible to collect these data using Inlong,because the Inlong agents may not be directly installed on these devices, it needs to be collected through the protocol or flume, etc.
How can I use Inlong to collect those data,looking forward to your reply，thank you!

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@bitian, there are some ways to collect files.
1, install InLong Agent and collect the files on the device
2, InLong support report by HTTP
3, using SDK report in your application
