### ISSUE TITLE
[Bug][DataProxy] Fix can not get the local IP in the docker container 

### ISSUE THREAD

**Issue by chestnut-c** [apache/inlong#6604]
### What happened

Fix can not get the local IP in the docker container When the target IP contains 30.

### What you expected to happen

get the local IP in the docker container excluding the ip of the network segment starting with 30.

### How to reproduce

When both network card IPs of the container contain 30

### InLong version

1.4.0

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Hi @chestnut-c , Is it same with https://github.com/apache/inlong/issues/6602?

Can you provide more logs or error information?
