### ISSUE TITLE
[Improve] Add settings for agent's data report-to

### ISSUE THREAD

**Issue by gosonzhang** [apache/inlong#6607]
### Description

After the Agent collects data, it needs to report the data to the server. It is possible that the system allows the Agent to directly report the data to DataProxy, or it is possible to allow the Agent to directly report the data to MQ; when reporting to DataProxy, it is possible to choose to let the source side of DataProxy reply The response to the request may also return a response on the sink side according to the result of the request. To this end, we need to support the setting of this parameter on the Manager, the idea is as follows:
![image](https://user-images.githubusercontent.com/14038849/203490753-1d388e03-372f-4932-9d80-e6aa64c7d635.png)

This issue makes improvements in this area, this improve involves Agent, Manager, and Dashboard, which will be disassembled into 3 sub-issues for tracking:

- [x] #6610 
- [x] #6681 

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by pocozh** [comment]
https://github.com/apache/inlong/issues/6681

**Comment by pocozh** [comment]
**[Feature][Agent] Support settings for agent's data report-to** https://github.com/apache/inlong/issues/6681
