### ISSUE TITLE
[Bug][TubeMQ] The C++ client does not support filtering consume with the "-" character

### ISSUE THREAD

**Issue by FvvSuu** [apache/inlong#6638]
### What happened

The C++ client of TubeMQ does not support filtering consume with the "-" character.

### What you expected to happen

The Java client of TubeMQ does not check the "-" character and can successfully filter consumed from the server.

### How to reproduce

Configure consumer filtering with "-" characters

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@FvvSuu, thanks, the two are not consistent, I'll deal with it
