### ISSUE TITLE
[Feature][Dashboard] Add status management for group

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#6669]
### Description

Add status management for the data group in Dashboard, like start/restart/suspend.

manager API:
https://github.com/apache/inlong/blob/master/inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kinfuy** [comment]
I want to try this task. Can you assign it to me

**Comment by kinfuy** [comment]
Can you provide more descriptions for this task, and what specific needs to be done

**Comment by dockerzhang** [comment]
fixed in https://github.com/apache/inlong/pull/7177, close it.
