### ISSUE TITLE
[Feature][Manager] Add `inlongctl` status management for the group

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#6672]
### Description

Add `inlongctl` status management for the group.

manager API:
https://github.com/apache/inlong/blob/master/inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java

inlongctl(managerctl)
code: https://github.com/apache/inlong/tree/master/inlong-manager/manager-client-tools
guide: https://inlong.apache.org/zh-CN/docs/next/user_guide/command_line_tools

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seedscoder** [comment]
If others don't start, please assign it to me

**Comment by seedscoder** [comment]
The `inlongctl list group` can display the status of the group. What's special about the `inlongctl status group`  @dockerzhang

**Comment by dockerzhang** [comment]
we may need to add `inlongctl start/stop/suspend group`
