### ISSUE TITLE
[Bug][TubeMQ] After continuous consumption for a period of time, some partitions may not be able to consume

### ISSUE THREAD

**Issue by mrcat2018** [apache/inlong#6743]
### What happened

After continuous consumption for a period of time, some partitions may not be able to consume.

### What you expected to happen

The client should be able to consume the data of all partitions after the connection is established. Instead of running for a period of time, some partitions cannot be consumed.

### How to reproduce

After continuous consumption for a period of time, some partitions may not be able to consume.

### Environment

linux 

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Can someone help me, I'm not very familiar with Go, I need your help, thanks!
