### ISSUE TITLE
[Feature][Metrics][TubeMQ] Add grafana dashboard json template

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#6756]
### Description

Agent and DataProxy have added:
https://github.com/apache/inlong/tree/master/inlong-tools/grafana/dashboards

TubeMQ Metrics for Prometheus:
https://inlong.apache.org/docs/next/modules/tubemq/configure_introduction
![企业微信截图_1670225669711](https://user-images.githubusercontent.com/18047329/205792798-d13ecb3d-20dd-4e7e-baff-d9752944b855.png)

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ogkunald** [comment]
Hello,Please assign this to me

**Comment by dockerzhang** [comment]
@ogkunald thanks.

**Comment by bibhu107** [comment]
I would love to contribute in this task! If no one is working on this, can you please assign it to me

**Comment by dockerzhang** [comment]
@bibhu107 do you have a plan to work on this issue?

**Comment by bibhu107** [comment]
@dockerzhang Hello, I am occupied with few other priority tasks for now, so don't have enough bandwidth for this one.

**Comment by fancycoderzf** [comment]
I would like to work on this issue.
