### ISSUE TITLE
[Feature] Support multi addresses for ES load node

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#6838]
### Description

 Support adding multi addresses for ES load node.

- before
host: host_name
port: 9092
- after
hosts: "http://host_name:9092;http://host_name:9093"

include manager and dashboard.

https://github.com/apache/inlong/pull/6817 fixed a bug for one address.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
https://nightlies.apache.org/flink/flink-docs-release-1.13/zh/docs/connectors/table/elasticsearch/#hosts

![image](https://user-images.githubusercontent.com/18047329/206986752-2ae0a418-1896-45ae-8884-a5edee5d7261.png)

**Comment by wangpeix** [comment]
Hi, @dockerzhang ,can you assigin this issue to me? thanks
