### ISSUE TITLE
[Feature] support ddl change and auto create database/table in doris multi table load.

### ISSUE THREAD

**Issue by chyueyi** [apache/inlong#6892]
### Description

Doris has been supported light schema change since 1.2, so we can synchronize ddl change and auto create database/table in doris multi table load, just like iceberg load. 

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kuansix** [comment]
we are doing this

**Comment by kuansix** [comment]
来信已收到，谢谢！

**Comment by EMsnap** [comment]
@kuansix Thanks for your attention, this issue is closed with https://github.com/apache/inlong/pull/7764

**Comment by kuansix** [comment]
来信已收到，谢谢！
