### ISSUE TITLE
[Improve][Manager] Rename Flink Job to avoid conflicts

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#6909]
### Description

Now:
![image](https://user-images.githubusercontent.com/18047329/208013514-2831c1f2-d63d-4f18-800a-31200b01b059.png)

Todo:
job_name is `InLong-Sort-{Group ID}`

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ZuoFengZhang** [comment]
I hava finished this issue, please assign to me.
