### ISSUE TITLE
[Bug][Audit] No exceptions are printed in the log

### ISSUE THREAD

**Issue by leosanqing** [apache/inlong#6919]
### What happened

No exceptions are printed in the log. I don't know how to locate the specific cause of this error

![image](https://user-images.githubusercontent.com/20400582/208045261-03fb70a7-ccda-4d21-9903-b0012d5db2a6.png)

### What you expected to happen

![image](https://user-images.githubusercontent.com/20400582/208045770-2c7a7b33-509a-41dc-90b4-d38d2e9ae6eb.png)

### How to reproduce

For example, when creating a task, the port occupies

### Environment

MacOS 12.6 

### InLong version

master

### InLong Component

InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@leosanqing do you plan to fix this issue?
