### ISSUE TITLE
[Bug][dashboard] Configuration failure always occurs after adding data stream

### ISSUE THREAD

**Issue by linqianppb** [apache/inlong#7034]
### What happened

![image](https://user-images.githubusercontent.com/5062416/209263910-51302445-eb8e-4950-a2be-1eab4b1548ac.png)
Configuration failure always occurs after adding data stream

[QueueResourceListener] event: [COMPLETE], executed [failed], remark: [null], exception: [cannot find any cluster by tag test and type PULSAR]

### What you expected to happen

Configuration failure always occurs after adding data stream

### How to reproduce

Configuration failure always occurs after adding data stream

### Environment

docker-compose

### InLong version

1.4.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@linqianppb please make sure to create a tag and bind clusters, you can refer to:
https://inlong.apache.org/zh-CN/docs/next/deployment/docker

**Comment by dockerzhang** [comment]
@linqianppb please try the latest version, and if occurs again, please create a new issue.
