### ISSUE TITLE
[Bug][Manager] Unknown method isNoneBlank

### ISSUE THREAD

**Issue by woofyzhao** [apache/inlong#7039]
### What happened

<img width="1415" alt="企业微信截图_1fad3c41-c3f4-4f8d-bc40-ee1a2a75c67a" src="https://user-images.githubusercontent.com/941634/209291535-45af771a-fc50-4234-8231-8a03dfdb5dea.png">

### What you expected to happen

no error

### How to reproduce

run manager

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@woofyzhao, let me see it
