### ISSUE TITLE
[Bug][CI] Lint and test charts create kind cluster faild

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#7129]
### What happened

![image](https://user-images.githubusercontent.com/18047329/210326869-6c466c06-548d-4ee0-823f-10d8dc6c31d5.png)

see 
https://github.com/apache/inlong/actions/runs/3827285454/jobs/6511744539

### What you expected to happen

create kind cluster successfully.Create

### How to reproduce

see 
https://github.com/apache/inlong/actions/runs/3827285454/jobs/6511744539

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
fixed in https://github.com/apache/inlong/pull/7125

**Comment by shink** [comment]
same issue https://github.com/kubernetes-sigs/kind/issues/1437
cause of this problem: https://github.com/kubernetes-sigs/kind/issues/1437#issuecomment-602975963
