### ISSUE TITLE
[Improve][Manager] Enhance the logical processing of Open API

### ISSUE THREAD

**Issue by gosonzhang** [apache/inlong#7168]
### Description

At present, the main problems of OpenAPI are:
1. The parameter check is not strict: some key fields do not have enough judgment items, so that the existence is only checked during actual operation;

2. The log output is disordered: some places that do not need to output the log are output, resulting in the inundation of useful information;

3. There are bugs in the implementation logic: For the operation of the API, it is necessary to align and adjust item by item according to the existence and operation requirements.

This issue is a general issue, and the provided OpenAPI will be dealt with item by item. The overall logic is consistent with the above-mentioned issues:
- [x] #7169 
- [x] #7178 
- [x] #7204 
- [x] #7220
- [x] #7229 
- [x] #7261
- [x] #7278
- [x] #7280
- [x] #7284
- [x] #7300 

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
finished all sub-tasks, and close it.
