### ISSUE TITLE
[Bug][Sort] Data copy process is not used for MySQL node

### ISSUE THREAD

**Issue by linqianppb** [apache/inlong#7201]
### What happened

![image](https://user-images.githubusercontent.com/5062416/211460577-8b2cdd86-91d7-49a2-b7df-748e80cb94f1.png)

Data copy process is not used
### What you expected to happen

mysql to mysql

### How to reproduce

no

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@gong @yunqingmoswu PTAL, thanks.

**Comment by EMsnap** [comment]
@linqianppb Can you please define what daata copy process is and describe more details in your description? Since your pic shows only the checkpoint process
