### ISSUE TITLE
[Umbrella] Support sink to Redis

### ISSUE THREAD

**Issue by featzhang** [apache/inlong#7210]
### Describe the proposal

# Support sink redis

Redis: The open source, in-memory data store used by millions of developers as a database, cache, streaming engine, and message broker. 

### Task list

- [x] #7060 
- [x] #7211 
- [x] #7238 
- [x] #7240 
- [x] #7242 
- [x] #7244
- [x] #7245 
- [x] #7305 
- [x] #7306 

### InLong Component

InLong Manager, InLong Dashboard, InLong Sort, InLong Audit, Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
all sub-tasks finished, close it.
