### ISSUE TITLE
[Bug][Manager] Caught UnsupportedVersionException

### ISSUE THREAD

**Issue by GYK123123** [apache/inlong#7225]
### What happened

The topic of kafka is successfully created, but an error is displayed

### What you expected to happen

The topic of kafka is successfully created, but an error is displayed，org.apache.kafka.common.errors.UnsupportedVersionException: Topic metadata and configs in CreateTopics response not supported，maybe is result.numPartitions() == CreateTopicsResult.UNKNOWN 

### How to reproduce

The topic of kafka is successfully created, but an error is displayed，org.apache.kafka.common.errors.UnsupportedVersionException: Topic metadata and configs in CreateTopics response not supported，maybe is result.numPartitions() == CreateTopicsResult.UNKNOWN 

### Environment

docker_compose

### InLong version

1.4.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@GYK123123 please try to use the 1.5.0 branch which has lots of optimizations for Kafka, and it will release recently.
