### ISSUE TITLE
[Feature][SDK]

### ISSUE THREAD

**Issue by bigdaronlee163** [apache/inlong#7252]
### Description

I want to contribute the producer implementation code to the Go SDK, so I'd like to check to see if there are any similar contributions recently.
At present, the basic logic has been sorted out, and the rest is mainly to spend time debugging, so I plan to submit a version of the implemented code before the end of the Spring Festival.

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@bigdaronlee163, which component SDK do you want to do, DataProxy or TubeMQ?

There are existing issues for them, and you can use them when you confirm.
- DataProxy
https://github.com/apache/inlong/issues/4961

- TubeMQ
https://github.com/apache/inlong/issues/4968

**Comment by bigdaronlee163** [comment]
TubeMQ go  sdk for producing message

**Comment by dockerzhang** [comment]
@bigdaronlee163 thanks, but there is another contributor @xuehuanran doing #4968. You could choose other issues and review the PR after completion.

I will close this issue, and we can follow the forward pace in #4968.
