### ISSUE TITLE
[Bug][Manager] The test connection address is wrong, but it shows success

### ISSUE THREAD

**Issue by leosanqing** [apache/inlong#7256]
### What happened

![image](https://user-images.githubusercontent.com/20400582/212839872-34d3d7a6-e624-441e-846e-f79b4ef370a7.png)

### What you expected to happen

The test connection should check service urls

### How to reproduce

Add pulsar cluster

### InLong version

1.5.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@fuweng11 PTAL, thanks.

**Comment by fuweng11** [comment]
I will deal with this problem.
