### ISSUE TITLE
[Bug][Sort] Fix bug of dirtysink not opening for jdbc multiple sink 

### ISSUE THREAD

**Issue by Yizhou-Yang** [apache/inlong#7291]
### What happened

dirtysink not opening for jdbc multiple sink

### What you expected to happen

add dirtysink.open in the opening of the connector

### How to reproduce

bug for multiple sink dirty data

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
Fixed by #7288
