### ISSUE TITLE
[Bug][Sort] The invokeMultiple method cannot accurately detect and archive dirty data

### ISSUE THREAD

**Issue by Yizhou-Yang** [apache/inlong#7292]
### What happened

the method could not accurately detect and archive dirty data

### What you expected to happen

it should archive data properly

### How to reproduce

do a dirty data archive with those connectors

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
What bug? Please add more info for the Issue.
