### ISSUE TITLE
[Improve][Manager] Replace getRoles() with getAccountType()

### ISSUE THREAD

**Issue by gosonzhang** [apache/inlong#7300]
### Description

The parent issue: https://github.com/apache/inlong/issues/7168

In the user authorization check of the Open APIs, the getRoles() function of the UserInfo class is used, but the getAccountType() function is used in the current Manager implementation. In order to maintain the consistency of the authentication and authorization logic, the getRoles() calls are replaced with getAccountType()

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
How do we manage users of InLong? I think we need to do some research and design, and modify the code after discussion and decision.
