### ISSUE TITLE
[Improve][Sort][Manager] Support complex type field

### ISSUE THREAD

**Issue by gong** [apache/inlong#7331]
### Description

Supporting complex type field

### InLong Component

InLong Manager, InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xxhannah** [comment]
I am willing to submit a PR 🙋🏻‍♀️
