### ISSUE TITLE
[Feature][Manager] Support stream join dimension table

### ISSUE THREAD

**Issue by gong** [apache/inlong#7334]
### Description

Support stream join dimension table

### Use case

for example: I have kafka stream and dimension table(mysql or redis)
I can join kafka table and dimension table

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JJiacheng** [comment]
I am willing to submit a PR!
