### ISSUE TITLE
[Bug]datanode Hive JDBC URL cannot change

### ISSUE THREAD

**Issue by zhubangpei** [apache/inlong#7338]
### What happened

The hive jdbc url connot be changed
<img width="1540" alt="企业微信截图_adab126d-f92e-4f94-a609-e7903b91b327" src="https://user-images.githubusercontent.com/17564903/217473753-2fb64ebf-7000-473a-b859-18726d05018f.png">
2023-02-03 15:04:18 ~ 2023-02-03 15:04:18 [StreamSinkResourceListener] event: [COMPLETE], executed [failed], remark: [null], exception: [create hive table failed: hive server url should start with jdbc:hive2]

### What you expected to happen

<img width="1553" alt="企业微信截图_f2e453d8-a0ff-483c-afef-2e5529cdbb86" src="https://user-images.githubusercontent.com/17564903/217474222-35e0705e-d60a-4e00-9cbc-8d6ff66d0c02.png">
datanode is null

### How to reproduce

fix the bug

### Environment

MacBook Pro 12.2.1  
Apple M1 Pro

### InLong version

1.5.0

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhubangpei** [comment]
bug is not be solved

**Comment by bluewang** [comment]
This bug has now been fixed：https://github.com/apache/inlong/pull/7298

**Comment by dockerzhang** [comment]
> This bug has now been fixed：#7298

@zhubangpei please try again.
