### ISSUE TITLE
[Bug][Sort] When use multiple flink sink to iceberg, it happends NPE

### ISSUE THREAD

**Issue by hejiay** [apache/inlong#7344]
### What happened

Use flink sink multiple to write to iceberg, NPE appears.
![image](https://user-images.githubusercontent.com/48463767/217790403-72dc4135-aa7d-40ad-aac0-12b25ca04732.png)

### What you expected to happen

The reason is that **flinkWriteConf** has not been initialized when use flink sink multiple to write to iceberg.
![image](https://user-images.githubusercontent.com/48463767/217793461-4acf5e68-312b-4927-a82e-dbb2cb78ce58.png)
![image](https://user-images.githubusercontent.com/48463767/217791351-d72abfa2-c096-43dd-9565-68db268e4c70.png)
It can be initialized in the chainIcebergMultipleSinkOperators(), but it is used directly in the appendMultipleCommitter().
NPE will not occur when FlinkSink single table is written to iceberg, because **flinkWriteConf** will be initialized![20230209-185443](https://user-images.githubusercontent.com/48463767/217793280-a4357c99-b184-4831-a9f8-d72b6eae9f72.png)

### How to reproduce

Use FlinkSink multiple to write to iceberg

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gong** [comment]
https://github.com/apache/inlong/pull/7364 had fixed this error @hejiay

**Comment by healchow** [comment]
Fixed.
