### ISSUE TITLE
[Bug]Create hudi  sink fail

### ISSUE THREAD

**Issue by zhubangpei** [apache/inlong#7352]
### What happened

<img width="1182" alt="企业微信截图_6533fb46-c779-4677-bae0-8b12dfc54171" src="https://user-images.githubusercontent.com/17564903/218050004-2e78d7b2-aa78-42aa-97bd-8d9712c9edfd.png">

### What you expected to happen

<img width="1570" alt="企业微信截图_a5380983-b827-42b3-a236-56666c3b46ef" src="https://user-images.githubusercontent.com/17564903/218050343-8f64e9bb-0fbb-4fb6-a13c-fbea466334f2.png">

<img width="1197" alt="企业微信截图_15c719f1-7441-41d4-9b30-55a175521b3d" src="https://user-images.githubusercontent.com/17564903/218050369-27b8e11c-c875-4f73-b900-0863ffc0a280.png">

fix the bug

### How to reproduce

sink hudi

### Environment

MacBook Pro 12.2.1
Apple M1 Pro

### InLong version

1.5.0

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@featzhang PTAL

**Comment by dockerzhang** [comment]
you could add `hudi-flink1.13-bundle` jar to the lib or pick #7657 and build the latest package.
