### ISSUE TITLE
[Feature][Audit] Support using Kafka

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#7428]
### Description

The audit module only supported Pulsar and TubeMQ, and the InLong stream supported Kafka recently, 
it's better to support Kafka for audit at the same time.

### Subtasks.

- https://github.com/apache/inlong/issues/7518
- https://github.com/apache/inlong/issues/7519
- https://github.com/apache/inlong/issues/7528
- https://github.com/apache/inlong/issues/7572
- https://github.com/apache/inlong/issues/7413
- https://github.com/apache/inlong/issues/7641
- https://github.com/apache/inlong/issues/7636

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haifxu** [comment]
I can do this issue.
