### ISSUE TITLE
[Improve][DataProxy] Update the metrics log level to avoid the log file increasing quickly

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#7512]
### Description

![image](https://user-images.githubusercontent.com/18047329/222679662-96427c66-89d2-4896-90ff-1b8cb8acfc5e.png)

Update the metrics log level to avoid the log file increasing quickly.

`INFO` -> `DEBUG`

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by macroguo-ghy** [comment]
hi @dockerzhang, i'd like to solve this problem. Could you help me review this pr? [https://github.com/apache/inlong/pull/7634](url)
