### ISSUE TITLE
[Feature] Add file completion strategy in agent component

### ISSUE THREAD

**Issue by xuesongxs** [apache/inlong#7682]
### Description

Specifies what to do with the original file on the file system once it has been collected into Inlong.

Allowable Values: 
1.None:
2.Move File: Move the file to destination directory.
3.Delete File: Delete the original file on the file system.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by justinwwhuang** [comment]
we should neither change the user file nor directory,  it has beyond inlong`s responsibility(readonly).
