### ISSUE TITLE
[Feature][Tool] Support parallel compilation and packaging

### ISSUE THREAD

**Issue by featzhang** [apache/inlong#7784]
## There are two problems with the current project:
1. When using mvn -B or mvnd to compile the project, various problems will occur and the compilation will fail.
2. The CR pipeline runs too slowly

## To locate the above problem, the analysis is as follows:

1. Reasons why parallel packaging cannot be done

The `inlong-distribution` module uses assembly to compress and package the output of each module together. However, the module dependencies are not clearly specified in the pom file, causing maven to infer dependencies.

2. CR pipeline does not need to generate distribution

## Transformation method:

- [ ] #8242 
1. CR pipeline does not package Distribution
2. Clear distribution modules and all dependencies in the project

> At present, it is being transformed to support multiple versions of Sort Flink, and it is also necessary to clarify the maven coordinates of each Connector

**Comment by aloyszhang** [comment]
#11440  support parallel building
