### ISSUE TITLE
[Bug][Manager] No token field in the return result of getAllConfig

### ISSUE THREAD

**Issue by gosonzhang** [apache/inlong#7810]
### What happened

When DataProxy accesses a Pulsar cluster with authentication and authorization enabled, DataProxy will report an authorization error. Through inspection, it is found that when the Manager obtains the metadata information of the Pulsar cluster through the getConfig method, the returned result carries the token authorization access information of the Pulsar cluster, but through When the getAllConfig method obtains the metadata information of the Pulsar cluster, the token authorization access information of the Pulsar cluster is not carried

### What you expected to happen

When the Pulsar cluster metadata information is obtained through the getAllConfig method, the returned result carries the token authorization access information of the Pulsar cluster

### How to reproduce

Enable Pulsar cluster authentication authorization check, and then report data to the Pulsar cluster through DataProxy

### Environment

Linux

### InLong version

master

### InLong Component

InLong Manager, InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
I will deal with this problme. And add token information to `CacheClusterObject` and `CacheCluster`, convert the token information to json, and send it to dataproxy.

**Comment by gosonzhang** [comment]
Thanks @fuweng11
