### ISSUE TITLE
[Bug] 源数据使用pg数据库，目标数据使用pg数据库时，写入数据格式错误。

### ISSUE THREAD

**Issue by wjwjm** [apache/inlong#7821]
### What happened

按照【https://inlong.apache.org/zh-CN/docs/deployment/docker】使用docker部署inlong1.6版本。源数据使用pg数据库，目标数据使用pg数据库时，写入数据格式错误。只在第一个字段写入了{"before"nul,'ater"("id'""2"name'asd, source'":("version':"1 8.0.Final""connector :postgresgl', "name""public' "ts ms"1681183395......}{i'before"nul "after""id"""before "nul "ater'i "di: "name " "awe % "source : 'version "1 8.0.Fina'" 'connectorl"i"pos......}的内容。
![Uploading 740a2ae0e1c7e04924400206849ebab.png…]()

### What you expected to happen

flink显示的日志中，insert语句，velue内容显示的是{id:"{"before"nul,'ater"("id'""2"name'asd, source'":("version':"1 8.0.Final""connector :postgresgl', "name""public' "ts ms"1681183395......}",name:null}这种样式。

### How to reproduce

1. 按照【https://inlong.apache.org/zh-CN/docs/deployment/docker】使用docker部署inlong1.6版本。
2.pg数据库版本12。新建源数据表data_ex ,data_load, 字段为id【varchar】,name【varchar】，data_ex表按照文档要求进行了配置。
3. 新建数据组，使用消息队列pulsar，新建源数据![image](https://user-images.githubusercontent.com/79295169/231098428-10b35b62-5b82-4e81-ac92-8b58070d6b1f.png)
4. 新建目标数据：
![image](https://user-images.githubusercontent.com/79295169/231098599-2b33d1d4-76af-4f7e-9eb0-a87e623ef11b.png)
5.审批后会提示找不到【POSTGRESQL】type。
6.manager使用的数据库表，增加类型，执行以下语句，INSERT INTO `audit_base`(`name`, `type`, `is_sent`, `audit_id`)
VALUES ('audit_sort_postgres_input', 'POSTGRESQL', 0, '27'),
       ('audit_sort_postgres_output', 'POSTGRESQL', 1, '28');
7.配置成功，后续出现情况如下图所示：
![3e10aed6261203bc2530257bcb4856f](https://user-images.githubusercontent.com/79295169/231099614-68def9ee-bdfd-4a05-91bb-98af714991eb.png)
![fbecb2420d2b6f1cd59d74dbbade0cc](https://user-images.githubusercontent.com/79295169/231099640-5c828da2-fbda-427f-895a-1dc90bd16746.png)
![4ea09cf6caf8b497343d3afb82d9fa4](https://user-images.githubusercontent.com/79295169/231099726-fac31e4b-511e-4f02-9258-5eba8eda0ac4.png)
目标数据库表内容截图：
![740a2ae0e1c7e04924400206849ebab](https://user-images.githubusercontent.com/79295169/231099793-9fb86853-0813-4f92-9b72-6dec4b5d7a35.png)

### Environment

centos7.6，docker拉取的最新版。

### InLong version

1.6.0

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by haifxu** [comment]
Fixed in this PR: https://github.com/apache/inlong/pull/7935
