### ISSUE TITLE
[Feature][Manager] Support data validation when importing Excel file

### ISSUE THREAD

**Issue by featzhang** [apache/inlong#7867]
### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bibhu107** [comment]
I would love to contribute in this task! If this is not assigned to anyone, can i look into it?

**Comment by dockerzhang** [comment]
@bibhu107 Thanks, but this issue has been implemented by @featzhang. You could check other issues.
