### ISSUE TITLE
[Bug]使用python对pulsar中的数据进行自主消费时无法对消息体解码

### ISSUE THREAD

**Issue by wang273257881** [apache/inlong#7875]
### What happened

我们将数据通过inlong导入到pulsar中，之后使用python直接从pulsar中获取数据，但获取到的数据流无法使用utf-8/gbk/windows-1252等格式进行解码。

### What you expected to happen

我们了解到直接从MQ消费数据需要解析InlongMsg格式的数据，但官网仅给出了Java的解析方式，我们期望通过python对其进行解析。

### How to reproduce

直接获取pulsar中导入的数据即可，例以下为某次获取到的数据流：
b'\x0f\x01\x00\x00\x01\x87\x93G\x14\\\x00\x00\x00\x01\x00\x9adt=1681745136747&partitionKey=80ba78988f88f987b3934c36f378446d&streamId=test_stream&topic=persistent://public/test_group_0417_1/test_stream&syncSend=false\x00\x00\x006\x01;\x88\x00\x00\x00\x07id,name\x00\x00\x00\x041,qq\x00\x00\x00\x032,w\x00\x00\x00\x0533,qw.\x10\x00,,www\x00\x00\x00\x04,www\x0f\x01'

### Environment

python3.8.10
pulsar2.8.2
ubuntu

### InLong version

1.6.0

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wang273257881** [comment]
我尝试使用了pyjnius调用了官网提供的InLongMsg解析方法，但在parseDefault方法中报错：JVM exception occurred: Illegal initial capacity: -187228160 java.lang.IllegalArgumentException ['java.lang.IllegalArgumentException: Illegal initial capacity: -187228160', 'java.util.HashMap.<init>(HashMap.java:450)', 'java.util.HashMap.<init>(HashMap.java:469)', 'java.util.LinkedHashMap.<init>(LinkedHashMap.java:359)', 'org.apache.inlong.common.msg.InLongMsg.parseDefault(InLongMsg.java:652)', 'org.apache.inlong.common.msg.InLongMsg.parse(InLongMsg.java:874)', 'org.apache.inlong.common.msg.InLongMsg.makeSureParsed(InLongMsg.java:940)', 'org.apache.inlong.common.msg.InLongMsg.getAttrs(InLongMsg.java:949)', 'com.companyname.bank.App.parserInLongMsg(App.java:19)']，传入的参数即How to reproduce中的示例数据

**Comment by dockerzhang** [comment]
Hi, I'm sorry that there is no Python SDK parsing InLongMsg now. We could add this feature in the future.

**Comment by wang273257881** [comment]
Nothing much, thank you for your reply. I tried using Python to call the official website’s Java code for parsing InLongMsg and it was successful. The issue has been resolved and I will close this issue.
