### ISSUE TITLE
[bug] multiple times generating approval slips

### ISSUE THREAD

**Issue by fhj123456789** [apache/inlong#7892]
### What happened

偶然间点击快了一些发现在重复点击时
![image](https://user-images.githubusercontent.com/67697088/233605070-7907c790-1904-40ae-9f91-1286d9bebe3b.png)

会出现数据重复写入的BUG
![image](https://user-images.githubusercontent.com/67697088/233605131-c7862c13-4199-4d4a-961b-1569728d393b.png)

当然对于该项目的重点可能没影响

### What you expected to happen

虽然并发请求可能不大，但是希望在处理并发请求时能够有一些操作

### How to reproduce

1.6.0

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@fuweng11 PTAL

**Comment by fuweng11** [comment]
I will deal with this problem.

**Comment by fuweng11** [comment]
@fhj123456789 Please use English.

**Comment by fhj123456789** [comment]
> @fhj123456789 Please use English.

Thank you very much for your response. This issue occurred when I clicked to submit for approval. Firstly, the front-end component was not set to disable after clicking. After multiple clicks at the same time, the backend approval event would be written multiple times. Although this issue does not affect the use of InLong, I still hope to optimize the operation interface provided by the backend.
