### ISSUE TITLE
[Bug]1.6.0的docker部署中，数据库初始化表结构中，缺少postgresql类型

### ISSUE THREAD

**Issue by JeffWang79** [apache/inlong#7992]
### What happened

1.6.0的docker部署中，数据库初始化表结构中，缺少postgresql类型
![493c1baf7bc445474a9a097fdd2978a](https://github.com/apache/inlong/assets/90167565/62dacb3f-ec1d-40ca-ae87-0d6ea6263b64)

### What you expected to happen

数据库初始化表结构中，缺少postgresql类型
![5ee352282a2dcdebbe78fddc7eafa2b](https://github.com/apache/inlong/assets/90167565/a7f53b48-276c-4640-8963-14008fd30968)

### How to reproduce

![7ea601ee6971c11ea4820b4f9c8ba9c](https://github.com/apache/inlong/assets/90167565/81e04bde-6bbc-40a3-afdb-a553df02d622)
构建pg目标或shu'ju'jian数据源新建流时，审批后会出现此问题

### Environment

centos7.6服务器

### InLong version

1.6.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JeffWang79** [comment]
INSERT INTO `audit_base`(`name`, `type`, `is_sent`, `audit_id`)
VALUES ('audit_sort_postgres_input', 'POSTGRESQL', 0, '27'),
       ('audit_sort_postgres_output', 'POSTGRESQL', 1, '28');
使用测试中新增了两条数据。我网络问题拉取不到github的代码，不能提交pr。

**Comment by dockerzhang** [comment]
@JeffWang79 thanks. It's better to use English to describe the issue.

**Comment by haifxu** [comment]
@JeffWang79 It's fixed in this PR: https://github.com/apache/inlong/pull/8000
