### ISSUE TITLE
[Bug] Kafka connector should support group offset

### ISSUE THREAD

**Issue by EMsnap** [apache/inlong#7993]
### What happened

[Bug] Kafka connector should support group offset

### What you expected to happen

[Bug] Kafka connector should support group offset

### How to reproduce

[Bug] Kafka connector should support group offset

### InLong version

master

### InLong Component

InLong Manager, InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
fixed in https://github.com/apache/inlong/pull/7997
