### ISSUE TITLE
[Bug]dataproxy http returns suc all the time

### ISSUE THREAD

**Issue by justinwwhuang** [apache/inlong#8003]
### What happened

dataproxy http returns suc all the time，even if the groupId and streamId were incorrect

### What you expected to happen

expect dataproxy http can check wether the params are correct，and return the error msg

### How to reproduce

report http msg to dataproxy http with incorrect groupId and streamId

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Thanks @justinwwhuang
