### ISSUE TITLE
[Improve][Dashboard] Add default icon for different data nodes

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8008]
### Description

Add default icon for different data nodes, making it easier identifiable.

![image](https://github.com/apache/inlong/assets/18047329/656dce27-fccb-4955-bb4a-3dc3eb047d82)

![image](https://github.com/apache/inlong/assets/18047329/d064a45d-78b5-41d8-ac71-8692cac9cc66)

For example:
mysql ->
![image](https://github.com/apache/inlong/assets/18047329/bf05dd00-9d05-4629-b7cd-f7f7bc8255c6)

### InLong Component

InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yuvraj-Singh-Wahla** [comment]
I would like to work on this issue.

**Comment by dadaobajiao** [comment]
I would like to work on this issue.

**Comment by dockerzhang** [comment]
@Yuvraj-Singh-Wahla thanks, have you made any progress recently？ we plan to release the new version in later weeks.

**Comment by dockerzhang** [comment]
@dadaobajiao thanks.

**Comment by dockerzhang** [comment]
@dadaobajiao do you have a plan to work on this issue?

**Comment by LeeBingler** [comment]
Can i try ?

**Comment by durand90** [comment]
Hi,

If this is still available, I would like to work on it.

**Comment by dockerzhang** [comment]
@durand90 Thanks. Assigned to you.
