### ISSUE TITLE
[Improve] Update the CI workflow to avoid the network being unreachable

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8042]
### Description

![82b724a28a47b1296e55ae3d1e5a9e0](https://github.com/apache/inlong/assets/18047329/d25e39a2-4a9f-46de-a853-84b3198cafbb)

Fefer to https://github.com/apache/pulsar/pull/20198/files, add `-Daether.connector.http.reuseConnections=false -Daether.connector.requestTimeout=60000` could solve the problem.

- Disable Maven HTTP connection pooling also for Aether
- Set request timeout to 60000ms also for aether

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hnrainll** [comment]
Hello, I have submitted a PR.
