### ISSUE TITLE
[Bug][Manager] Unsupported FieldType is reported when the source and sink are both PostgreSQL

### ISSUE THREAD

**Issue by JeffWang79** [apache/inlong#8091]
### What happened

字段存在 int4类型，映射字段INTEGER，源和目标都是postgres,报错Unsupported FieldType : INTEGER，1.7和1.6都有这问题。
![5025942cb231469028d63d2ee998112](https://github.com/apache/inlong/assets/90167565/b57e6928-abc5-46a9-952d-2294e5fec67c)
![70e6752bd6f92abe7a56c60d11f2231](https://github.com/apache/inlong/assets/90167565/cb82352a-d4a3-4ac9-815c-4b1e0e9a5755)

### What you expected to happen

![image](https://github.com/apache/inlong/assets/90167565/e0a6188b-8ff8-4493-878d-32358538c8d5)

### How to reproduce

![image](https://github.com/apache/inlong/assets/90167565/542484c3-de5b-475a-9a1a-c4af1883667f)

### Environment

centos7.6，docker一键部署

### InLong version

1.7.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chestnut-c** [comment]
Ok thanks for the feedback, we will improve the data type mapping for various data sources

**Comment by dockerzhang** [comment]
@JeffWang79, please use English to describe this issue. Thanks.

**Comment by dockerzhang** [comment]
fixed by https://github.com/apache/inlong/pull/8223, close it.
