### ISSUE TITLE
[Improve][TubeMQ] Improve the precision of tube consumer id

### ISSUE THREAD

**Issue by Reo-LEI** [apache/inlong#8321]
### Description

https://github.com/apache/inlong/blob/017e4006d72ab26372826078e8f516c8758228f8/inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java#L589-L594

In the k8s environment with hostNetwork enabled, there will be multiple pods running on the same host, and the ip of these pods will be the same.

Assume these pods are taskmanager as a flink cluster and the flink cluster is exclusive to a job. At this time, taskmanagers running on the same host will most likely have the same pid. And because each taskmanager has the same parallelism, so the number of tube consumers is also the same, and the self-incrementing id will also have the same probability at this time.

When the parallelism of the tube source is relatively high, it is easy for multiple consumers to be created in parallel at the same time. At this time, the timestamp is likely to have the same value, which makes the tube consumer id duplicate. In the end, the tube server has been unable to wait for enough consumers so that the flink job cannot consume any data.

Therefore, it is hoped that the accuracy of the consumer id can be improved to avoid the above situation.

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Reo-LEI** [comment]
@gosonzhang Please take a look of this issue, thx~

**Comment by gosonzhang** [comment]
@Reo-LEI, thanks for your report

**Comment by gosonzhang** [comment]
Maybe replacing milliseconds with nanoseconds and adding random numbers would be a better way

**Comment by gosonzhang** [comment]
I'll push a PR to fix this, thanks @Reo-LEI
