### ISSUE TITLE
[Improve][Manager] Support previewing data of Kafka

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#8360]
### Description

Support previewing data of Kafka.

The purpose of data preview is to observe the result of sending data in time after the user sends data, and take it out from kafka to verify the correctness of the data.

Please refer to the following pull requests:

- Pulsar
#8301

- Tube
#8357

- Dashboard
#8299
![image](https://github.com/apache/inlong/assets/88174078/6201768b-d62a-4d07-b62f-fecdde3e6642)

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hnrainll** [comment]
hi,@fuweng11 I am willing to submit a PR!
