### ISSUE TITLE
[Bug][Manager] Group restart fail

### ISSUE THREAD

**Issue by xuesongxs** [apache/inlong#8361]
### What happened

![image](https://github.com/apache/inlong/assets/54351417/8c43f0f5-3fb3-4a59-80b7-a9e661aa671e)
![image](https://github.com/apache/inlong/assets/54351417/e7531f0d-4033-45a0-bd15-331734cb8d9a)
![image](https://github.com/apache/inlong/assets/54351417/ac20dafd-8c2e-4261-846c-bda929ff3de5)
![image](https://github.com/apache/inlong/assets/54351417/a13e01c4-538e-4c7b-87fa-c6ae3bb5bc04)
![image](https://github.com/apache/inlong/assets/76141879/9dadf598-3a50-407b-9657-5694cfdb0636)
![image](https://github.com/apache/inlong/assets/76141879/a58490aa-fae2-44e3-8467-9e6ecaae1e86)Stop the group first, then restart, and report a startup error.

### What you expected to happen

Group  startup successfull.

### How to reproduce

Stop the group first, then restart, and report a startup error.

### InLong version

1.7.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
After https://github.com/apache/inlong/pull/8401 merge, you could try again.
