### ISSUE TITLE
[Bug][Manager] Group restart fail and the industry display configuration failed

### ISSUE THREAD

**Issue by xuesongxs** [apache/inlong#8362]
### What happened

group source is auto-push.

![1f5bcaa3d28220b52384e0641b1f350](https://github.com/apache/inlong/assets/54351417/f3f12fbe-6776-4c83-83af-dfc833ca3fca)
![acf4fe6c9f5e059c82da397f64da90c](https://github.com/apache/inlong/assets/54351417/1083942a-111d-40c9-8fa4-f489c300d176)
![1664960dd25a487ce4492c58074fdd8](https://github.com/apache/inlong/assets/54351417/ac70cd28-efec-41ca-9459-b0062aacee36)
![05a4035ac5bf04c1911ba06fe1e5f47](https://github.com/apache/inlong/assets/54351417/452d6c3c-1b13-459b-a61f-776144c4601b)
![d6e3649422ab4adebe3787e14b43289](https://github.com/apache/inlong/assets/54351417/975e49d0-599b-4106-b54e-56e36641f7fa)

### What you expected to happen

Group restart fail and the industry display configuration failed. 
When stopping the group, the manager tried many times before it ended, and the group's status changed to configuration failure. At this time, the job on Flink was still running, and there was no restart button on the page.

### How to reproduce

When stopping the group, the manager tried many times before it ended, and the group's status changed to configuration failure. At this time, the job on Flink was still running, and there was no restart button on the page.

### InLong version

1.7.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
The `AUTO_PUSH` streamSource was mistakenly modified to 202 status due to modifying dataNode , fixed by the above PR：
https://github.com/apache/inlong/issues/8400

**Comment by fuweng11** [comment]
The AUTO_PUSH streamSource was mistakenly modified to 202 status due to modifying dataNode , fixed by the above PR：
https://github.com/apache/inlong/issues/8400
