### ISSUE TITLE
[Bug][DataProxy] Sink does not have audit data

### ISSUE THREAD

**Issue by lvanneo** [apache/inlong#8368]
### What happened

Source has audit data, sink does not have audit data.

### What you expected to happen

Sink should also have audit data.

### How to reproduce

You can observe this by looking at the audit data.

### InLong version

1.7.0

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@lvanneo, thanks, I got it
