### ISSUE TITLE
[Feature][Manager] Manager client tools support multiple tenant

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#8374]
### Description

1. List resources by different tenant
2. List tenant info

The main idea of achive this ability is to add "tenant:{YOUR_TARGET_TEANT}" into the http request header.
The server will insert the tenant into the context and do all request under the tenant you specified.

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
Here can refer to https://github.com/apache/inlong/pull/8428.
