### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:eclipse (default-cli) on project sort-connector-hive: Execution default-cli of goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:eclipse failed: For artifact {org.apache.hive:hive-exec:null:jar}: The version cannot be empty. -> [Help 1][Bug]

### ISSUE THREAD

**Issue by lujiefsi** [apache/inlong#8402]
### What happened

when i run 
```
 mvn eclipse:eclipse
```

i meet :
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:eclipse (default-cli) on project sort-connector-hive: Execution default-cli of goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:eclipse failed: For artifact {org.apache.hive:hive-exec:null:jar}: The version cannot be empty. -> [Help 1]
```

I have to add "\<version>${hive3x.version}</version\>"  after https://github.com/apache/inlong/blob/5f544aaf2752cc7065fa69c529bfff2f5791ba20/inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hive/pom.xml#L44 

to fix the error.

### What you expected to happen

no errrors.

### How to reproduce

mvn eclipse:eclipse

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gong** [comment]
I suggest you can use IDEA.

**Comment by dockerzhang** [comment]
Please try `mvn clean package -DskipTests`.
