### ISSUE TITLE
[Bug][dataproxy-sdk-cpp] Data sending fails but dataproxy-sdk-cpp returns success

### ISSUE THREAD

**Issue by gosonzhang** [apache/inlong#8409]
### What happened

When reporting data to DataProxy through dataproxy-sdk-cpp, after DataProxy returns an error, dataproxy-sdk-cpp still counts successfully

### What you expected to happen

counts failure

### How to reproduce

sdk send a message,  dataproxy  force return a error, check result

### Environment

Linux

### InLong version

master

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by doleyzi** [comment]
I'll handle it

**Comment by gosonzhang** [comment]
Thanks
