### ISSUE TITLE
[Improve] Improve the TaskTypeEnum.java file in Inlong-common-enums

### ISSUE THREAD

**Issue by nikam14** [apache/inlong#8433]
### Description

In the getTaskType() method we are using switch case to get the task , we can improve it using Hashmap to store the Task and then can get Task Type from HashMap, which is more efficient.

Screenshot

![after](https://github.com/apache/inlong/assets/55378196/5e85131a-41bf-43b6-a3af-a31197f6a19a)

Open for Suggestions.

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@nikam14 do you have a plan to fix this issue?

**Comment by nikam14** [comment]
I have shared my idea in the issue, converting the enums to Hashmap, Using the Hashmap to store and using hashmap methods instead of switch statement. Can refer the screenshot in the issue.

**Comment by dockerzhang** [comment]
@nikam14 you could create a PR and commit it, and more contributors could review and confirm it.

**Comment by LiJie20190102** [comment]
I want to do this.

**Comment by LiJie20190102** [comment]
@nikam14 , I have submitted a PR, can you help me review it
