### ISSUE TITLE
[Feature] [Sort] Add JDBC connector on Flink 1.15

### ISSUE THREAD

**Issue by Yizhou-Yang** [apache/inlong#8464]
### Description

Add JDBC connector on Flink 1.15

some extra notes: Oceanus has adopted Flink v1.16 to all its connectors, if the branches were to be in sync, I might want to upgrade all connectors to be compatible with flink 1.16

Will do for 1.15 for this one for now, hopefully the difference between 1.15 and 1.16 isnt too large
(but flink 1.16 made huge changes to jdbc...)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoYou201** [comment]
I wish to finish it~
