### ISSUE TITLE
[Improve] Modify nodeIp in dataproxy message to clientIp

### ISSUE THREAD

**Issue by fuweng11** [apache/inlong#8506]
### Description

Modify nodeIp in dataproxy message to clientIp.
Currently, dataproxy uses `nodeIp` to record the reporting address of received messages.
However, this information is difficult to understand and requires modifying the field name to clientIp.
`nodeIp` only displays and is not associated with any operations, so there will be no compatibility.

### InLong Component

InLong Manager, InLong Dashboard

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

- [ ] https://github.com/apache/inlong/issues/8504
- [ ] https://github.com/apache/inlong/issues/8507

**Comment by gosonzhang** [comment]
Thanks @fuweng11, I'll do it
