### ISSUE TITLE
[Bug] Can't reproduce the experiment. ERROR: Connect to manager:8083 [manager/172.26.0.6] failed: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by discivigour** [apache/inlong#8545]
### What happened

When I reproduce the experiment at the web https://mp.weixin.qq.com/s/gRVY00PyORbKXDo15nvgWQ, I get the error log in the agent container: ERROR: Connect to manager:8083 [manager/172.26.0.6] failed: Connection refused (Connection refused).

 Why? 

Besides, Wnen I run the kafka as the experiment, the kafka container get error:Error connecting to node kafka:9092(id:0 rack:null). But When I change the "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092" into "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.183.132:9092", I succeed. 

### What you expected to happen

I can't extract the data and put it to clickhousr db

### How to reproduce

just as the  web https://mp.weixin.qq.com/s/gRVY00PyORbKXDo15nvgWQ does the third step. Once I execute the command "docker compose up -d" and the inlong service start, the agent container will get the error.log.

### Environment

Virtual machine centos7+docker24.0.2+inlong1.7-bin.
Due to docker24.0.2, I use the command "docker compose"  to start the service instead of "docker-compose"

### InLong version

1.7.0

### InLong Component

InLong Manager, InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@discivigour please make sure your docker-compose environment is ok, especially the network. you could create other docker-compose applications to check the network.
