### ISSUE TITLE
[Bug] [Manager] Exception Occurs When Creating a New User in Windows Development Environment

### ISSUE THREAD

**Issue by siLiang220** [apache/inlong#8566]
### What happened

Exception Occurs When Creating a New User in Windows Development Environment
![3a6b15767e14c05669c710b7a1ae100](https://github.com/apache/inlong/assets/47940098/d53aeab1-4c3c-44de-bed6-7b632c4f0c14)
![170731d982e0738cf1c010a18a8c504](https://github.com/apache/inlong/assets/47940098/deca24dc-2237-41ff-b1b4-b7260205161b)

### What you expected to happen

The new user should be created successfully without any exceptions.

### How to reproduce

1. Windows development environment set up
2. Start the front-end Dashboard application.
3. Start the back-end Manager application.
4. Navigate to the User Management section in the Dashboard.
5. Click on the "Create" button.

### Environment

windows 10

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vernedeng** [comment]
Hi @siLiang220, it seems like that the `WindowsPathParser` treat ":" as an illegal char.
I recommend you to deploy InLong in linux or docker enviroments.
