### ISSUE TITLE
[Feature][Sort] Support synchronize data with Apache Spark

### ISSUE THREAD

**Issue by featzhang** [apache/inlong#8584]
### Description

1. Support invoke Spark job with launcher
2. Support Spark task
3. Support distributed current limiting
4. Support automatic rewriting of failed data
5. Support reconciliation of the number of records written

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
InLong would not support Spark, and the community thinks of only using Flink.
