### ISSUE TITLE
[Feature][Manager][Agent][DataProxy] Support full link tracking to improve the observability of the project

### ISSUE THREAD

**Issue by ZhaoNiuniu** [apache/inlong#8611]
### Description

Inlong lacks observability, which is not conducive to link tracking and error location.

### InLong Component

InLong Manager, InLong Agent, InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
@ZhaoNiuniu Please add more design documents to this issue description.
