### ISSUE TITLE
[Bug][Sort] SingleTableCustomFieldsPartitioner package name does not match path

### ISSUE THREAD

**Issue by hnrainll** [apache/inlong#8641]
### What happened

SingleTableCustomFieldsPartitioner package name does not match path.
![image](https://github.com/apache/inlong/assets/1780095/8a06dd45-d219-47e3-8343-7cf7e2c80c90)

### What you expected to happen

SingleTableCustomFieldsPartitioner package name  match path.

### How to reproduce

SingleTableCustomFieldsPartitioner package name  match path.

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Yizhou-Yang** [comment]
I‘ll take a look, thank you for pointing this out

**Comment by hnrainll** [comment]
@Yizhou-Yang Please help me review the code, thanks a lot!
