### ISSUE TITLE
[Improve][Manager] Add tenant related OpenAPI

### ISSUE THREAD

**Issue by vernedeng** [apache/inlong#8663]
### Description

Add all tenant related openAPI

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vernedeng** [comment]
@castorqin

**Comment by castorqin** [comment]
ok,I will do it

> @castorqin
