### ISSUE TITLE
[Improve][Manager] Elasticsearch - Modify the calling method from SDK to HTTP

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8676]
### Description

The available API could refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by alph00** [comment]
I would like to work on this issue

**Comment by jywang616** [comment]
I would like to work on this issue
