### ISSUE TITLE
[Improve][Manager] Flink - Modify the calling method from SDK to HTTP

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8677]
### Description

The available API could refer to https://nightlies.apache.org/flink/flink-docs-master/docs/ops/rest_api/

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Every365** [comment]
I would like to work on this issue

**Comment by dockerzhang** [comment]
this issue is not necessary after the package size shrinks.
