### ISSUE TITLE
[Improve][Manager] Add a common implementation for HTTP calls

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8678]
### Description

Add a common implementation for HTTP calls, that could avoid each Service using different ways.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by alph00** [comment]
I would like to work on this issue

**Comment by haibo-duan** [comment]
Class org.apache.inlong.manager.common.util.HttpUtils is already a common implementation for HTTP calls. This issue may be duplicated.
