### ISSUE TITLE
[Improve][Security] netty-handler SniHandler 16MB allocation

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8681]
### Description

![image](https://github.com/apache/inlong/assets/18047329/4ab269e4-f996-45a0-aec4-8249848bf90e)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SCUTking** [comment]
I would like to work on this issue
