### ISSUE TITLE
[Improve][Security] Guava vulnerable to insecure use of temporary directory

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8682]
### Description

![image](https://github.com/apache/inlong/assets/18047329/6b41030e-6cae-4d90-a7d0-3666da672faa)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Every365** [comment]
I would like to work on this issue

**Comment by jywang616** [comment]
I would like to work on this issue
