### ISSUE TITLE
[Improve][Security] OutOfMemoryError for large multipart without filename in Eclipse Jetty

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8683]
### Description

![image](https://github.com/apache/inlong/assets/18047329/94aa36fe-2c13-433c-91f8-f2844165245d)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Alexdzk** [comment]
I would like to work on this issue
