### ISSUE TITLE
[Improve][Security] Vite Server Options (server.fs.deny) can be bypassed using double forward-slash (//)

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8684]
### Description

![image](https://github.com/apache/inlong/assets/18047329/d608babc-37cf-46ad-b4fd-579e16e15cdd)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by H0924cc** [comment]
I would like to work on this issue
