### ISSUE TITLE
[Improve][Security] Denial of service due to parser crash

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8685]
### Description

![image](https://github.com/apache/inlong/assets/18047329/26f97c62-6961-44e3-827e-72ea1d80d08b)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by H0924cc** [comment]
I would like to work on this issue

**Comment by CorneliusDeng** [comment]
I would like to work on this issue
