### ISSUE TITLE
[Improve][Security] TemporaryFolder on unix-like systems does not limit access to created files

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8686]
### Description

![image](https://github.com/apache/inlong/assets/18047329/f7022e48-9cfe-4911-ac3b-5904cdb3d927)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sunrisefromdark** [comment]
I would like to work on this issue

**Comment by sunrisefromdark** [comment]
Sorry, I accidentally closed the pull request due to a mistake on my part,I would like to work on this issue
