### ISSUE TITLE
[Improve][Security] Apache Pulsar Java Client vulnerable to Improper Certificate Validation

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8687]
### Description

![image](https://github.com/apache/inlong/assets/18047329/41050f18-e304-4c4c-93c5-e4d6b11c75bb)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CorneliusDeng** [comment]
I would like to work on this issue
