### ISSUE TITLE
[Improve][Security] Incorrect Authorization in MySQL Connector Java

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8688]
### Description

![image](https://github.com/apache/inlong/assets/18047329/f375b843-9dde-4bc4-ac4a-3ba625b4d91f)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liaosunny123** [comment]
I would like to work on this issue
