### ISSUE TITLE
[Improve][Security] TemporaryFolder on unix-like systems does not limit access to created files 

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8690]
### Description

![image](https://github.com/apache/inlong/assets/18047329/4232a651-eef1-47cc-ba16-330f34cdc99c)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by williamli-15** [comment]
I would like to work on this issue

**Comment by jywang616** [comment]
I would like to work on this issue

**Comment by dockerzhang** [comment]
![image](https://github.com/apache/inlong/assets/18047329/f57df545-35f7-4986-92a0-e82d550804bb)

The newest version is `4.13.2`, and InLong has already changed to this version, so I think this PR isn't needed now.
