### ISSUE TITLE
[Improve][Security] The `size` option isn't honored after following a redirect in node-fetch

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8691]
### Description

![image](https://github.com/apache/inlong/assets/18047329/86e99eba-173f-4d0d-8952-5beffe23b0e3)

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liaosunny123** [comment]
I would like to work on this issue
