### ISSUE TITLE
[Improve][TubeMQ] set error code 0 when it works

### ISSUE THREAD

**Issue by liaosunny123** [apache/inlong#8712]
### Description

TubeMQ Master will respond error code 200 in the retValue when it works, however the wrapped error code is 0.
The two is not consistent and I think making error code 0 both will be a good idea.

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
This issue is duplicated with https://github.com/apache/inlong/issues/8716, I'll close this
