### ISSUE TITLE
[Bug][TubeMQ] set error code 0 when it works 

### ISSUE THREAD

**Issue by liaosunny123** [apache/inlong#8716]
### What happened

TubeMQ Master will respond error code 200 in the retValue when it works, however the wrapped error code is 0.
The two is not consistent and I think making error code 0 both will be a good idea.

### What you expected to happen

Set both 0 means ok.

### How to reproduce

Every api may carrys these problems.
For example:
<img width="464" alt="391d73721216191b50a66c5e2ff3c84" src="https://github.com/apache/inlong/assets/30096937/804ced2b-b8af-4750-a160-7210b19c6fda">
The child data use 200 OK to mean success, however, the wrapped retInfo use 0 to mean Ok

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
It is indeed a bug, and it is a very hidden problem!

@liaosunny123, thanks!

**Comment by gosonzhang** [comment]
@liaosunny123, please adjust the implementation of 8722 according to the above content, thanks!

**Comment by liaosunny123** [comment]
> @liaosunny123, please adjust the implementation of [8722 ](https://github.com/apache/inlong/pull/8722) according to the above content, thanks!

solved in https://github.com/apache/inlong/pull/8722/commits/a6f1a237ebeb9c86297afd4d647e035236f9fb63, however it seems that it has been fixed in https://github.com/apache/inlong/pull/8724
