### ISSUE TITLE
[Bug][TubeMQ] There is a bug in the consumer group details of TubeMQ Master managing WEB

### ISSUE THREAD

**Issue by FvvSuu** [apache/inlong#8738]
### What happened

![image](https://github.com/apache/inlong/assets/53012896/5fc9b9cc-ccc0-4a39-bb39-0387a8363233)

![image](https://github.com/apache/inlong/assets/53012896/036ee89b-bea4-4ca5-9894-fffdc19d7ead)

### What you expected to happen

The previous version returned partId + brokerAddr + topicname, but now it returns partitionKey+brokerAddr, which caused the WEB UI parsing exception
![image](https://github.com/apache/inlong/assets/53012896/bf7f2cf3-3817-4fd5-bb5b-818cb0decc6c)

### How to reproduce

click URL：http://${master_host}:${master_port}/consume/detail.html?consumeGroup=${consumeGroup}

### InLong version

1.8.0

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@FvvSuu, thanks, I got it!

**Comment by FvvSuu** [comment]
> @FvvSuu, thanks, I got it!

Sorry, the question was submitted incorrectly, it is our internal issue

**Comment by gosonzhang** [comment]
Found that the latest version is not aligned with your code, maybe you have modified the code, welcome to contribute features,thanks!
