### ISSUE TITLE
[Bug][Manager] Response of data preview was empty

### ISSUE THREAD

**Issue by castorqin** [apache/inlong#8751]
### What happened

<img width="960" alt="image" src="https://github.com/apache/inlong/assets/58140421/c7daf905-e2d9-4d73-ad33-d6ad1f40d9b4">
The inlong group has been reporting data, but the data preview cannot be queried

### What you expected to happen

return multiple messages normally

### How to reproduce

1、Create an inlong group, select pulsar as MQ, and set the pulsar queue model as serial. 
2、Use sdk to report data,
3、Use the data preview function

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vernedeng** [comment]
@castorqin
