### ISSUE TITLE
[Improve][TubeMQ] tubemq-client-go lacks log level configuration API

### ISSUE THREAD

**Issue by smarteng** [apache/inlong#8791]
### Description

现在 github.com/apache/inlong/inlong-tubemq/tubemq-client-twins/tubemq-client-go 的日志级别是固定的warn，系统可以设置日志级别来输出日志，排查问题。

======================================================================

Now the log level of github.com/apache/inlong/inlong-tubemq/tubemq-client-twins/tubemq-client-go is fixed to warn, which is inconvenient to check.

The system can be improved by increasing the log level configuration API, which can output different detailed logs according to needs, which is convenient for troubleshooting.

### Are you willing to submit PR?

- [x] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@smarteng, thanks for contribution!

**Comment by dockerzhang** [comment]
@smarteng do you still work on this issue?

**Comment by dockerzhang** [comment]
https://github.com/apache/inlong/pull/10040 will continue to solve this problem.
