### ISSUE TITLE
[Feature][Dashboard] Plugin supports images

### ISSUE THREAD

**Issue by leezng** [apache/inlong#8804]
### Description

Associated pre-PR #8770 

Current process:
```
Plugin -> UI Pages -> UI Components -> Match images
```

The newly designed process:

```
Plugin with images -> UI Pages -> UI Components
```

At present, various data source plugins do not integrate their images, making their relationship seem to be separated.

Secondly, the images of each data source are matched in the UI components, which also leads to the coupling of UI components and images.

A better design method is: the images of the data source are defined in the plugins, and the UI page rendering can be directly read.

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by healchow** [comment]
@richardji202 Could you please reply this comment? Then I can assign this issue to you, thanks.

**Comment by richardji202** [comment]
> @richardji202 Could you please reply this comment? Then I can assign this issue to you, thanks.

ok?
