### ISSUE TITLE
[Bug][Metrics][TubeMQ] The Prometheus server cannot get data from the TubeMQ Metrics of master and broker

### ISSUE THREAD

**Issue by fancycoderzf** [apache/inlong#8807]
### What happened

The Prometheus server cannot get data from the TubeMQ Metrics of master and broker.
The following are some files or data:
1) broker.ini
![image](https://github.com/apache/inlong/assets/47296299/5298e0cd-a3c4-4da9-ae86-cc761857afab)
2) data I get from the Web page(localhost:9181/metrics)
![image](https://github.com/apache/inlong/assets/47296299/4269a69e-54ed-488b-a695-5433c275a995)
3) prometheus.yml configuration file
![image](https://github.com/apache/inlong/assets/47296299/770313dc-93e0-4027-8550-33cf71568f4a)
However, when I visited the Prometheus server Status page of Targets, I got this
![image](https://github.com/apache/inlong/assets/47296299/9af1fc92-4612-42d1-aeae-a70f0818bbb2)
I have no idea how to fix this. 

### What you expected to happen

The Prometheus Server can get data from the TubeMQ metrics.

### How to reproduce

Start up a TubeMQ Server and a Prometheus Server, and modify the related config file to get the same results.

### Environment

Ubuntu 20.04.5 LTS
prometheus, version 2.46.0

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
Thanks @fancycoderzf!

I see from the screenshot that there are 2 items with non-zero values, which means that the statistical logic is in effect. Is it because the running time is too short and almost of all are no data for the corresponding statistical items?

![image](https://github.com/apache/inlong/assets/14038849/d421df9d-97ed-469d-864c-cdbbaf525f4a)

**Comment by fancycoderzf** [comment]
Thank you. I'm trying to work on issue #6756. Yes, I can see the Web page got the data successfully, and the problem I got is that I cannot get any data in the Prometheus Server(But it can get other exporter's data, such as node_exporter). Thus, I cannot get any data using Grafana. Maybe this is a problem caused by the custom exporter implemented in the TubeMQ, or just caused by my Prometheus Server. I'm not sure, and maybe my understanding is wrong
