### ISSUE TITLE
[Improve][Tubemq] Missing parameter

### ISSUE THREAD

**Issue by SCUTking** [apache/inlong#8812]
### Description

The parameter of the AddTopicReq class is missing memCacheMsgSizeInMB compared to the HTTP API parameter.
![image](https://github.com/apache/inlong/assets/106209956/8c6b909f-ecb3-44fe-a9d0-c1f0a070b238)
![image](https://github.com/apache/inlong/assets/106209956/95337ad2-c5ad-4af3-bb25-233a72c5cc3e)

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
It does not fully map TubeMQ's API parameters, which feels like this problem should be caused by the omission of the original implementer.

@SCUTking, would you like to take some time to fix it?

**Comment by SCUTking** [comment]
I am very happy to fix it.

**Comment by gosonzhang** [comment]
@SCUTking, thanks!
