### ISSUE TITLE
[Bug][Manager] Stop Inlong Group ID Fail

### ISSUE THREAD

**Issue by xuesongxs** [apache/inlong#8870]
### What happened

Inlong v1.7

If a stop operation is performed on a running inlong group, the page will report a stop failure. If a start operation is performed on a inlong group, it will also fail. Below are screenshots of the operation for the inlong group with only auto push and the two data inlong groups with auto push and sort.

Group1: auto-push
![image](https://github.com/apache/inlong/assets/54351417/4afc2a66-83bd-47b5-aad8-e6077cd5e442)
![image](https://github.com/apache/inlong/assets/54351417/c4f3bb65-0f1b-4efb-b155-04083db5c568)
![image](https://github.com/apache/inlong/assets/54351417/8eaf0763-8bb7-44af-abf3-083d238efcf0)
![image](https://github.com/apache/inlong/assets/54351417/636f28e3-3edc-4fee-81bb-63ff81311209)

Group2:auto-push + sort
![image](https://github.com/apache/inlong/assets/54351417/d9ddbb7a-5899-4a20-b105-42f10863affe)
![image](https://github.com/apache/inlong/assets/54351417/0d40c6ba-bad2-4b0b-8d90-55b342dfae43)
![image](https://github.com/apache/inlong/assets/54351417/b666b1ce-bb6d-4a9a-ac7d-10b0fd41a026)
![image](https://github.com/apache/inlong/assets/54351417/b70e04bd-3397-4890-965c-3184993d784b)

manager log:
[manager-all.log](https://github.com/apache/inlong/files/12557693/manager-all.log)

### What you expected to happen

Both start and stop the inlong group can be successful.

### How to reproduce

Look at the picture above.

### Environment

CentOS

### InLong version

1.7.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@fuweng11 PTAL, thanks.

**Comment by fuweng11** [comment]
This issue has been fixed in version 1.11.0.

**Comment by fuweng11** [comment]
This issue has been fixed in version 1.11.0.
