### ISSUE TITLE
[Release] Publish all 1.9.0 images to docker hub

### ISSUE THREAD

**Issue by luchunliang** [apache/inlong#8880]
### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
![image](https://github.com/apache/inlong/assets/18047329/7a072fea-54b7-4798-86cf-cfaa9437d061)
