### ISSUE TITLE
[Bug][DataProxy] The log's path for DataProxy is wrong

### ISSUE THREAD

**Issue by dockerzhang** [apache/inlong#8936]
### What happened

![image](https://github.com/apache/inlong/assets/18047329/7b28be4e-c4d8-45ce-90f2-e1bf77ad63a9)

### What you expected to happen

The log's path for DataProxy is right.

### How to reproduce

Install from the latest version.

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment]
@dockerzhang, thanks, let me see, why does the environment I use not have this problem?!

**Comment by gosonzhang** [comment]
This problem arises from [1]: when $ENABLE_OBSERVABILITY is false, the execution command does not carry the $JAVA_OPTS parameter, causing the DataProxy to not carry the log path information when it is started, causing this problem.

1. https://github.com/apache/inlong/pull/8802/files#diff-b41eca090b17d52c4ff29152b39375e1361ffa6b9a18e9da6e59c527d232520dL227
![image](https://github.com/apache/inlong/assets/14038849/3d9bcc40-dda8-4ada-a939-836b872010c4)

I'll fix it
