### ISSUE TITLE
[Bug] There is a problem using mysql-to-mysql with sort

### ISSUE THREAD

**Issue by LiJie20190102** [apache/inlong#9199]
### What happened

The data synchronization task I created is from MySQL to MySQL. I use the command line to operate sort, and the database information is correct. However, I see that the jobmanager log on Flink shows that I cannot find the source table I want. Do I need to configure any filtering conditions to do this

mysql2mysql.sql

```
CREATE TABLE `table_11`(
    `name` STRING)
    WITH (
    'connector' = 'mysql-cdc-inlong',
    'hostname' = '192.168.1.133',
    'database-name' = 'inlong_test',
    'port' = '13306',
    'username' = 'root',
    'password' = 'qsdi1@3',
    'table-name' = 'source_test'
);

CREATE TABLE `table_22`(
    PRIMARY KEY (`name`) NOT ENFORCED,
    `name` STRING)
    WITH (
'connector' = 'jdbc-inlong',
    'url' = 'jdbc:mysql://192.168.1.133:13306/inlong_test',
    'username' = 'root',
    'password' = 'qsdi1@3',
    'table-name' = 'target'
);

INSERT INTO `table_22`
    SELECT
    `name` AS `name`
    FROM `table_11`;
```
	
	
CLI:
/opt/software/flink/flink-1.13.6/bin/flink run -c org.apache.inlong.sort.Entrance /usr/lib/inlong/inlong-sort/sort-dist-1.9.0.jar --sql.script.file /home/lj/inlong/mysql2mysql.sql

flink jobmanager log:
![image](https://github.com/apache/inlong/assets/53458004/0da1df4e-04df-4964-ac65-523f1ef75aca)
The log shows that there is actually this table, but it has been filtered out.
![image](https://github.com/apache/inlong/assets/53458004/744ba0b6-7e50-41c9-8342-a4dc5ad3ba32)

![image](https://github.com/apache/inlong/assets/53458004/27f6cfa5-0ab6-4f5e-8436-3aa2d708fd50)

### What you expected to happen

Can correctly synchronize MySQL to MySQL data

### How to reproduce

mysql2mysql.sql

```
CREATE TABLE `table_11`(
    `name` STRING)
    WITH (
    'connector' = 'mysql-cdc-inlong',
    'hostname' = '192.168.1.133',
    'database-name' = 'inlong_test',
    'port' = '13306',
    'username' = 'root',
    'password' = 'qsdi1@3',
    'table-name' = 'source_test'
);

CREATE TABLE `table_22`(
    PRIMARY KEY (`name`) NOT ENFORCED,
    `name` STRING)
    WITH (
'connector' = 'jdbc-inlong',
    'url' = 'jdbc:mysql://192.168.1.133:13306/inlong_test',
    'username' = 'root',
    'password' = 'qsdi1@3',
    'table-name' = 'target'
);

INSERT INTO `table_22`
    SELECT
    `name` AS `name`
    FROM `table_11`;
```
	
	
CLI:
/opt/software/flink/flink-1.13.6/bin/flink run -c org.apache.inlong.sort.Entrance /usr/lib/inlong/inlong-sort/sort-dist-1.9.0.jar --sql.script.file /home/lj/inlong/mysql2mysql.sql

### InLong version

1.9.0

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@EMsnap PTAL

**Comment by yunqingmoswu** [comment]
@LiJie20190102 You need to config the table name with a database such as 'database.table'. It is 'inlong_test .source_test'
  in your demo.
  
<img width="1127" alt="image" src="https://github.com/apache/inlong/assets/44659300/86bfc337-6e85-4f59-a79f-e955fcd927d5">

**Comment by LiJie20190102** [comment]
Do I still need to add a library name to the target table? After I added it, there was an exception in the jobmanager. The job is still running, but there is no data in the target table.
![image](https://github.com/apache/inlong/assets/53458004/3bd0caaa-bded-4c2a-a3e5-2d588b545560)
![image](https://github.com/apache/inlong/assets/53458004/a760dc27-6a57-4296-80a3-a1463b44bcf5)

**Comment by LiJie20190102** [comment]
Functionally functional, the complete file is as follows：
			
CREATE TABLE `table_11`(
    `id` bigint,
	PRIMARY KEY(id) NOT ENFORCED
	)
    WITH (
    'connector' = 'mysql-cdc-inlong',
    'hostname' = '192.168.1.133',
    'database-name' = 'inlong_test',
    'port' = '13306',
    'username' = 'root',
    'password' = 'qsdi1@3',
    'table-name' = 'inlong_test.source1'
);

CREATE TABLE `table_22`(
    PRIMARY KEY (`id`) NOT ENFORCED,
    `id` bigint)
    WITH (
'connector' = 'jdbc-inlong',
    'url' = 'jdbc:mysql://192.168.1.133:13306/inlong_test',
    'username' = 'root',
    'password' = 'qsdi1@3',
    'table-name' = 'target1'
);

INSERT INTO `table_22`
    SELECT
    `id` AS `id`
    FROM `table_11`;
