### ISSUE TITLE
[Feature][Manager]Support Tube MQ sink

### ISSUE THREAD

**Issue by castorqin** [apache/inlong#9303]
### Description

Support Tube MQ sink

### Use case

Support Tube MQ sink

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vernedeng** [comment]
This issue will be done in the following version, but now.
