### ISSUE TITLE
[Improve][Sort] Errors in UT test logs for sort-end-to-end-tests, but UT results show as successful

### ISSUE THREAD

**Issue by hnrainll** [apache/inlong#9402]
### Description

- Case 1
https://github.com/apache/inlong/actions/runs/7081425279/job/19270686450
![image](https://github.com/apache/inlong/assets/1780095/479904a9-14c9-4603-bcec-eb9d4883ba89)

- Case 
https://github.com/apache/inlong/actions/runs/7081189588/job/19270165431?pr=9395
![image](https://github.com/apache/inlong/assets/1780095/8d7a2757-8cd1-4fc6-bcec-9ed278e48026)

Errors in UT test logs for sort-end-to-end-tests, but UT results show as successful.

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoYou201** [comment]
Case1 causes a warning due to a problem with the Java version, In #9940 , change the flink java version to 1.8.
Case2 causes a error due to a other module influent network adapter, In #9924 and #9869 , modify the ci_ut.yaml and add ci_ut_flink13.yaml to solve it.
