### ISSUE TITLE
[Bug][Sort] Missing MySQL CDC connector for Flink 1.15

### ISSUE THREAD

**Issue by haifxu** [apache/inlong#9417]
### What happened

Missing MySQL CDC connector for Flink 1.15
![image](https://github.com/apache/inlong/assets/58519431/4d01b025-d377-4966-807d-9a8bd9b49a18)

### What you expected to happen

Add MySQL CDC connector for Flink 1.15

### How to reproduce

Download `apache-inlong-1.10.0-SNAPSHOT-sort-connectors-flink-v1.15.tar.gz`.

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hnrainll** [comment]
I'll fix the bug.
