### ISSUE TITLE
[Feature][Sort] Pulsar connector support process time meta field 

### ISSUE THREAD

**Issue by EMsnap** [apache/inlong#9487]
### Description

[Feature][Sort] Pulsar connector support process time meta field 

### Use case

add a new metafield for process time 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoYou201** [comment]
This issue was fixed by pr #10574
