### ISSUE TITLE
[Bug] Logging error for the NativeFlinkSqlParser 

### ISSUE THREAD

**Issue by JinsYin** [apache/inlong#9493]
### What happened

Logging error for the [NativeFlinkSqlParser](https://github.com/apache/inlong/blob/master/inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java#L46).

### What you expected to happen

Using the correct class name.

### How to reproduce

Always

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@JinsYin please add more details abort this issue, thanks.
