### ISSUE TITLE
[Improve][Sort] Doris full database migration missing audit data

### ISSUE THREAD

**Issue by haifxu** [apache/inlong#9507]
### Description

Doris full database migration missing audit data

![企业微信截图_17031481992395](https://github.com/apache/inlong/assets/58519431/f779274f-bc43-4d78-a74c-d9f0939c0342)

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aloyszhang** [comment]
Audit module has been refactored, close this issue.
