### ISSUE TITLE
[Improve][Sort] sort-format-common fails to compile in macOS M1

### ISSUE THREAD

**Issue by hnrainll** [apache/inlong#9656]
### Description

<img width="1461" alt="Screenshot 2024-02-01 at 16 36 26" src="https://github.com/apache/inlong/assets/1780095/85488f28-0653-4194-ae49-3a8439948ddd">

com.google.protobuf:protoc:2.5.0 macOS M1 is not supported

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
The Sort module only supports protobuf 2.5.0 now, but we plan to update protobuf to 3.x in the next version, and this issue could be fixed.
