### ISSUE TITLE
[Bug] Stream-InitSink failed

### ISSUE THREAD

**Issue by Nicole1983** [apache/inlong#9661]
### What happened

I am trying to fetch data from cloud MySQL to cloud MySQL by Pulsar
1. add cluster
![bug1](https://github.com/apache/inlong/assets/15648117/ba9e23fe-1803-40f7-957b-9f873a555a08)
2. add data node
![bug2](https://github.com/apache/inlong/assets/15648117/da036bbb-9006-4823-9262-7206cf12723a)
3. config data ingestion
![bug3](https://github.com/apache/inlong/assets/15648117/b65454cf-f7e5-4b82-a070-5c223d9bfa6f)

### What you expected to happen

the system show fail

### How to reproduce

I've pasted the picture

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
![image](https://github.com/apache/inlong/assets/18047329/6dfae2b1-26e0-43b2-92d7-00c41b705bc5)

**Comment by Nicole1983** [comment]
你好，mysql这个语法错误解决之后，还是出现config_failed的错误
![image](https://github.com/apache/inlong/assets/15648117/218bc181-1b0a-4abf-acec-84d67aea6684)
这个该怎么查呢？
新手刚刚开始用InLong，想用InLong从腾讯云MySQL上拉数据到腾讯云MySQL，麻烦详情讲一下吧，非常感激！

**Comment by dockerzhang** [comment]
please see the log details to get the specific cause.
