### ISSUE TITLE
[Bug] failed to initSort as fieldRelations is empty

### ISSUE THREAD

**Issue by Nicole1983** [apache/inlong#9681]
### What happened

![image](https://github.com/apache/inlong/assets/15648117/353a8d18-9a5d-4da2-9e36-f30cd2e18a02)

a.i.m.w.e.LogableEventListener:88 - execute listener WorkflowEventLogEntity(id=null, processId=20, processName=CREATE_GROUP_RESOURCE, processDisplayName=Create Group, inlongGroupId=sync004, taskId=45, elementName=InitSort, elementDisplayName=Group-InitSort, eventType=TaskEvent, event=COMPLETE, listener=SortConfigListener, startTime=Tue Feb 06 13:31:35 CST 2024, endTime=null, status=-1, async=0, ip=172.25.0.8, remark=null, exception=failed to build sort config for groupId=sync004, fieldRelations is empty) error:
org.apache.inlong.manager.common.exceptions.WorkflowListenerException: failed to build sort config for groupId=sync004, fieldRelations is empty

配置数据同步，运行之后，得到以上错误log
看了issue https://github.com/apache/inlong/issues/5157，这个是不是个bug呢？

### What you expected to happen

期望按照指引配置完之后，可以顺利同步数据，不出现配置失败的提示

### How to reproduce

使用docker搭建了InLong之后，配置集群、数据同步

### Environment

![image](https://github.com/apache/inlong/assets/15648117/f924ad05-d12b-4ee7-a458-12d648fa86f4)

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EMsnap** [comment]
sorry can you show your configuration for the job and field relations ?

**Comment by Nicole1983** [comment]
你好，请参见以下配置
集群设置
![image](https://github.com/apache/inlong/assets/15648117/28bf3838-59dd-4303-a267-111bc86994f3)
数据同步 -> 数据流配置
![image](https://github.com/apache/inlong/assets/15648117/402b29d3-1fc2-4566-85a9-2c2651d59a8c)
数据源配置
![image](https://github.com/apache/inlong/assets/15648117/109b8191-7d26-4bcb-b057-447e71972825)
数据转换配置
![image](https://github.com/apache/inlong/assets/15648117/7d22d1c3-e700-4b36-b1fd-cc96422102f2)
数据目标的配置
![image](https://github.com/apache/inlong/assets/15648117/a5d57dd7-9e9a-446b-857a-86121bcdb118)
