### ISSUE TITLE
[Bug] time to remove Akka and use Apache Pekko?

### ISSUE THREAD

**Issue by pjfanning** [apache/inlong#9683]
### What happened

Akka is no longer OSS and has CVEs

Apache Pekko is an open source fork and a pretty straightforward switch - https://pekko.apache.org/docs/pekko/current/project/migration-guides.html

### What you expected to happen

use OSS libs

### How to reproduce

n/a

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
@justinwwhuang PTAL, thanks.

**Comment by dockerzhang** [comment]
Akka is not used anymore, we could remove it.
