### ISSUE TITLE
[Improve][Sort] Update protobuf-java version in sort module

### ISSUE THREAD

**Issue by baomingyu** [apache/inlong#9715]
### Description

 Update protobuf-java version in sort module

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
it's better to unify one version.
