### ISSUE TITLE
[Feature][Sort] Add ElasticSearch connector on Flink 1.15 

### ISSUE THREAD

**Issue by EMsnap** [apache/inlong#9730]
### Description

Add ElasticSearch connector on Flink 1.15 

### Use case

Add ElasticSearch connector on Flink 1.15 

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aloyszhang** [comment]
duplicated with #10740, close this issue
