### ISSUE TITLE
[Umbrella][Agent] Add an agent installer module for agent installation

### ISSUE THREAD

**Issue by justinwwhuang** [apache/inlong#9801]
## Motivation 
Due to the fact that in actual deployment environments, the machine on which the inlong agent is located is often not controlled by the platform. Therefore, the inlong agent needs to have the ability to self upgrade. Agent installers are introduced for the installation and self upgrading of agents. He does not need to rely on third-party installation platforms and can achieve a closed loop of agent installation and upgrade capabilities.
## Solution
Agent installers have five atomic operations:
1. Download installation package
2. Install through installation package
3. Start process
4. Stop process
5. Uninstall
The agent installer periodically pulls configuration information from the manager and compares the new and old configurations to obtain three results. Each result corresponds to a process, and each process performs a fixed number of atomic operations.
![image](https://github.com/apache/inlong/assets/26856549/9815572a-ecc7-4fd1-991a-cbcd33877680)
## add flow
manager config
![image](https://github.com/apache/inlong/assets/26856549/4d6c4698-a1cc-4c73-8a6f-ad1aa629f5fa)
local config
![image](https://github.com/apache/inlong/assets/26856549/4edf17ec-9433-4505-9aaa-6e9cea18721a)
## Local config module list is empty, manager config module list has one module, then add flow is actived. And 1 2 3 atomic operations will be execued:
- atomic operations 1 will use install package relatived config to download package
![image](https://github.com/apache/inlong/assets/26856549/fbc29337-7088-48ce-ba28-5703991778a5)
- atomic operations 2 will use installCommand to install the module
![image](https://github.com/apache/inlong/assets/26856549/d654fffa-0784-4c2d-87d0-d691268ff7f4)
- atomic operations 3 will use startCommand to start the module
![image](https://github.com/apache/inlong/assets/26856549/eefbe07d-fbd4-485c-802f-df767b156ca9)
Then, the module is installed.
## update flow
manager config
![image](https://github.com/apache/inlong/assets/26856549/edc43352-132d-418d-b8e2-f44481147b60)
local config
![image](https://github.com/apache/inlong/assets/26856549/40db577c-62cb-4ac7-bcc4-2e92d5ac67e1)
## Local config and manager config has the same module id, but the md5 has changed, update flow is actived. And 1 4 5 2 3 atomic operations will be execued:
- atomic operations 1 will use install package relatived config to download package
![image](https://github.com/apache/inlong/assets/26856549/d0632bdc-1510-4637-828b-3f08c8b4b1cd)
- atomic operations 4 will use stopCommand to stop the module
![image](https://github.com/apache/inlong/assets/26856549/e3b2e94f-e674-4ef5-a3e7-98f13d9c16da)
- atomic operations 5 will use uninstallCommand to uninstall the module
![image](https://github.com/apache/inlong/assets/26856549/a895eaba-3ecf-4f12-afa3-b6ca86b18323)
- atomic operations 2 will use installCommand to install the module
![image](https://github.com/apache/inlong/assets/26856549/df34cfc9-e36c-4be6-9c83-caf95ca1aa25)
- atomic operations 3 will use startCommand to start the module
![image](https://github.com/apache/inlong/assets/26856549/17b58e26-fe70-474b-a3a8-f84f73df4956)
### Task list

- [x] #9802 
- [x] #9806 
- [x] #9816 
- [x] #9829 
- [x] #9831 
- [x] #9833 
- [x] #9844 
- [x] #9848 
- [x] #9850 
- [x] #9852
- [x] #9858
- [x] #9859
- [x] #9889 
- [x] #9906
- [x] #9909 
- [x] #9910
- [x] #9922

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dockerzhang** [comment]
close it for all sub-tasks finshed.
