### ISSUE TITLE
[Bug][Sort] DorisLoadNode repeat

### ISSUE THREAD

**Issue by bigide-dataops** [apache/inlong#9875]
https://github.com/apache/inlong/blame/92794e15f3a418ce2396f911f61cc38b41a3b9b0/inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java#L83

**Comment by EMsnap** [comment]
Yes, something needs to be fixed, any interest on submitting a pr for this ?
