### ISSUE TITLE
[Improve][Manager] Add unit test of AuditController

### ISSUE THREAD

**Issue by balloon72** [apache/inlong#9881]
### Description

What happened
add ut AuditController

What you expected to happen
add ut AuditController

How to reproduce
add ut AuditController

Environment
add ut AuditController

InLong Component
inlong-manager

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuweng11** [comment]
The audit data is reported by each component themselves, and UT cannot verify whether the data reported by each component meets expectations, so there is no need to add this interface test.
